const main = document.querySelector('#main');
const config = window.VDK_CONFIG || {};
const apiBase = (config.apiBase || '').replace(/\/$/, '');
let user = null;
let settings = null;
let pageEpoch = 0;
const esc = (v = '') => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = v => new Intl.DateTimeFormat('sv-SE', { dateStyle: 'medium' }).format(new Date(v));
const time = v => `${Math.floor(v / 60).toString().padStart(2,'0')}:${Math.floor(v % 60).toString().padStart(2,'0')}`;
const icons = {
  people: '<circle cx="16" cy="14" r="6"/><circle cx="34" cy="16" r="5"/><path d="M4 42v-7c0-8 24-8 24 0v7ZM31 28c10-2 14 3 14 8v6H33"/>',
  growth: '<path d="M5 43V28h9v15ZM20 43V18h9v25ZM35 43V5h9v38"/><path d="m5 20 12-9 9 2L40 2"/>',
  shield: '<path d="M24 3 43 10v13c0 12-10 20-19 25C15 43 5 35 5 23V10Z"/><path d="m14 24 7 7 14-16"/>',
  whistle: '<circle cx="17" cy="31" r="13"/><circle cx="17" cy="31" r="5"/><path d="m26 21 15-9 5 10-17 11M8 8l4 7M23 3v9M36 4l-6 9"/>'
};
function icon(name){return `<svg class="pillar-icon" viewBox="0 0 50 52" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;}
function page(title, intro, body, eyebrow = 'Värmlands Domarkollektiv') {
  return `<section class="page container"><div class="page-head"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${intro ? `<p class="lead">${intro}</p>` : ''}</div>${body}</section>`;
}
function notice(text, type=''){return `<div class="notice ${type}" role="${type==='error'?'alert':'status'}">${text}</div>`;}
function empty(title, body){return `<div class="empty-state"><h3>${title}</h3><p>${body}</p></div>`;}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.hidden=false;setTimeout(()=>{el.hidden=true},5000);}
async function api(path, { method='GET', body } = {}) {
  let response;
  try {response=await fetch(`${apiBase}/api${path}`, {method,credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});}
  catch {throw new Error('Medlemstjänsten går inte att nå just nu. Försök igen senare.');}
  const type=response.headers.get('content-type')||'';
  if(!type.includes('application/json')) throw new Error('Medlemstjänsten är inte ansluten ännu. Kontakta VDK för medlemskap.');
  const data=await response.json();
  if(!response.ok) throw new Error(data.error||'Något gick fel. Försök igen.');
  return data;
}
async function loadSettings(){if(settings)return settings;try{settings=await api('/settings');}catch{settings={season:'2026/27',fee:100,applicationsOpen:false};}return settings;}
function formError(form, error){let el=form.querySelector('[data-error]');if(el)el.textContent=error.message;}
async function submit(form, action){const button=form.querySelector('button[type="submit"]');button.disabled=true;form.querySelector('[data-error]').textContent='';try{await action(Object.fromEntries(new FormData(form)));}catch(error){formError(form,error);}finally{button.disabled=false;}}
function formFooter(label){return `<p class="form-error" data-error role="alert"></p><button class="button full-width" type="submit">${label}</button>`;}
function field(label,name,type='text',extra=''){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" ${extra}></div>`;}
function home(){return `<section class="hero"><img class="hero-image" src="assets/design-reference.png" alt="" fetchpriority="high"><div class="hero-content"><p class="eyebrow">Värmlands Domarkollektiv</p><h1>TILLSAMMANS FÖR EN<br><span class="yellow">STARKARE DOMARKÅR</span></h1><p class="hero-intro">VDK samlar innebandydomare i Värmland för gemenskap, utveckling och trygghet – på och utanför planen.</p><div class="motto"><strong>AEQUALITAS PRO OMNIBUS</strong><em>Rättvisa för alla.</em></div><div class="hero-actions">${membershipMenu('hero-membership-menu')}<a class="button button-outline" href="#/om-vdk">Läs mer om VDK</a></div></div></section>
  <div class="container"><section class="pillars" aria-label="Det här står vi för">${[['people','Gemenskap','Ett starkare domarnätverk i Värmland.'],['growth','Utveckling','Videocoachning och kunskapsutbyte.'],['shield','Trygghet','Stöd för alla domare, hela säsongen.'],['whistle','Bättre hallmiljö','Tillsammans för en positiv innebandymiljö.']].map(([i,t,p])=>`<div class="pillar">${icon(i)}<div><h2>${t}</h2><p>${p}</p></div></div>`).join('')}</section>
  <section class="rule-banner" aria-labelledby="rule-generator-title"><div><p class="eyebrow">Träna ditt domarskap</p><h2 id="rule-generator-title">VDK Regelgenerator 2026</h2><p>Träna på matchsituationer, testa dina regelkunskaper och utforska regelbanken.</p></div><a class="button" href="innebandyregler/">Öppna regelgeneratorn</a></section><section class="home-cards" aria-label="Aktuellt från VDK"><article class="card card-light"><div class="card-heading"><h2>Senaste nytt</h2><a class="text-link" href="#/nyheter">Visa alla</a></div><p class="empty-news">Här samlar vi nyheter om föreningen, medlemskapet och kommande aktiviteter.</p><p class="empty-news">Inga nyheter är publicerade ännu.</p><a class="text-link" href="#/for-domare">Upptäck våra domarverktyg</a></article><article class="card quote-card"><span class="quote-mark" aria-hidden="true">“</span><blockquote>Bättre domare<br>skapar bättre matcher.</blockquote><cite>Värmlands Domarkollektiv</cite></article><article class="card card-light"><h2>Bli medlem idag</h2><ul class="benefit-list"><li>Stöd vår gemensamma utveckling</li><li>Ta del av videocoachning för seniorinnebandy</li><li>Bidra till en bättre hallmiljö</li><li>Var en del av Värmlands domarnätverk</li></ul><a class="button full-width" href="#/medlemskap">Se våra medlemskap</a></article></section></div>`;}
function about(){return page('Mer än en match.','Vi förenas av uppdraget på planen. Vi växer genom gemenskapen utanför den.',`<div class="reading"><h2>En gemensam plats för Värmlands domare</h2><p>Värmlands Domarkollektiv samlar innebandydomare i Värmland. Vi vill skapa ett starkt nätverk där vi kan dela erfarenheter, utvecklas tillsammans och stötta varandra under hela säsongen.</p><p>Vår utgångspunkt är enkel: rättvisa för alla. För spelare och föreningar, men också för dem som leder matchen.</p></div><div class="content-grid"><article class="card"><h2>Gemenskap och trygghet</h2><p>Att döma ska inte vara ett ensamt uppdrag. VDK är en plats för erfarenhetsutbyte och kollegialt stöd, med en bättre hallmiljö som gemensamt mål.</p></article><article class="card"><h2>Utveckling på egna villkor</h2><p>Personlig matchstatistik och videocoachning för seniorinnebandy ska hjälpa medlemmar att reflektera över bedömningar och utveckla sitt domarskap.</p></article></div><div class="reading"><h2>AEQUALITAS PRO OMNIBUS</h2><p>Rättvisa för alla. Det är mottot som följer oss, på och utanför planen.</p><a class="button" href="#/medlemskap">Bli en del av VDK</a></div>`);}
const membershipNames={active:'Aktiv domare',support:'Stödmedlem',club:'Föreningsmedlem',business:'Företagsstöd'};
const money=value=>new Intl.NumberFormat('sv-SE').format(value)+' kr';
const membershipPaths={active:'aktiv-domare',support:'stodmedlem',club:'foreningsmedlem',business:'foretagsstod'};
const membershipAmounts={active:100,support:100,club:1500,business:1000};
function membershipChoices(){return Object.entries(membershipNames).map(([key,label])=>`<a href="#/medlemskap/${membershipPaths[key]}"><strong>${label}</strong><span>${key==='business'?'Gåva från ':''}${money(membershipAmounts[key])}${key==='business'?'':' / säsong'}</span></a>`).join('');}
function membershipMenu(id){return `<div class="membership-menu-wrap"><button type="button" class="button" data-membership-menu aria-expanded="false" aria-controls="${id}">Bli medlem</button><div class="membership-mini-menu" id="${id}" hidden><p>Välj medlemskap eller stöd</p>${membershipChoices()}</div></div>`;}
function statutesLink(){return config.statutesUrl?`<a class="text-link" href="${esc(config.statutesUrl)}" download>Ladda ner VDK:s stadgar (Word)</a>`:'<a class="text-link" href="#/stadgar">Om VDK:s stadgar</a>';}
function sharedQr(category){const paymentNote=category==='club'?'Ändra beloppet i Swish till 1 500 kr och ange föreningens namn i meddelandet.':category==='business'?'Ändra beloppet i Swish till din gåva, minst 1 000 kr, och ange företagsstöd samt företagets namn i meddelandet.':'Kontrollera beloppet 100 kr och ange ditt namn i meddelandet.';return `<aside class="card qr-card"><h2>Betala med Swish</h2><object class="membership-qr-pdf" data="${esc(config.membershipQrPdf)}#toolbar=0&navpanes=0&view=Fit" type="application/pdf" aria-label="VDK:s gemensamma Swish-kod"><p>Öppna PDF:en via länken nedan för att se QR-koden.</p></object><a class="button secondary qr-open" href="${esc(config.membershipQrPdf)}" target="_blank" rel="noopener">Öppna Swish-koden (PDF)</a><p>Swishnummer: <strong>123 149 49 88</strong></p><p>Samma QR-kod används för alla medlemskategorier och företagsstöd. Den fyller i 100 kr och ”Medlemsavgift 2026/27”.</p><p><strong>${paymentNote}</strong> Kontrollera mottagaren innan du godkänner betalningen.</p></aside>`;}
function membership(){return page('Välj medlemskap eller stöd.','Det finns flera sätt att vara en del av VDK. Välj det som passar dig för att läsa mer.',`<div class="membership-chooser">${membershipChoices()}</div><p class="notice">Aktiva medlemmar har rösträtt enligt stadgarna. Stödmedlemmar kan komma med förslag och har ingen rösträtt. Företagsstöd är en gåva.</p>${statutesLink()}`);}
const membershipInformation={
  active:{title:'Aktiv medlem',intro:'För dig som är aktiv innebandydomare och vill utvecklas tillsammans med Värmlands domarkår.',body:`<h2>Gemenskap på och utanför planen</h2><p>Som aktiv medlem är du en del av ett kollektiv som delar erfarenheter, stöttar varandra och arbetar för en bättre hallmiljö. Du får en plats för din egen domarutveckling och för samtal med kollegor.</p><ul class="benefit-list"><li>Gemenskap och kollegialt stöd</li><li>Mina sidor med verktyg för din domarutveckling</li><li>Videocoachning för seniorinnebandy</li></ul><h2>Din röst i föreningen</h2><p>Som aktiv medlem har du rösträtt när du uppfyller stadgarnas krav för aktivt medlemskap och rösträtt. Du kan vara med och påverka VDK:s riktning och utveckling.</p><h2>Varför ditt medlemskap är viktigt</h2><p>En stark domarkår byggs av domare som engagerar sig. Ditt medlemskap bidrar till att vi kan samla kunskap, utveckla våra verktyg och skapa en tryggare vardag för dem som leder matcherna.</p>`},
  support:{title:'Stödmedlem',intro:'För dig som vill stötta domarna och bidra till en positiv innebandymiljö i Värmland.',body:`<h2>Du behöver inte stå på planen för att göra skillnad</h2><p>Som stödmedlem hjälper du VDK att skapa gemenskap, uppmuntra domare och arbeta för respekt i hallarna. Du kan vara förälder, ledare, tidigare domare eller helt enkelt någon som tycker att domarnas arbete är viktigt.</p><h2>Förslag och idéer är välkomna</h2><p>Du har möjlighet att komma med förslag och bidra med dina erfarenheter. Stödmedlemskapet ger ingen rösträtt. Medlemsrättigheterna regleras i VDK:s stadgar.</p><h2>Varför ditt stöd är viktigt</h2><p>Bakom varje match finns människor som behöver känna sig trygga i sitt uppdrag. Ditt stöd hjälper oss att bygga ett nätverk där domare får uppmuntran, kunskapsutbyte och kollegor att vända sig till.</p>`},
  club:{title:'Föreningsmedlem',intro:'En närmare dialog med domarkåren och omtanke om föreningens egna domare.',body:`<h2>Två domarbesök under säsongen</h2><p>För 1 500 kr får er förening två besök av en domare, <strong>en timme per besök</strong>. Vi planerar tillfällena tillsammans med er.</p><p>Här finns tid att ställa frågor, diskutera regler och få klarhet i sådant som annars lätt hamnar i skuggan av matchens puls. Samtalet sker vid ett neutralt tillfälle, fristående från en enskild matchhändelse.</p><h2>Vi tar hand om era föreningsdomare</h2><p>Vi följer upp, åker ut och stöttar era domare. Med ett positivt bemötande och uppmuntran vill vi hjälpa dem att känna sig trygga, våga utvecklas och trivas med uppdraget.</p><ul class="benefit-list"><li>Två domarbesök à en timme</li><li>Frågor, regelkunskap och dialog i lugn miljö</li><li>Uppföljning och stöd till föreningsdomarna</li><li>En kontakt med Värmlands Domarkollektiv</li></ul><h2>Varför föreningens engagemang är viktigt</h2><p>När föreningar och domare lär känna varandra ökar förståelsen för varandras uppdrag. Tillsammans kan vi skapa en hallmiljö där nya domare får en bra start och fler vill fortsätta döma.</p><p>Medlemskap och representation regleras i VDK:s stadgar.</p>`},
  business:{title:'Företagsstöd',intro:'En gåva till domarutveckling och en bättre innebandymiljö i Värmland. Ni väljer beloppet, från 1 000 kr.',body:`<h2>Stötta människorna som gör matchen möjlig</h2><p>Varje match behöver domare som känner sig trygga och vill fortsätta med sitt uppdrag. Er gåva bidrar till VDK:s arbete med gemenskap, uppföljning, stöd och utveckling för domarkåren.</p><h2>Valfri gåva från 1 000 kr</h2><p>Ni väljer själva hur mycket ni vill ge, med ett minsta belopp på 1 000 kr. Företagsstöd är en gåva och ger inte medlemskap eller rösträtt.</p><h2>Varför ert stöd är viktigt</h2><p>Ett lokalt företag kan göra konkret skillnad för den lokala idrotten. Genom att stötta domarna bidrar ni till en miljö där fler vill engagera sig, där nya domare får uppmuntran och där vi möter varandra med respekt.</p><p>Om ni vill kan vi presentera er som ett företag som stöttar VDK. Önskar ni ett särskilt sponsorsamarbete tar vi gärna en separat dialog.</p>`}
};
function applicationForm(category,s){const business=category==='business';const org=['club','business'].includes(category);const label=business?'Anmäl företagsstöd':'Ansök om '+(category==='active'?'aktivt medlemskap':category==='support'?'stödmedlemskap':'föreningsmedlemskap');return `<div class="card form-card" id="membership-application"><h2>${label}</h2>${s.applicationsOpen?`<form id="membership-form"><input type="hidden" name="category" value="${category}"><input type="hidden" name="season" value="${esc(s.season)}">${org?field(category==='club'?'Föreningens namn':'Företagets namn','organization','text','required maxlength="160"'):''}${business?field('Gåvans belopp (kronor, minst 1 000)','amount','number','required min="1000" max="10000000" step="1" value="1000"'):''}${field(org?'Kontaktperson':'Namn','name','text','required autocomplete="name" maxlength="120"')}${field('E-postadress','email','email','required autocomplete="email" maxlength="254"')}<label class="check-label"><input type="checkbox" name="consent" required><span>${business?'Jag vill lämna företagsstöd':'Jag ansöker om medlemskap'} och har läst <a href="#/integritet">hur VDK behandlar mina uppgifter</a>.</span></label>${formFooter(business?'Skicka anmälan':'Skicka medlemsansökan')}</form>`:`<p>${business?'Kontakta VDK för att lämna er gåva. Ange företagsnamn, kontaktperson och belopp.':'Kontakta VDK för att ansöka om den här medlemskategorin.'}</p><a class="button full-width" href="mailto:vdk.varmland@gmail.com?subject=${encodeURIComponent((business?'Företagsstöd':'Medlemskap')+' i VDK – '+membershipNames[category])}">${business?'Kontakta VDK om företagsstöd':'Kontakta VDK för att ansöka'}</a><p class="membership-note" style="margin-top:1rem">${business?'Anmälan':'Ansökan'} på webben öppnar när medlemstjänsten och betalningsuppgifterna är klara.</p>`}</div>`;}
async function membershipDetail(category){const info=membershipInformation[category];const s=await loadSettings();return page(info.title,info.intro,`<a class="text-link" href="#/medlemskap">Alla medlemskap och stöd</a><div class="membership-detail-layout"><article class="reading"><div class="membership-price">${category==='business'?'Från ':''}${money(membershipAmounts[category])}<span>${category==='business'?' / gåva':' / säsong'}</span></div>${info.body}${category==='business'?'':statutesLink()}</article><div class="membership-detail-aside">${applicationForm(category,s)}${sharedQr(category)}</div></div>`);}
function statutes(){return page('VDK:s stadgar.','Stadgarna beskriver föreningens ändamål, medlemskap och hur föreningens beslut fattas.',`<div class="reading"><h2>Medlemskap och inflytande</h2><p>Aktiva medlemmar som uppfyller stadgarnas krav har rösträtt. Stödmedlemmar kan komma med förslag och har ingen rösträtt. Företagsstöd är en gåva och ger inte medlemskap.</p>${config.statutesUrl?`<a class="button" href="${esc(config.statutesUrl)}" download>Ladda ner stadgarna (Word)</a>`:notice('Stadgedokumentet publiceras här när rätt version är bekräftad.')}<a class="text-link" href="#/medlemskap">Läs om medlemskap och stöd</a></div>`);}

function referees(){return page('Ditt domarskap. Din utveckling.','Mina sidor samlar verktygen som hjälper VDK-medlemmar att följa och utveckla sitt domarskap.',`<div class="content-grid"><article class="card"><h2>Mina matcher</h2><p>Dina egna matcher, samlade i en personlig vy. Matchunderlag läggs till när kopplingen till den publika innebandydatan är verifierad.</p></article><article class="card"><h2>Min statistik</h2><p>Se matchhändelser och utvisningskategorier per säsong. Filtrera på domarkollega och reflektera över nivån ni sätter tillsammans.</p></article><article class="card"><h2>Möjliga återbud</h2><p>Matcher med färre än två offentligt synliga domare kan bli en signal att kontrollera uppdraget i iBIS. En saknad domare i publik data är inte ett bekräftat återbud.</p></article><article class="card"><h2>Videocoachning</h2><p>För seniorinnebandy. Gå direkt till kommenterade situationer, läs coachens återkoppling och diskutera bedömningarna.</p></article></div><div class="reading"><h2>Verktyg för utveckling</h2><p>Matchstatistiken beskriver händelser i de matcher du har dömt. Den säger inte vilken domare som fattade ett enskilt beslut. VDK sammanställer endast medlemmarnas matchunderlag och räknar varje match en gång.</p><p>Matchprogram, resultat, tabeller och tillsättning finns fortsatt hos <a class="text-link" href="https://www.innebandy.se/" target="_blank" rel="noopener">innebandy.se</a> och i iBIS.</p><div class="inline-actions"><a class="button" href="#/mina-sidor">Till Mina sidor</a><a class="button button-outline" href="#/medlemskap">Bli medlem</a></div></div>`);}
function sponsors(){return page('Stärk domarna. Stärk innebandyn.','Som sponsor kan du bidra till gemenskap, domarutveckling och en bättre hallmiljö i Värmland.',`<div class="content-grid"><article class="card"><h2>Bli en del av VDK</h2><p>Vill din verksamhet stötta Värmlands innebandydomare? Kontakta oss så pratar vi om hur ett samarbete kan se ut.</p><a class="button" href="mailto:vdk.varmland@gmail.com?subject=Sponsorsamarbete%20med%20VDK">Prata med oss om sponsring</a></article><article class="card">${empty('Våra samarbeten','Godkända sponsorsamarbeten presenteras här när de är klara.')}</article></div>`);}
function news(){return page('Nyheter från VDK.','Föreningsnyheter, medlemsinformation och aktiviteter.',`<div class="card">${empty('Inga nyheter är publicerade ännu.','När vi har något nytt att dela hittar du det här. Under tiden kan du läsa mer om medlemskapet och vår verksamhet.')}<div style="text-align:center"><a class="button button-outline" href="#/om-vdk">Läs om VDK</a></div></div>`);}
function contact(){return page('Vi hörs.','Frågor om medlemskap, videocoachning eller samarbete? Hör av dig till VDK.',`<div class="content-grid"><article class="card"><p class="eyebrow">E-post</p><h2>Kontakta kollektivet</h2><a class="contact-address" href="mailto:vdk.varmland@gmail.com">vdk.varmland@gmail.com</a><p style="margin-top:1.5rem">Värmland, Sverige</p></article><article class="card"><h2>Vad gäller ditt ärende?</h2><p>Skriv gärna om frågan handlar om medlemskap, din domarportal, videocoachning eller sponsring. Då blir det lättare för oss att hjälpa dig.</p><a class="button" href="mailto:vdk.varmland@gmail.com">Skriv till oss</a></article></div>`);}
function privacy(){return page('Dina uppgifter hos VDK.','Medlemsuppgifter används för medlemskapet och din egen domarutveckling.',`<div class="reading"><h2>Vilka uppgifter vi behandlar</h2><p>VDK behandlar namn, e-postadress, en valfri profilbild, säsongsmedlemskap, betalningsstatus och kontobehörigheter. Om du använder domarverktygen kan även kopplingen till dina matcher, din statistik och videocoachningar behandlas.</p><h2>Vem får tillgång?</h2><p>Du ser dina egna medlemsuppgifter och matcher. Behöriga administratörer hanterar medlemsregistret. Videocoacher ser de uppdrag och situationer de har tilldelats. Videocoachning är endast tillgänglig för berörda medlemmar och behöriga coacher.</p><h2>Matchstatistik</h2><p>VDK:s sammanställningar avser medlemmarnas matchunderlag. Matchhändelser beskriver inte vilken av domarna som fattade beslutet. En match räknas en gång i den gemensamma statistiken även om två VDK-medlemmar har dömt den.</p><h2>Kontosäkerhet och kakor</h2><p>Lösenord lagras som säkra envägsvärden. En nödvändig sessionskaka används för inloggning. Webbplatsen använder ingen annons- eller analysmätning. Typsnitt hämtas från Google Fonts, vilket innebär att din webbläsare kontaktar Google vid sidvisning.</p><h2>Frågor, rättelse och radering</h2><p>Kontakta <a class="text-link" href="mailto:vdk.varmland@gmail.com">vdk.varmland@gmail.com</a> om du vill få tillgång till dina uppgifter, rätta dem eller begära radering.</p>${notice('Inför öppning av medlemstjänsten kompletterar VDK informationen med ansvarig förening, rättslig grund och beslutade lagringstider.')}</div>`);}
function login(){return `<section class="page container"><div class="login-wrap"><p class="eyebrow">För VDK-medlemmar</p><h1>Välkommen tillbaka.</h1><p class="lead">Logga in till ditt domarcentrum.</p><div class="card form-card"><form id="login-form">${field('E-postadress','email','email','required autocomplete="username"')}${field('Lösenord','password','password','required autocomplete="current-password"')}${formFooter('Logga in')}</form><div class="inline-actions"><a class="text-link" href="#/aterstall">Glömt lösenord?</a><a class="text-link" href="#/medlemskap">Bli medlem</a></div></div><p class="notice">Mina sidor är för godkända medlemmar. Du får din aktiveringslänk när VDK har bekräftat medlemskapet.</p></div></section>`;}
function passwordPage(reset=false){return `<section class="page container"><div class="login-wrap"><p class="eyebrow">Mina sidor</p><h1>${reset?'Välj ett nytt lösenord.':'Aktivera ditt medlemskonto.'}</h1><p class="lead">Välj ett eget lösenord med minst 12 tecken.</p><div class="card"><form id="password-form" data-reset="${reset}">${field('Lösenord','password','password','required minlength="12" maxlength="256" autocomplete="new-password"')}${field('Upprepa lösenordet','confirm','password','required minlength="12" maxlength="256" autocomplete="new-password"')}${formFooter(reset?'Spara lösenord':'Aktivera mitt konto')}</form></div></div></section>`;}
function resetPage(){return `<section class="page container"><div class="login-wrap"><h1>Glömt lösenord?</h1><p class="lead">Ange din e-postadress. Om den hör till ett konto skickar vi en återställningslänk.</p><div class="card"><form id="reset-form">${field('E-postadress','email','email','required autocomplete="email"')}${formFooter('Skicka återställningslänk')}</form></div></div></section>`;}
const portalTabs=[['','Översikt'],['matcher','Mina matcher'],['statistik','Min statistik'],['aterbud','Möjliga återbud'],['video','Videocoachning'],['medlemskap','Mitt medlemskap']];
function portalShell(tab,body){return `<section class="page container"><div class="portal-head"><div><p class="eyebrow">Mina sidor</p><h1>Hej ${esc(user.name.split(' ')[0])}.</h1><p>Ditt domarcentrum i Värmland.</p><a class="text-link" href="#/mina-sidor/profil">Min profilbild</a></div><div>${user.roles.includes('ADMIN')?'<a class="button button-outline button-small" href="#/admin">Administration</a> ':''}<button class="button button-quiet button-small" id="logout">Logga ut</button></div></div><nav class="tabs" aria-label="Mina sidor">${portalTabs.map(([p,t])=>`<a href="#/mina-sidor${p?'/'+p:''}" class="${p===tab?'active':''}">${t}</a>`).join('')}${user.roles.includes('VIDEO_COACH')?`<a href="#/mina-sidor/coach" class="${tab==='coach'?'active':''}">Coachverktyg</a>`:''}</nav>${body}</section>`;}
async function portal(tab){try{user=(await api('/me')).user;}catch{return login();}let body='';
  if(tab==='profil'){body=`<div class="card"><h2>Min profilbild</h2>${user.hasPhoto?`<img class="profile-photo" src="${esc(apiBase)}/api/profile/photo" alt="Din profilbild">`:'<p>Du har inte laddat upp någon profilbild ännu.</p>'}<form id="profile-photo-form"><div class="field"><label for="profile-photo">Välj bild (PNG eller JPEG, högst 2 MB)</label><input id="profile-photo" name="photo" type="file" accept="image/png,image/jpeg" required></div>${formFooter('Spara profilbild')}</form>${user.hasPhoto?'<button id="remove-photo" class="button button-quiet">Ta bort profilbild</button>':''}<p>Bilden visas bara på dina egna Mina sidor.</p></div>`;}
  else if(tab==='matcher'){const {matches}=await api('/matches');body=`<h2>Mina matcher</h2>${matches.length?matchTable(matches):`<div class="card">${empty('Inga matcher är kopplade ännu.','När verifierade matcher kopplas till ditt medlemskonto ser du dem här. Endast dina egna matcher visas.')}</div>`}`;}
  else if(tab==='statistik'){const s=await loadSettings();const params=new URLSearchParams(location.hash.split('?')[1]);const season=params.get('season')||s.season;const colleague=params.get('colleague')||'';const data=await api(`/statistics?season=${encodeURIComponent(season)}&colleague=${encodeURIComponent(colleague)}`);body=`<h2>Min statistik</h2><form id="stats-filter" class="filter-row"><div class="field"><label for="season">Säsong</label><select id="season" name="season">${[...new Set([s.season,...data.seasons])].map(x=>`<option ${x===season?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label for="colleague">Domarkollega</label><select id="colleague" name="colleague"><option value="">Alla kollegor</option>${data.colleagues.map(x=>`<option value="${esc(x)}" ${x===colleague?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>&nbsp;</label><button class="button" type="submit">Visa statistik</button></div></form>${notice('Statistiken beskriver era matchhändelser. Den visar inte vilken domare som fattade ett enskilt beslut.')}<div class="card">${statsView(data)}</div><h2 style="margin-top:2rem">Matcher i urvalet</h2>${data.matchList?.length?matchTable(data.matchList):empty('Inga matcher i urvalet.','Välj en annan säsong eller domarkollega.')}<h2 style="margin-top:2rem">Mina domarkollegor under säsongen</h2>${colleagueTable(data.colleagueSummary||[],season)}`;}
  else if(tab==='aterbud'){body=`<h2>Möjliga återbud</h2>${notice('Möjligt återbud – kontrollera i iBIS. Domarnamn kan publiceras först nära matchstart. Saknade namn är inte ett bekräftat ledigt uppdrag.')}<div class="card">${empty('Datakopplingen är inte aktiverad.','Signaler visas först när den publika datakällan och kontrollen av synliga domare har verifierats.')}<a class="text-link" href="https://www.innebandy.se/" target="_blank" rel="noopener">Till innebandy.se</a></div>`;}
  else if(tab==='video'){const {coachings}=await api('/coachings');body=`<h2>Videocoachning</h2><p class="lead">Dina kommenterade situationer från seniorinnebandyn.</p>${coachings.length?coachings.map(coachingView).join(''):`<div class="card">${empty('Du har inga publicerade videocoachningar.','När en coachning publiceras hittar du matchen och de kommenterade situationerna här.')}</div>`}`;}
  else if(tab==='medlemskap'){const {memberships,coachApplication}=await api('/membership');body=`<div class="content-grid"><div class="card"><h2>Mitt medlemskap</h2><p>${esc(user.name)}<br>${esc(user.email)}</p><div class="table-wrap"><table><thead><tr><th>Säsong</th><th>Status</th><th>Betalning</th></tr></thead><tbody>${memberships.map(x=>`<tr><td>${esc(x.season)}</td><td>${esc(statusLabel(x.status))}</td><td>${x.paid?'Bekräftad':'Ej bekräftad'}</td></tr>`).join('')}</tbody></table></div></div><div class="card"><h2>Bli videocoach</h2>${user.roles.includes('VIDEO_COACH')?'<p>Du är godkänd videocoach. Dina uppdrag finns i coachverktyget.</p>':coachApplication?`<p>Din ansökan: <span class="badge">${esc(statusLabel(coachApplication.status))}</span></p>`:`<p>Vill du bidra till domarutvecklingen i seniorinnebandyn? Beskriv din erfarenhet och varför du vill bli videocoach.</p><form id="coach-application"><div class="field"><label for="motivation">Din erfarenhet och motivation</label><textarea name="motivation" id="motivation" required maxlength="3000"></textarea></div>${formFooter('Ansök om att bli videocoach')}</form>`}</div></div>`;}
  else if(tab==='coach' && user.roles.includes('VIDEO_COACH')){const {coachings}=await api('/coach/work');body=`<h2>Mina coachuppdrag</h2>${coachings.length?coachings.map(coachEditor).join(''):`<div class="card">${empty('Inga uppdrag har tilldelats.','En administratör tilldelar dig seniormatcher med klarlagd rättighet till videomaterialet.')}</div>`}`;}
  else {const {notifications,counts}=await api('/dashboard');body=`<div class="content-grid three-grid"><a class="card" href="#/mina-sidor/matcher"><span class="number">${counts.matches}</span><h2>Mina matcher</h2><p>Matcher kopplade till ditt medlemskonto.</p></a><a class="card" href="#/mina-sidor/video"><span class="number">${counts.coachings}</span><h2>Videocoachning</h2><p>Publicerade coachningar för dig.</p></a><a class="card" href="#/mina-sidor/medlemskap"><span class="badge badge-yellow">${esc(user.season)}</span><h2 style="margin-top:1rem">Mitt medlemskap</h2><p>Dina medlemsuppgifter och säsonger.</p></a></div><h2 style="margin-top:2.5rem">Mina notiser</h2><div class="card">${notifications.length?notifications.map(n=>`<p><span class="badge">${date(n.created_at)}</span> <a class="text-link" href="#/mina-sidor/video">${esc(n.message)}</a></p>`).join(''):empty('Du är uppdaterad.','Nya videocoachningar och medlemsnotiser visas här.')}</div>`;}
  return portalShell(tab,body);
}
function statusLabel(status){return ({pending:'Väntar på godkännande',approved:'Godkänd',active:'Aktivt',rejected:'Avslagen',expired:'Avslutat',draft:'Utkast',published:'Publicerad'})[status]||status;}
function matchTable(matches){return `<div class="card table-wrap"><table><thead><tr><th>Datum</th><th>Match</th><th>Domarkollega</th><th>Säsong</th><th>Utvisningar</th><th>Källa</th></tr></thead><tbody>${matches.map(m=>`<tr><td>${date(m.starts_at)}</td><td>${esc(m.home)} – ${esc(m.away)}</td><td>${esc(m.colleague||'Ej angiven')}</td><td>${esc(m.season)}</td><td>${m.penalty_count??'–'}</td><td><a class="text-link" href="${esc(m.source_url)}" target="_blank" rel="noopener">Matchprotokoll</a></td></tr>`).join('')}</tbody></table></div>`;}
function colleagueTable(rows,season){return rows.length?`<div class="card table-wrap"><table><thead><tr><th>Domarkollega</th><th>Matcher</th><th>Utvisningar tillsammans</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.colleague?`<a class="text-link" href="#/mina-sidor/statistik?${esc(new URLSearchParams({season,colleague:r.colleague}))}">${esc(r.colleague)}</a>`:'Ej angiven'}</td><td>${r.matches}</td><td>${r.penalties}</td></tr>`).join('')}</tbody></table></div>`:empty('Inga domarkollegor registrerade.','Kollegorna visas när dina matcher har importerats.');}
function statsView(data){return data.matches?`<div class="season-summary"><div><strong>${data.matches}</strong><span>Unika matcher</span></div><div><strong>${data.penalties}</strong><span>Utvisningar</span></div><div><strong>${Number(data.penaltiesPerMatch||0).toLocaleString('sv-SE',{maximumFractionDigits:2})}</strong><span>Utvisningar per match</span></div></div><div class="table-wrap"><table><thead><tr><th>Kategori</th><th>Antal</th><th>Andel</th></tr></thead><tbody>${data.categories.map(c=>`<tr><td>${esc(c.category)}</td><td>${c.count}</td><td>${data.penalties?Math.round(100*c.count/data.penalties):0} %</td></tr>`).join('')}</tbody></table></div>`:empty('Det finns inget matchunderlag ännu.','Statistiken fylls på när verifierade matchhändelser har kopplats till medlemskapet.');}
function coachingView(c){return `<article class="card" style="margin-bottom:1.5rem"><span class="badge">${esc(c.season)}</span><h2 style="margin-top:1rem">${esc(c.home)} – ${esc(c.away)}</h2><p>Videocoach: ${esc(c.coach_name)} · ${c.clips.length} kommenterade situationer</p><ul class="clip-list">${c.clips.map(clip=>`<li><span class="badge badge-yellow">${time(clip.start_seconds)}–${time(clip.end_seconds)}</span><h3>${esc(clip.category)}</h3><p>${esc(clip.comment)}</p><a class="button button-outline button-small" href="${esc(c.video_url)}" target="_blank" rel="noopener">Öppna originalvideon</a><p style="margin-top:.6rem;font-size:.875rem">Sök till ${time(clip.start_seconds)} i originalspelaren. Automatisk tidshoppning är ännu inte verifierad.</p>${clip.audio_url?`<audio controls preload="none" src="${esc(clip.audio_url)}">Din webbläsare saknar stöd för ljuduppspelning.</audio>`:''}</li>`).join('')}</ul></article>`;}
function coachEditor(c){return `<article class="card" style="margin-bottom:1.5rem"><span class="badge">${esc(statusLabel(c.status))}</span><h2 style="margin-top:1rem">${esc(c.home)} – ${esc(c.away)}</h2><a class="text-link" href="${esc(c.video_url)}" target="_blank" rel="noopener">Öppna originalvideon</a><p>${c.clips.length} situationer · Rättighet: ${esc(c.rights_note)}</p>${c.status==='draft'?`<form class="clip-form" data-id="${c.id}"><div class="content-grid"><div class="field"><label for="start-${c.id}">Start (mm:ss)</label><input id="start-${c.id}" name="start" required placeholder="23:35" pattern="[0-9]{1,3}:[0-5][0-9]"></div><div class="field"><label for="end-${c.id}">Slut (mm:ss)</label><input id="end-${c.id}" name="end" required placeholder="23:55" pattern="[0-9]{1,3}:[0-5][0-9]"></div></div>${field('Kategori','category-'+c.id,'text','required maxlength="100"')}<div class="field"><label for="comment-${c.id}">Coachkommentar</label><textarea id="comment-${c.id}" name="comment" required maxlength="5000"></textarea></div>${field('Länk till ljudkommentar (valfritt)','audio-'+c.id,'url','placeholder="https://…"')}${formFooter('Lägg till situation')}</form><div class="inline-actions"><button class="button button-outline publish-coaching" data-id="${c.id}" ${!c.clips.length?'disabled':''}>Publicera coachningen</button></div>`:''}<ul class="clip-list">${c.clips.map(x=>`<li><strong>${time(x.start_seconds)}–${time(x.end_seconds)} · ${esc(x.category)}</strong><p>${esc(x.comment)}</p></li>`).join('')}</ul></article>`;}
async function admin(tab){try{user=(await api('/me')).user;}catch{return login();}if(!user.roles.includes('ADMIN'))return page('Åtkomst saknas.','Den här sidan är endast tillgänglig för administratörer.','');const tabs=[['','Medlemmar'],['coacher','Coachansökningar'],['uppdrag','Videouppdrag'],['statistik','VDK-statistik']];let body='';
  if(tab==='coacher'){const {applications}=await api('/admin/coach-applications');body=`<h2>Videocoachansökningar</h2>${applications.length?applications.map(a=>`<div class="card" style="margin-bottom:1rem"><h3>${esc(a.name)}</h3><p>${esc(a.motivation)}</p><span class="badge">${esc(statusLabel(a.status))}</span>${a.status==='pending'?`<div class="inline-actions"><button class="button coach-decision" data-id="${a.id}" data-status="approved">Godkänn</button><button class="button button-outline coach-decision" data-id="${a.id}" data-status="rejected">Avslå</button></div>`:''}</div>`).join(''):empty('Inga coachansökningar.','Ansökningar från medlemmar visas här.')}`;}
  else if(tab==='uppdrag'){const {matches,coaches,members}=await api('/admin/coaching-options');const {coachings}=await api('/admin/coachings');body=`<h2>Videocoachuppdrag</h2>${matches.length&&coaches.length?`<div class="card"><form id="assignment-form"><div class="field"><label for="matchId">Seniormatch</label><select id="matchId" name="matchId" required>${matches.map(m=>`<option value="${m.id}">${esc(m.home)} – ${esc(m.away)} (${date(m.starts_at)})</option>`).join('')}</select></div><div class="field"><label for="coachId">Videocoach</label><select id="coachId" name="coachId" required>${coaches.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label for="memberId">Berörd medlem</label><select id="memberId" name="memberId" required>${members.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div>${field('Originalvideo (https-länk)','videoUrl','url','required')}${field('Dokumenterad videorättighet / tillstånd','rightsNote','text','required maxlength="1000"')}<label class="check-label"><input type="checkbox" name="rightsConfirmed" required><span>Rättigheten till sluten domarutbildning är klarlagd.</span></label>${formFooter('Skapa videocoachuppdrag')}</form></div>`:notice('Uppdrag kan skapas när en verifierad seniormatch och en aktiv videocoach finns i systemet.')}<h2 style="margin-top:2rem">Tilldelade uppdrag</h2>${coachings.length?coachings.map(c=>`<p>${esc(c.home)} – ${esc(c.away)} · ${esc(c.coach_name)} · ${esc(statusLabel(c.status))}</p>`).join(''):empty('Inga uppdrag ännu.','Nya uppdrag visas här.')}`;}
  else if(tab==='statistik'){const s=await loadSettings();const {statistics}=await api('/admin/statistics?season='+encodeURIComponent(s.season));body=`<h2>VDK ${esc(s.season)}</h2>${notice('Sammanställningen avser endast VDK-medlemmarnas matchunderlag. Varje externt match-id räknas en gång.')}<div class="card"><p>${statistics.members} aktiva domarmedlemmar</p>${statsView(statistics)}</div>`;}
  else{const {applications,members}=await api('/admin/members');body=`<h2>Medlemsansökningar</h2>${applications.length?`<div class="card table-wrap"><table><thead><tr><th>Medlem</th><th>Säsong</th><th>Status</th><th>Åtgärd</th></tr></thead><tbody>${applications.map(a=>`<tr><td>${esc(a.name)}<br>${esc(a.email)}</td><td>${esc(a.season)}<br>${esc(membershipNames[a.category]||'Aktiv domare')}<br>${esc(a.organization||'')}<br>${money(a.amount||100)}</td><td>${esc(a.category==='business'&&a.status==='active'?'Gåva bekräftad':statusLabel(a.status))}<br>${a.paid?'Betalning verifierad':'Betalning ej verifierad'}</td><td>${a.status==='pending'?`<button class="button payment-confirm" data-id="${a.id}">Bekräfta Swish ${money(a.amount)}</button><button class="button button-outline member-approve" data-id="${a.id}" data-category="${a.category}" ${a.paid?'':'disabled'}>${a.category==='business'?'Bekräfta gåvan':'Godkänn och skicka aktivering'}</button>`:a.status==='approved'?`<button class="button button-outline resend-activation" data-id="${a.id}">Skicka ny aktiveringslänk</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('Inga medlemsansökningar.','Ansökningar visas här när medlemskapet öppnas.')}<h2 style="margin-top:2rem">Medlemsregister</h2><div class="card table-wrap"><table><thead><tr><th>Namn</th><th>E-post</th><th>Roller</th><th>Behörighet</th></tr></thead><tbody>${members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.email)}</td><td>${m.roles.map(esc).join(', ')}</td><td>${m.id===user.id?'Du':`<button class="button button-outline role-change" data-id="${m.id}" data-role="${m.roles.includes('VIDEO_COACH')?'MEMBER':'VIDEO_COACH'}">${m.roles.includes('VIDEO_COACH')?'Ta bort coachroll':'Ge coachroll'}</button>`}</td></tr>`).join('')}</tbody></table></div>`;}
  if(!tab){const {applications}=await api('/admin/members');const closable=applications.filter(x=>['active','approved'].includes(x.status)&&x.user_id!==user.id);if(closable.length)body+=`<div class="card" style="margin-top:1.5rem"><h2>Avsluta säsongsmedlemskap</h2><p>Åtkomsten till Mina sidor stängs och befintliga sessioner avslutas.</p><form id="close-membership"><div class="field"><label for="membershipId">Medlemskap</label><select name="membershipId" id="membershipId">${closable.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.season)}</option>`).join('')}</select></div><label class="check-label"><input type="checkbox" required><span>Jag bekräftar att medlemskapet ska avslutas.</span></label>${formFooter('Avsluta medlemskapet')}</form></div>`;}
  return `<section class="page container"><div class="portal-head"><div><p class="eyebrow">VDK administration</p><h1>Administrera kollektivet.</h1></div><a class="button button-outline button-small" href="#/mina-sidor">Till Mina sidor</a></div><nav class="tabs" aria-label="Admin">${tabs.map(([p,t])=>`<a href="#/admin${p?'/'+p:''}" class="${p===tab?'active':''}">${t}</a>`).join('')}</nav>${body}</section>`;
}
async function route(){const epoch=++pageEpoch;const hash=(location.hash.slice(1)||'/');const path=hash.split('?')[0];document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===path||(a.dataset.nav==='/medlemskap'&&path.startsWith('/medlemskap/'))));document.querySelector('#navigation').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');main.innerHTML='<div class="loading" role="status">Laddar…</div>';let html;
  try{if(path==='/')html=home();else if(path==='/om-vdk')html=about();else if(path==='/medlemskap')html=membership();else if(path.startsWith('/medlemskap/')){const category=Object.keys(membershipPaths).find(key=>membershipPaths[key]===path.split('/')[2]);html=category?await membershipDetail(category):membership();}else if(path==='/stadgar')html=statutes();else if(path==='/for-domare')html=referees();else if(path==='/sponsorer')html=sponsors();else if(path==='/nyheter')html=news();else if(path==='/kontakt')html=contact();else if(path==='/integritet')html=privacy();else if(path==='/aktivera')html=passwordPage();else if(path==='/nytt-losenord')html=passwordPage(true);else if(path==='/aterstall')html=resetPage();else if(path.startsWith('/mina-sidor'))html=await portal(path.split('/')[2]||'');else if(path.startsWith('/admin'))html=await admin(path.split('/')[2]||'');else html=page('Sidan finns inte.','Länken verkar inte leda till någon sida.','<a class="button" href="#/">Till startsidan</a>');}
  catch(e){html=page('Det gick inte att hämta sidan.','Försök igen om en stund.',notice(esc(e.message),'error')+'<a class="button" href="#/mina-sidor">Till Mina sidor</a>');}
  if(epoch!==pageEpoch)return;main.innerHTML=html;bind();window.scrollTo(0,0);main.focus({preventScroll:true});const title=main.querySelector('h1')?.textContent||'VDK';document.title=`${title} | VDK`;
}
function bind(){
  document.querySelector('#close-membership')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async data=>{await api(`/admin/applications/${data.membershipId}/close`,{method:'POST',body:{}});toast('Säsongsmedlemskapet är avslutat.');await route();});});
  document.querySelector('#membership-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async data=>{const result=await api('/applications',{method:'POST',body:{...data,consent:data.consent==='on'}});e.target.outerHTML=notice(`Din ansökan är mottagen. Swisha ${money(result.fee)} till <strong>${esc(result.swishNumber)}</strong> och ange <strong>${esc(result.paymentReference)}</strong> som meddelande. ${result.category==='business'?'VDK bekräftar gåvan när betalningen har kontrollerats.':'VDK kontrollerar betalningen innan en aktiveringslänk skickas till din e-post.'}`,'success');});});
  document.querySelector('#login-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async data=>{await api('/auth/login',{method:'POST',body:data});await route();});});
  document.querySelector('#logout')?.addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST',body:{}});user=null;location.hash='#/';}catch(e){toast(e.message);}});
  document.querySelector('#password-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async data=>{if(data.password!==data.confirm)throw new Error('Lösenorden stämmer inte överens.');const token=new URLSearchParams(location.hash.split('?')[1]).get('token');if(!token)throw new Error('Aktiveringslänken är ofullständig. Be VDK om en ny länk.');await api(e.target.dataset.reset==='true'?'/auth/reset':'/auth/activate',{method:'POST',body:{token,password:data.password}});history.replaceState(null,'','#/mina-sidor');toast('Lösenordet är sparat. Du kan nu logga in.');await route();});});
  document.querySelector('#reset-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async data=>{await api('/auth/request-reset',{method:'POST',body:data});e.target.outerHTML=notice('Om adressen hör till ett aktiverat konto har vi skickat en återställningslänk.','success');});});
  document.querySelector('#profile-photo-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async()=>{const file=e.target.querySelector('input[type=file]').files[0];if(!file||!['image/png','image/jpeg'].includes(file.type))throw new Error('Välj PNG eller JPEG.');if(file.size>2*1024*1024)throw new Error('Bilden får vara högst 2 MB.');const image=await createImageBitmap(file);if(image.width>4096||image.height>4096){image.close();throw new Error('Bilden får vara högst 4096 × 4096 pixlar.');}image.close();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(new Error('Bilden kunde inte läsas.'));reader.readAsDataURL(file);});await api('/profile/photo',{method:'POST',body:{mime:file.type,data}});toast('Profilbilden är sparad.');await route();});});
  document.querySelector('#remove-photo')?.addEventListener('click',e=>action(e.currentTarget,'/profile/photo',{remove:true},'Profilbilden är borttagen.'));
  document.querySelector('#stats-filter')?.addEventListener('submit',e=>{e.preventDefault();location.hash='#/mina-sidor/statistik?'+new URLSearchParams(new FormData(e.target));});
  document.querySelector('#coach-application')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async data=>{await api('/coach-applications',{method:'POST',body:data});toast('Din videocoachansökan är mottagen.');await route();});});
  document.querySelectorAll('.payment-confirm').forEach(b=>b.addEventListener('click',()=>action(b,`/admin/applications/${b.dataset.id}/payment`,{},'Betalningen är verifierad.')));
  document.querySelectorAll('.member-approve,.resend-activation').forEach(b=>b.addEventListener('click',()=>action(b,`/admin/applications/${b.dataset.id}/approve`,{},b.dataset.category==='business'?'Gåvan är bekräftad.':'Aktiveringslänken har skickats.')));
  document.querySelectorAll('.coach-decision').forEach(b=>b.addEventListener('click',()=>action(b,`/admin/coach-applications/${b.dataset.id}`,{status:b.dataset.status},'Ansökan är behandlad.')));
  document.querySelectorAll('.role-change').forEach(b=>b.addEventListener('click',()=>action(b,`/admin/members/${b.dataset.id}/role`,{role:b.dataset.role},'Behörigheten är uppdaterad.')));
  document.querySelector('#assignment-form')?.addEventListener('submit',e=>{e.preventDefault();submit(e.target,async data=>{await api('/admin/coachings',{method:'POST',body:{...data,matchId:Number(data.matchId),coachId:Number(data.coachId),memberId:Number(data.memberId),rightsConfirmed:data.rightsConfirmed==='on'}});toast('Coachuppdraget är skapat.');await route();});});
  document.querySelectorAll('.clip-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();submit(form,async data=>{const seconds=x=>{const [m,s]=x.split(':').map(Number);return m*60+s;};await api(`/coach/work/${form.dataset.id}/clips`,{method:'POST',body:{startSeconds:seconds(data.start),endSeconds:seconds(data.end),category:data['category-'+form.dataset.id],comment:data.comment,audioUrl:data['audio-'+form.dataset.id]}});toast('Situationen är sparad.');await route();});}));
  document.querySelectorAll('.publish-coaching').forEach(b=>b.addEventListener('click',()=>action(b,`/coach/work/${b.dataset.id}/publish`,{},'Coachningen är publicerad och medlemmen har fått en notis.')));
}
async function action(button,path,body,message){button.disabled=true;try{await api(path,{method:'POST',body});toast(message);await route();}catch(e){toast(e.message);button.disabled=false;}}
document.querySelector('.menu-toggle').addEventListener('click',e=>{const button=e.currentTarget;const open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));document.querySelector('#navigation').classList.toggle('open',!open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('#navigation').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');}});
function closeMembershipMenus(){document.querySelectorAll('[data-membership-menu]').forEach(button=>{button.setAttribute('aria-expanded','false');const menu=document.getElementById(button.getAttribute('aria-controls'));if(menu)menu.hidden=true;});}
document.addEventListener('click',event=>{const button=event.target.closest('[data-membership-menu]');if(button){const wasOpen=button.getAttribute('aria-expanded')==='true';closeMembershipMenus();const menu=document.getElementById(button.getAttribute('aria-controls'));if(menu&&!wasOpen){if(button.closest('.hero')){const rect=button.getBoundingClientRect();menu.style.position='fixed';menu.style.left=Math.max(12,Math.min(rect.left,innerWidth-310))+'px';menu.style.top=Math.min(rect.bottom+10,innerHeight-350)+'px';}button.setAttribute('aria-expanded','true');menu.hidden=false;}}else if(!event.target.closest('.membership-mini-menu'))closeMembershipMenus();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){const open=document.querySelector('[data-membership-menu][aria-expanded="true"]');closeMembershipMenus();open?.focus();}});
window.addEventListener('resize',closeMembershipMenus);
window.addEventListener('hashchange',()=>{closeMembershipMenus();route();});
route();
