import {BoardModel,emptyBoard,normalizeBoard,courtPoint,clampPoint,BOARD_LIMITS} from './board-data.js';
const clone=v=>JSON.parse(JSON.stringify(v));let sequence=0;
// IFF 2026 rules 101–102: 40x20 m; creases 4x5 m, rear line 2.85 m;
// goalkeeper areas 1x2.5 m; goal line at 3.5 m; face-offs 1.5 m from long sides.
const xy=p=>[20+p.x*400,20+p.y*200];
function layers(d,id,interactive=false){
 const arrows=d.arrows.map(a=>{const [x,y]=xy(a.from),[tx,ty]=xy(a.to);return `<path d="M${x} ${y} L${tx} ${ty}" class="board-arrow" marker-end="url(#${id})"/>`;}).join('');
 const drawings=d.drawings.map(a=>`<path d="${a.points.map((p,i)=>{const [x,y]=xy(p);return (i?'L':'M')+x+' '+y;}).join(' ')}" class="board-drawing"/>`).join('');
 const marker=(key,p,label,shape)=>{const [x,y]=xy(p);return `<g class="board-marker" data-marker="${key}" transform="translate(${x} ${y})" ${interactive?'tabindex="0" role="button"':''} aria-label="${label}"><circle r="28" fill="transparent"/>${shape}<text text-anchor="middle" dominant-baseline="central">${label}</text></g>`;};
 const refs=d.referees.map(p=>marker('ref:'+p.id,p,p.id,'<rect x="-14" y="-13" width="28" height="26" rx="4" class="board-referee"/>')).join('');
 const players=d.players.map(p=>marker('player:'+p.id,p,p.team,p.team==='A'?'<circle r="13" class="board-player-a"/>':'<path d="M0 -16 16 13 -16 13Z" class="board-player-b"/>')).join('');
 const ball=d.ball?(()=>{const[x,y]=xy(d.ball);return `<g class="board-marker board-ball" data-marker="ball" transform="translate(${x} ${y})" ${interactive?'tabindex="0" role="button"':''} aria-label="Boll"><circle r="24" fill="transparent"/><circle r="7" fill="#fff" stroke="#101719" stroke-width="2"/><circle r="1.1" fill="#101719"/><circle cx="-3" cy="-2" r="1" fill="#101719"/><circle cx="3" cy="2" r="1" fill="#101719"/></g>`;})():'';
 return drawings+arrows+players+refs+ball;
}
export function boardSVG(data=emptyBoard(),{interactive=false}={}){
 const d=normalizeBoard(data),id='board-arrow-'+(++sequence);
 return `<svg class="board-court" viewBox="0 0 440 240" ${interactive?'tabindex="0" role="group"':'role="img"'} aria-label="Domartavla på innebandyplan"><defs><marker id="${id}" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0 0 6 3 0 6Z" fill="#ffd000"/></marker></defs><rect x="20" y="20" width="400" height="200" rx="14" class="board-floor"/><g class="board-lines"><path d="M220 20V220"/><circle cx="220" cy="120" r="1.5"/>${[48.5,351.5].map(x=>`<rect x="${x}" y="95" width="40" height="50"/>`).join('')}<rect x="55" y="107.5" width="10" height="25"/><rect x="375" y="107.5" width="10" height="25"/>${[55,220,385].flatMap(x=>[35,205].map(y=>`<path d="M${x-1.5} ${y}h3m-1.5 -1.5v3"/>`)).join('')}</g><g class="board-goals"><path d="M55 112H48.5V128H55M385 112H391.5V128H385"/><path d="M55 112V128M385 112V128" class="board-goal-mouth"/></g><g class="board-items" data-arrow-id="${id}">${layers(d,id,interactive)}</g></svg>`;
}
const tools=[['move','Flytta'],['draw','Rita'],['arrow','Pil'],['referee','Domare'],['A','Lag A'],['B','Lag B'],['ball','Boll']];
export function mountBoard(root,{data=emptyBoard(),mode='edit'}={}){
 const model=new BoardModel(data),editable=mode==='edit';let tool='move',gesture=null,frame=0,dialog=null;
 root.classList.add('domartavla');root.dataset.mode=mode;if(editable)root.dataset.tool=tool;else delete root.dataset.tool;
 root.innerHTML=`<div class="board-surface">${boardSVG(model.state,{interactive:editable})}</div>${editable?`<div class="board-toolbar" role="toolbar" aria-label="Domartavlans verktyg">${tools.map(([key,label])=>`<button type="button" class="button button-outline button-small" data-tool="${key}" aria-pressed="${key===tool}">${label}${key===tool?' – aktiv':''}</button>`).join('')}</div><div class="board-controls"><button type="button" class="button button-quiet button-small" data-control="undo">Ångra</button><button type="button" class="button button-quiet button-small" data-control="redo">Gör om</button><button type="button" class="button button-quiet button-small" data-control="clear">Rensa</button><button type="button" class="button button-outline button-small" data-control="fullscreen">Helskärm</button></div><p class="board-help">Välj verktyg och tryck eller dra på planen. Välj Flytta för att dra markörer. Utanför planen scrollar sidan som vanligt.</p>`:'<button type="button" class="button button-outline button-small" data-control="fullscreen">Visa större</button>'}<p class="board-status" role="status" aria-live="polite"></p>`;
 const svg=root.querySelector('svg'),items=root.querySelector('.board-items'),arrowId=items.dataset.arrowId,status=root.querySelector('.board-status');
 if(!editable)svg.querySelectorAll('[data-marker]').forEach(el=>{el.removeAttribute('tabindex');el.removeAttribute('role');});
 const render=(state=model.state)=>{items.innerHTML=layers(state,arrowId,editable);if(!editable)items.querySelectorAll('[data-marker]').forEach(el=>{el.removeAttribute('tabindex');el.removeAttribute('role');});root.querySelector('[data-control="undo"]')?.toggleAttribute('disabled',!model.past.length);root.querySelector('[data-control="redo"]')?.toggleAttribute('disabled',!model.future.length);};
 const error=e=>status.textContent=e.message;
 const localPoint=event=>{const p=new DOMPoint(event.clientX,event.clientY).matrixTransform(svg.getScreenCTM().inverse());return courtPoint(p);};
 const queue=state=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>render(state));};
 function fullscreen(){if(dialog){dialog.close();return;}const placeholder=document.createElement('span');root.replaceWith(placeholder);dialog=document.createElement('dialog');dialog.className='board-dialog board-fullscreen';dialog.setAttribute('aria-label','VDK Domartavla i helskärm');dialog.innerHTML='<button type="button" class="button button-quiet board-close">Stäng helskärm</button>';dialog.querySelector('button').onclick=()=>dialog.close();dialog.append(root);document.body.append(dialog);dialog.addEventListener('close',()=>{placeholder.replaceWith(root);dialog.remove();dialog=null;},{once:true});dialog.showModal();}
 root.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;root.dataset.tool=tool;root.querySelectorAll('[data-tool]').forEach(x=>{const active=x===b;x.setAttribute('aria-pressed',String(active));x.textContent=tools.find(t=>t[0]===x.dataset.tool)[1]+(active?' – aktiv':'');});status.textContent='';});
 root.querySelectorAll('[data-control]').forEach(b=>b.onclick=()=>{const action=b.dataset.control;if(action==='fullscreen'){fullscreen();return;}try{if(action==='clear'&&JSON.stringify(model.state)!==JSON.stringify(emptyBoard())&&!confirm('Rensa hela tavlan?'))return;if(action==='clear')model.clear();else model[action]();render();status.textContent=action==='clear'?'Tavlan är rensad.':'';}catch(e){error(e);}});
 if(editable){
 svg.addEventListener('pointerdown',event=>{if(event.button!==0||gesture)return;event.preventDefault();const p=localPoint(event),marker=event.target.closest('[data-marker]');svg.setPointerCapture(event.pointerId);gesture={pointer:event.pointerId,start:p,end:p,points:[p],marker:tool==='move'?marker?.dataset.marker:null,state:clone(model.state)};});
 svg.addEventListener('pointermove',event=>{if(!gesture||gesture.pointer!==event.pointerId)return;event.preventDefault();const p=localPoint(event);gesture.end=p;const s=clone(gesture.state);
  if(gesture.marker){const target=gesture.marker==='ball'?s.ball:gesture.marker.startsWith('ref:')?s.referees.find(x=>x.id===gesture.marker.slice(4)):s.players.find(x=>x.id===gesture.marker.slice(7));Object.assign(target,p);}
  else if(tool==='arrow')s.arrows.push({from:gesture.start,to:p});
  else if(tool==='draw'){const last=gesture.points.at(-1);if(gesture.points.length<BOARD_LIMITS.pointsPerDrawing&&Math.hypot((p.x-last.x)*400,(p.y-last.y)*200)>1.5)gesture.points.push(p);if(gesture.points.length>1)s.drawings.push({points:gesture.points});}
  queue(s);
 });
 const finish=event=>{if(!gesture||gesture.pointer!==event.pointerId)return;event.preventDefault();const g=gesture;gesture=null;cancelAnimationFrame(frame);try{if(g.marker)model.moveMarker(g.marker,g.end);else if(tool==='arrow'&&Math.hypot(g.end.x-g.start.x,g.end.y-g.start.y)>.01)model.addArrow(g.start,g.end);else if(tool==='draw'&&g.points.length>1)model.addDrawing(g.points);else if(!['draw','arrow','move'].includes(tool))model.addMarker(tool,g.start);status.textContent='';}catch(e){error(e);}render();};
 svg.addEventListener('pointerup',finish);svg.addEventListener('pointercancel',()=>{gesture=null;cancelAnimationFrame(frame);render();});
 svg.addEventListener('keydown',event=>{const marker=event.target.closest('[data-marker]');if(!marker||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const key=marker.dataset.marker,p=key==='ball'?model.state.ball:key.startsWith('ref:')?model.state.referees.find(x=>x.id===key.slice(4)):model.state.players.find(x=>x.id===key.slice(7));model.moveMarker(key,clampPoint({x:p.x+(event.key==='ArrowRight'?.01:event.key==='ArrowLeft'?-.01:0),y:p.y+(event.key==='ArrowDown'?.01:event.key==='ArrowUp'?-.01:0)}));render();items.querySelector(`[data-marker="${key}"]`)?.focus();});
 }
 render();return {model,getData:()=>normalizeBoard(model.state),destroy:()=>{cancelAnimationFrame(frame);dialog?.close();root.replaceChildren();}};
}
export function openBoard({data=emptyBoard(),mode='edit',onSave}={}){
 const dialog=document.createElement('dialog');dialog.className='board-dialog';dialog.setAttribute('aria-label','VDK Domartavla');dialog.innerHTML='<div class="board-dialog-head"><h2>VDK Domartavla</h2><button type="button" class="button button-quiet board-close">Stäng</button></div><div class="board-mount"></div><div class="board-dialog-actions"></div><p class="board-save-status" role="status"></p>';document.body.append(dialog);const board=mountBoard(dialog.querySelector('.board-mount'),{data,mode});dialog.querySelector('.board-close').onclick=()=>dialog.close();if(mode==='edit'&&onSave){const save=document.createElement('button');save.type='button';save.className='button';save.textContent='Spara i situationen';save.onclick=async()=>{save.disabled=true;try{await onSave(board.getData());dialog.close();}catch(e){dialog.querySelector('.board-save-status').textContent=e.message;save.disabled=false;}};dialog.querySelector('.board-dialog-actions').append(save);}dialog.addEventListener('close',()=>{board.destroy();dialog.remove();},{once:true});dialog.showModal();return board;
}

export function closeBoards(){document.querySelectorAll('dialog.board-dialog[open]').forEach(d=>d.close());}
