import {isVenueInScope} from '../server/stat-geography.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cloudStore} from './cloud-fixture.mjs';
import {cacheMatch} from '../cloudflare/cache-store.mjs';
import {planSync,runSyncBatch,isSwedishMondayThree} from '../cloudflare/sync.mjs';
import {statistics} from '../cloudflare/store.mjs';
const league={CompetitionID:1,CompetitionTypeID:1,Name:'Herrar Division 3'};
const match={VenueID:1587,SeasonID:43,CompetitionID:1,MatchID:1,MatchDateTime:'2025-10-01T18:00:00',HomeTeam:'Arvika IBF U',HomeTeamID:10,AwayTeam:'Gäster',AwayTeamID:20,HomeMatchTeamID:100,AwayMatchTeamID:200,Referee1ID:8888,Referee1:'Sören Johansson',Referee2ID:99,Referee2:'Kollega',HasFinalResult:true,GoalsHomeTeam:1,GoalsAwayTeam:0,Events:[{MatchEventID:1,MatchEventTypeID:2,PenaltyCode:'219',PenaltyName:'Protest mot domslut, 2 min',MatchTeamID:100},{MatchEventID:2,MatchEventTypeID:2,PenaltyCode:'201',PenaltyName:'Slag, 2 min',MatchTeamID:200}]};
function pilot(db){const id=Number(db.prepare('INSERT INTO users(name,email) VALUES (?,?)').run('Sören Johansson','pilot@example.test').lastInsertRowid);db.prepare("INSERT INTO roles VALUES (?,'ADMIN')").run(id);return id;}
function owner(db,rows=[match],fail=false){const calls=[],alarms=[];const source={async get(p){calls.push(p);if(fail)throw Error('Source unavailable');if(p==='/venues/1587')return {City:'Karlstad',WGS84Longitude:13.483,WGS84Latitude:59.385};if(p.includes('/federations/11/'))return p.includes('/43/')?[league,{...league,CompetitionID:2,Name:'Herrar Division 3 (SIBF)'},{...league,CompetitionID:3,Name:'Herrar Division 3 Träningsmatcher'}]:[];if(p==='/competitions/1')return league;if(p==='/competitions/3')return {...league,Name:'Herrar Division 3 Träningsmatcher'};if(p==='/competitions/1/matches')return rows.map(m=>({...m,Events:undefined}));if(p.startsWith('/matches/'))return rows.find(m=>m.MatchID===Number(p.split('/').at(-1)));throw Error(p);}};return {db,sourceFactory:()=>source,ctx:{storage:{async setAlarm(t){alarms.push(t);}}},calls,alarms};}

test('Cloudflare cache is deduplicated, preserves zero-event matches and filters pair/team/event',()=>{const db=cloudStore();try{const id=pilot(db);cacheMatch(db,match,league);cacheMatch(db,match,league);cacheMatch(db,{...match,MatchID:2,Events:[],GoalsHomeTeam:0,GoalsAwayTeam:0},league);const all=statistics(db,{season:'2025/26',regional:true});assert.equal(all.matches,2);assert.equal(all.penalties,2);assert.match(all.matchList.find(m=>m.id===1).colleague,/Sören Johansson/);assert.match(all.matchList.find(m=>m.id===1).colleague,/Kollega/);assert.equal(statistics(db,{season:'2025/26',regional:true,code:'219',referee:'8888',coReferee:'99'}).penaltiesPerMatch,0.5);assert.equal(statistics(db,{season:'2025/26',regional:true,team:'20',against:true}).penalties,1);assert.equal(statistics(db,{season:'2025/26',userId:id}).matches,2);assert.throws(()=>cacheMatch(db,{...match,Events:null},league),/saknas/);assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,2);assert.throws(()=>cacheMatch(db,match,{...league,Name:'Herrar Division 3 (SIBF)'}),/avgränsning/);cacheMatch(db,{...match,Referee1ID:123,Referee1:'Annan domare'},league);assert.equal(statistics(db,{season:'2025/26',userId:id}).matches,1);}finally{db.close();}});

test('Cloudflare job queue handles 100 shared referee profiles in one regional scan and batches resumes',async()=>{const db=cloudStore();try{pilot(db);for(let i=0;i<99;i++){const id=Number(db.prepare('INSERT INTO users(name,email) VALUES (?,?)').run('Domare '+i,i+'@example.test').lastInsertRowid);db.prepare("INSERT INTO memberships(user_id,season,status,paid,category,payment_reference,consented_at) VALUES (?,'2026/27','active',1,'active',?,'2026-10-04')").run(id,'test-'+id);}const rows=Array.from({length:20},(_,i)=>({...match,MatchID:i+1,Events:match.Events.map(e=>({...e,MatchEventID:e.MatchEventID+i*2}))})),o=owner(db,rows);const first=planSync(o,'test-window');const overlap=await planSync(o,'other-window');assert.equal(overlap.started,false);assert.equal((await first).jobs,20);assert.equal((await planSync(o,'test-window')).started,false);await runSyncBatch(o);assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,15);await runSyncBatch(o);assert.equal(db.prepare('SELECT 1 FROM regional_sync_plan').get(),undefined);assert.equal(o.calls.filter(p=>p.startsWith('/matches/')).length,20);assert.ok(o.calls.every(p=>!p.includes('/federations/1/')));assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,40);assert.equal((await planSync(o,'test-window')).started,false);const next=await planSync(o,'next-window');assert.equal(next.jobs,0);await runSyncBatch(o);assert.equal(db.prepare('SELECT status FROM sync_runs ORDER BY id DESC LIMIT 1').get().status,'complete');}finally{db.close();}});

test('Cloudflare source failure resumes planning; missing protocols do not erase prior verified data',async()=>{const db=cloudStore();try{pilot(db);cacheMatch(db,match,league);const failed=owner(db,[match],true);assert.equal((await planSync(failed,'retry')).retrying,true);assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,-1);const recovered=owner(db,[{...match,MatchDateTime:new Date().toISOString(),Events:null}]);await runSyncBatch(recovered);await runSyncBatch(recovered);assert.equal(db.prepare('SELECT status FROM sync_runs').get().status,'partial');assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,2);}finally{db.close();}});

test('Cloudflare Monday 03 trigger follows Swedish daylight saving time',()=>{assert.equal(isSwedishMondayThree(Date.parse('2026-10-05T01:00:00Z')),'2026-10-05');assert.equal(isSwedishMondayThree(Date.parse('2026-11-02T02:00:00Z')),'2026-11-02');assert.equal(isSwedishMondayThree(Date.parse('2026-10-05T02:00:00Z')),null);assert.equal(isSwedishMondayThree(Date.parse('2026-11-02T01:00:00Z')),null);assert.equal(isSwedishMondayThree(Date.parse('2026-10-04T01:00:00Z')),null);});

test('junior statistics include shared HJ17 DJ17 and JAS18 while excluding other federal and training matches',()=>{const db=cloudStore();try{pilot(db);const names=['Herrjunior 17 Region','Damjunior 17 Region Västra','Juniorallsvenskan E HJ18 (SIBF)','Juniorallsvenskan D DJ18 (SIBF)'];for(const [i,Name] of names.entries()){const m={...match,MatchID:100+i,Events:match.Events.map(e=>({...e,MatchEventID:e.MatchEventID+1000+i*2}))};cacheMatch(db,m,{...league,Name,CompetitionID:100+i});cacheMatch(db,m,{...league,Name,CompetitionID:100+i});assert.equal(db.prepare('SELECT level FROM matches WHERE id=?').get(100+i).level,'youth');}assert.equal(statistics(db,{season:'2025/26',regional:true}).matches,4);assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,8);assert.equal(statistics(db,{season:'2025/26',regional:true,competition:'Herrjunior 17 Region'}).matches,1);assert.throws(()=>cacheMatch(db,match,{...league,Name:'Herrar Division 2 (SIBF)'}),/avgränsning/);assert.throws(()=>cacheMatch(db,match,{...league,Name:'Träningsmatcher HJ18',CompetitionTypeID:2}),/avgränsning/);}finally{db.close();}});

test('planning many series persists and resumes within per-invocation source limits',async()=>{const db=cloudStore();try{pilot(db);const o=owner(db,[]);const cs=Array.from({length:20},(_,i)=>({...league,CompetitionID:700+i}));const calls=[];o.sourceFactory=()=>({async get(path){calls.push(path);if(path.includes('/seasons/43/'))return cs;if(path.includes('/seasons/44/'))return [];if(path.endsWith('/matches'))return [];return cs.find(c=>path==='/competitions/'+c.CompetitionID);}});await planSync(o,'many-series');assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,-1);assert.equal(JSON.parse(db.prepare('SELECT jobs FROM regional_sync_plan').get().jobs).cursor,6);for(let i=0;i<3;i++){const before=calls.length;await runSyncBatch(o);assert.ok(calls.length-before<=12);}assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,0);await runSyncBatch(o);assert.equal(db.prepare('SELECT 1 FROM regional_sync_plan').get(),undefined);}finally{db.close();}});

test('shared series listings use each matches own competition instead of requested parent',async()=>{const db=cloudStore();try{pilot(db);const own={...league,Name:'Herrjunior 17 Region B',CompetitionID:88};const m={...match,CompetitionID:88,CompetitionName:own.Name};const o=owner(db,[]);o.sourceFactory=()=>({async get(path){if(path.includes('/seasons/43/'))return [{...league,Name:'Herrjunior 17 Region A',CompetitionID:77},own];if(path.includes('/seasons/44/'))return [];if(path.endsWith('/matches'))return [m];if(path==='/matches/1')return m;if(path==='/venues/1587')return {City:'Karlstad',WGS84Longitude:13.483,WGS84Latitude:59.385};return path.endsWith('/88')?own:{...league,Name:'Herrjunior 17 Region A',CompetitionID:77};}});assert.equal((await planSync(o,'shared-series')).jobs,1);await runSyncBatch(o);assert.equal(db.prepare('SELECT competition_name FROM matches WHERE id=1').get().competition_name,own.Name);}finally{db.close();}});

test('geographic scope accepts Värmland and four named extensions but not away venues elsewhere',()=>{assert.equal(isVenueInScope({City:'Karlstad',WGS84Longitude:13.483,WGS84Latitude:59.385}),true);for(const City of ['Karlskoga','Degerfors','Billingsfors','Åmål'])assert.equal(isVenueInScope({City}),true);assert.equal(isVenueInScope({City:'Örebro',WGS84Longitude:15.21,WGS84Latitude:59.27}),false);assert.equal(isVenueInScope({City:'Västerås',WGS84Longitude:16.54,WGS84Latitude:59.61}),false);assert.throws(()=>isVenueInScope({City:'Okänd hall'}),/kan inte verifieras/);});
test('geographic backfill excludes an old outside match and advances even if entire batch is outside',async()=>{const db=cloudStore();try{pilot(db);cacheMatch(db,match,league);const o=owner(db);const original=o.sourceFactory();o.sourceFactory=()=>({get:path=>path==='/venues/1587'?Promise.resolve({City:'Örebro',WGS84Longitude:15.21,WGS84Latitude:59.27}):original.get(path)});assert.equal((await planSync(o,'geography-backfill')).jobs,1);await runSyncBatch(o);assert.equal(db.prepare('SELECT excluded FROM matches WHERE id=1').get().excluded,1);assert.equal(db.prepare('SELECT 1 FROM regional_sync_plan').get(),undefined);assert.equal(statistics(db,{season:'2025/26',regional:true}).matches,0);assert.equal((await planSync(o,'next-geography')).jobs,0);}finally{db.close();}});
