import {isRegionalSenior} from '../cloudflare/sync.mjs';
import {isVenueInScope} from '../server/stat-geography.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cloudStore} from './cloud-fixture.mjs';
import {cacheMatch} from '../cloudflare/cache-store.mjs';
import {planSync,runSyncBatch,isSwedishMondayThree} from '../cloudflare/sync.mjs';
import {statistics} from '../cloudflare/store.mjs';
const league={CompetitionID:1,CompetitionTypeID:1,Name:'Herrar Division 3'};
const match={VenueID:1587,SeasonID:43,CompetitionID:1,MatchID:1,MatchDateTime:'2025-10-01T18:00:00',HomeTeam:'Arvika IBF U',HomeTeamID:10,AwayTeam:'Gäster',AwayTeamID:20,HomeMatchTeamID:100,AwayMatchTeamID:200,Referee1ID:8888,Referee1:'Sören Johansson',Referee2ID:99,Referee2:'Kollega',HasFinalResult:true,GoalsHomeTeam:1,GoalsAwayTeam:0,Events:[{MatchEventID:1,MatchEventTypeID:2,PenaltyCode:'219',PenaltyName:'Protest mot domslut, 2 min',MatchTeamID:100},{MatchEventID:2,MatchEventTypeID:2,PenaltyCode:'201',PenaltyName:'Slag, 2 min',MatchTeamID:200}]};
function pilot(db){const id=Number(db.prepare('INSERT INTO users(name,email) VALUES (?,?)').run('Sören Johansson','pilot@example.test').lastInsertRowid);db.prepare("INSERT INTO roles VALUES (?,'ADMIN')").run(id);return id;}
function owner(db,rows=[match],fail=false){const calls=[],alarms=[];const source={async get(p){calls.push(p);if(p.includes('/federations/1/'))return [];if(fail)throw Error('Source unavailable');if(p==='/venues/1587')return {City:'Karlstad',WGS84Longitude:13.483,WGS84Latitude:59.385};if(p.includes('/federations/11/'))return p.includes('/43/')?[league,{...league,CompetitionID:2,Name:'Herrar Division 3 (SIBF)'},{...league,CompetitionID:3,Name:'Herrar Division 3 Träningsmatcher'}]:[];if(p==='/competitions/1')return league;if(p==='/competitions/3')return {...league,Name:'Herrar Division 3 Träningsmatcher'};if(p==='/competitions/1/matches')return rows.map(m=>({...m,Events:undefined}));if(p.startsWith('/matches/'))return rows.find(m=>m.MatchID===Number(p.split('/').at(-1)));throw Error(p);}};return {db,sourceFactory:()=>source,ctx:{storage:{async setAlarm(t){alarms.push(t);}}},calls,alarms};}

test('Cloudflare cache is deduplicated, preserves zero-event matches and filters pair/team/event',()=>{const db=cloudStore();try{const id=pilot(db);cacheMatch(db,match,league);cacheMatch(db,match,league);cacheMatch(db,{...match,MatchID:2,Events:[],GoalsHomeTeam:0,GoalsAwayTeam:0},league);const all=statistics(db,{season:'2025/26',regional:true});assert.equal(all.matches,2);assert.equal(all.penalties,2);assert.match(all.matchList.find(m=>m.id===1).colleague,/Sören Johansson/);assert.match(all.matchList.find(m=>m.id===1).colleague,/Kollega/);assert.equal(statistics(db,{season:'2025/26',regional:true,code:'219',referee:'8888',coReferee:'99'}).penaltiesPerMatch,0.5);assert.equal(statistics(db,{season:'2025/26',regional:true,team:'20',against:true}).penalties,1);assert.equal(statistics(db,{season:'2025/26',userId:id}).matches,2);assert.throws(()=>cacheMatch(db,{...match,Events:null},league),/saknas/);assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,2);assert.throws(()=>cacheMatch(db,match,{...league,Name:'Herrar Division 3 (SIBF)'}),/avgränsning/);cacheMatch(db,{...match,Referee1ID:123,Referee1:'Annan domare'},league);assert.equal(statistics(db,{season:'2025/26',userId:id}).matches,1);}finally{db.close();}});

test('Cloudflare job queue handles 100 shared referee profiles in one regional scan and batches resumes',async()=>{const db=cloudStore();try{pilot(db);for(let i=0;i<99;i++){const id=Number(db.prepare('INSERT INTO users(name,email) VALUES (?,?)').run('Domare '+i,i+'@example.test').lastInsertRowid);db.prepare("INSERT INTO memberships(user_id,season,status,paid,category,payment_reference,consented_at) VALUES (?,'2026/27','active',1,'active',?,'2026-10-04')").run(id,'test-'+id);}const rows=Array.from({length:20},(_,i)=>({...match,MatchID:i+1,Events:match.Events.map(e=>({...e,MatchEventID:e.MatchEventID+i*2}))})),o=owner(db,rows);const first=planSync(o,'test-window');const overlap=await planSync(o,'other-window');assert.equal(overlap.started,false);assert.equal((await first).jobs,20);assert.equal((await planSync(o,'test-window')).started,false);await runSyncBatch(o);assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,15);await runSyncBatch(o);assert.equal(db.prepare('SELECT 1 FROM regional_sync_plan').get(),undefined);assert.equal(o.calls.filter(p=>p.startsWith('/matches/')).length,20);assert.equal(o.calls.filter(p=>p.includes('/federations/1/')).length,5);assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,40);assert.equal((await planSync(o,'test-window')).started,false);const next=await planSync(o,'next-window');assert.equal(next.jobs,0);await runSyncBatch(o);assert.equal(db.prepare('SELECT status FROM sync_runs ORDER BY id DESC LIMIT 1').get().status,'complete');}finally{db.close();}});

test('Cloudflare source failure resumes planning; missing protocols do not erase prior verified data',async()=>{const db=cloudStore();try{pilot(db);cacheMatch(db,match,league);const failed=owner(db,[match],true);assert.equal((await planSync(failed,'retry')).retrying,true);assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,-1);const recovered=owner(db,[{...match,MatchDateTime:new Date().toISOString(),Events:null}]);await runSyncBatch(recovered);await runSyncBatch(recovered);assert.equal(db.prepare('SELECT status FROM sync_runs').get().status,'partial');assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,2);}finally{db.close();}});

test('Cloudflare Monday 03 trigger follows Swedish daylight saving time',()=>{assert.equal(isSwedishMondayThree(Date.parse('2026-10-05T01:00:00Z')),'2026-10-05');assert.equal(isSwedishMondayThree(Date.parse('2026-11-02T02:00:00Z')),'2026-11-02');assert.equal(isSwedishMondayThree(Date.parse('2026-10-05T02:00:00Z')),null);assert.equal(isSwedishMondayThree(Date.parse('2026-11-02T01:00:00Z')),null);assert.equal(isSwedishMondayThree(Date.parse('2026-10-04T01:00:00Z')),null);});

test('junior statistics include shared HJ17 DJ17 and JAS18 while excluding other federal and training matches',()=>{const db=cloudStore();try{pilot(db);const names=['Herrjunior 17 Region','Damjunior 17 Region Västra','Juniorallsvenskan E HJ18 (SIBF)','Juniorallsvenskan D DJ18 (SIBF)'];for(const [i,Name] of names.entries()){const m={...match,MatchID:100+i,Events:match.Events.map(e=>({...e,MatchEventID:e.MatchEventID+1000+i*2}))};cacheMatch(db,m,{...league,Name,CompetitionID:100+i});cacheMatch(db,m,{...league,Name,CompetitionID:100+i});assert.equal(db.prepare('SELECT level FROM matches WHERE id=?').get(100+i).level,'youth');}assert.equal(statistics(db,{season:'2025/26',regional:true}).matches,4);assert.equal(statistics(db,{season:'2025/26',regional:true}).penalties,8);assert.equal(statistics(db,{season:'2025/26',regional:true,competition:'Herrjunior 17 Region'}).matches,1);assert.throws(()=>cacheMatch(db,match,{...league,Name:'Herrar Division 2 (SIBF)'}),/avgränsning/);assert.throws(()=>cacheMatch(db,match,{...league,Name:'Träningsmatcher HJ18',CompetitionTypeID:2}),/avgränsning/);}finally{db.close();}});

test('planning many series persists and resumes within per-invocation source limits',async()=>{const db=cloudStore();try{pilot(db);const o=owner(db,[]);const cs=Array.from({length:20},(_,i)=>({...league,CompetitionID:700+i}));const calls=[];o.sourceFactory=()=>({async get(path){calls.push(path);if(path.includes('/seasons/43/'))return cs;if(path.includes('/seasons/'))return [];if(path.endsWith('/matches'))return [];return cs.find(c=>path==='/competitions/'+c.CompetitionID);}});await planSync(o,'many-series');assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,-1);assert.equal(JSON.parse(db.prepare('SELECT jobs FROM regional_sync_plan').get().jobs).cursor,6);for(let i=0;i<3;i++){const before=calls.length;await runSyncBatch(o);assert.ok(calls.length-before<=12);}assert.equal(db.prepare('SELECT position FROM regional_sync_plan').get().position,0);await runSyncBatch(o);assert.equal(db.prepare('SELECT 1 FROM regional_sync_plan').get(),undefined);}finally{db.close();}});

test('shared series listings use each matches own competition instead of requested parent',async()=>{const db=cloudStore();try{pilot(db);const own={...league,Name:'Herrjunior 17 Region B',CompetitionID:88};const m={...match,CompetitionID:88,CompetitionName:own.Name};const o=owner(db,[]);o.sourceFactory=()=>({async get(path){if(path.includes('/seasons/43/'))return [{...league,Name:'Herrjunior 17 Region A',CompetitionID:77},own];if(path.includes('/seasons/'))return [];if(path.endsWith('/matches'))return [m];if(path==='/matches/1')return m;if(path==='/venues/1587')return {City:'Karlstad',WGS84Longitude:13.483,WGS84Latitude:59.385};return path.endsWith('/88')?own:{...league,Name:'Herrjunior 17 Region A',CompetitionID:77};}});assert.equal((await planSync(o,'shared-series')).jobs,1);await runSyncBatch(o);assert.equal(db.prepare('SELECT competition_name FROM matches WHERE id=1').get().competition_name,own.Name);}finally{db.close();}});

test('geographic scope accepts Värmland and four named extensions but not away venues elsewhere',()=>{assert.equal(isVenueInScope({City:'Karlstad',WGS84Longitude:13.483,WGS84Latitude:59.385}),true);for(const City of ['Karlskoga','Degerfors','Billingsfors','Åmål'])assert.equal(isVenueInScope({City}),true);assert.equal(isVenueInScope({City:'Örebro',WGS84Longitude:15.21,WGS84Latitude:59.27}),false);assert.equal(isVenueInScope({City:'Västerås',WGS84Longitude:16.54,WGS84Latitude:59.61}),false);assert.equal(isVenueInScope({City:'Skoghall'}),true);assert.equal(isVenueInScope({City:'Kumla'}),false);assert.throws(()=>isVenueInScope({City:'Okänd hall'}),/kan inte verifieras/);});
test('geographic backfill excludes an old outside match and advances even if entire batch is outside',async()=>{const db=cloudStore();try{pilot(db);cacheMatch(db,match,league);const o=owner(db);const original=o.sourceFactory();o.sourceFactory=()=>({get:path=>path==='/venues/1587'?Promise.resolve({City:'Örebro',WGS84Longitude:15.21,WGS84Latitude:59.27}):original.get(path)});assert.equal((await planSync(o,'geography-backfill')).jobs,1);await runSyncBatch(o);assert.equal(db.prepare('SELECT excluded FROM matches WHERE id=1').get().excluded,1);assert.equal(db.prepare('SELECT 1 FROM regional_sync_plan').get(),undefined);assert.equal(statistics(db,{season:'2025/26',regional:true}).matches,0);assert.equal((await planSync(o,'next-geography')).jobs,0);}finally{db.close();}});


test('historical season imports retain their own year and link to personal and regional statistics',()=>{const db=cloudStore();try{const userId=pilot(db);for(const [SeasonID,season] of [[40,'2022/23'],[41,'2023/24'],[42,'2024/25']]){cacheMatch(db,{...match,SeasonID,MatchID:SeasonID,Events:match.Events.map(e=>({...e,MatchEventID:e.MatchEventID+SeasonID*10}))},league);assert.equal(statistics(db,{season,regional:true}).matches,1);assert.equal(statistics(db,{season,userId}).penalties,2);}assert.equal(statistics(db,{season:'all',userId}).matches,3);assert.throws(()=>cacheMatch(db,{...match,SeasonID:39},league),/avgränsning/);}finally{db.close();}});

test('historical Pantamera junior 17 competitions retain youth classification',()=>{const db=cloudStore();try{pilot(db);cacheMatch(db,{...match,SeasonID:40},{...league,Name:'Pantamera Herrjunior 17 Region'});assert.equal(db.prepare('SELECT level FROM matches WHERE id=1').get().level,'youth');}finally{db.close();}});


test('season comparisons combine colleague, penalty type and team without dropping zero-event matches',()=>{const db=cloudStore();try{const userId=pilot(db);cacheMatch(db,{...match,SeasonID:42,MatchID:40},league);cacheMatch(db,{...match,SeasonID:43,MatchID:41,Events:[],GoalsHomeTeam:0,GoalsAwayTeam:0},league);cacheMatch(db,{...match,SeasonID:43,MatchID:42,Referee2:'Other colleague',Referee2ID:100},league);cacheMatch(db,{...match,SeasonID:43,MatchID:43,Referee1:'Other referee',Referee1ID:200},league);const d=statistics(db,{season:'all',userId,colleague:'Kollega',code:'219',team:'10',against:true});assert.equal(d.matches,2);assert.equal(d.penalties,1);assert.deepEqual(d.seasonSummary.map(r=>[r.season,r.matches,r.penalties,r.penaltiesPerMatch]),[['2024/25',1,1,1],['2025/26',1,0,0]]);assert.equal(d.seasonColleagues.length,2);assert.ok(d.seasonColleagues.every(r=>r.colleague==='Kollega'));assert.equal(d.penaltiesPerMatch,0.5);assert.equal(statistics(db,{season:'all',userId,colleague:'Kollega',code:'219',team:'20',against:true}).penalties,0);}finally{db.close();}});

test('all red boys and girls series, including seasonal divisions, are cached as youth',()=>{const db=cloudStore();try{pilot(db);for(const Name of ['Pantamera Pojkar Röd Serie 7 Östra','Pantamera Flickor Röd Serie 5 Västra','Pantamera Pojkar Röd Serie 5 Vår B','Pantamera Flick Mörkröd B Höst (Västsvenska)']){assert.equal(isRegionalSenior({Name}),true);cacheMatch(db,match,{...league,Name});assert.equal(db.prepare('SELECT level FROM matches WHERE id=1').get().level,'youth');}for(const Name of ['Pantamera Pojkar Blå Serie 1','Pantamera Flickor Grön Serie 1'])assert.equal(isRegionalSenior({Name}),false);}finally{db.close();}});

test('federal member matches outside Värmland stay personal while shared JAS matches are deduplicated regionally',()=>{const db=cloudStore();try{const userId=pilot(db);cacheMatch(db,match,league);cacheMatch(db,{...match,MatchID:2,HomeTeam:'Stockholm',VenueID:1318},{CompetitionID:90,CompetitionTypeID:1,Name:'Division 1 Herrar Södra Svealand'},{federal:true,regionalEligible:false});cacheMatch(db,{...match,MatchID:3},{CompetitionID:91,CompetitionTypeID:1,Name:'Juniorallsvenskan HJ18'},{federal:true,regionalEligible:true});assert.equal(statistics(db,{season:'2025/26',userId}).matches,3);assert.equal(statistics(db,{season:'2025/26',userId,scope:'federal'}).matches,2);assert.equal(statistics(db,{season:'2025/26',userId,scope:'district'}).matches,1);assert.equal(statistics(db,{season:'2025/26',regional:true}).matches,2);assert.equal(statistics(db,{season:'2025/26',userId,scope:'federal',colleague:'Kollega',code:'219'}).penalties,2);assert.equal(statistics(db,{season:'all',userId,scope:'federal'}).seasonSummary[0].matches,2);assert.ok(statistics(db,{season:'all',userId,scope:'district'}).competitions.every(n=>!n.includes('Division 1')));assert.throws(()=>cacheMatch(db,{...match,Referee1:'Other',Referee2:'Other 2'},{...league,Name:'SSL Herr'},{federal:true,regionalEligible:false}),/aktiv VDK/);}finally{db.close();}});

test('federal scan saves an index for other referees, only caches member matches and retries when a new member joins',async()=>{const db=cloudStore();try{const userId=pilot(db),federal={CompetitionID:90,CompetitionTypeID:1,Name:'Division 1 Herrar Södra Svealand'};const own={...match,MatchID:90,CompetitionID:90,VenueID:1318},other={...own,MatchID:91,Referee1:'New referee',Referee1ID:4444,Referee2:'Other referee',Referee2ID:5555};const calls=[],o={db,ctx:{storage:{async setAlarm(){}}},sourceFactory:()=>({async get(path){calls.push(path);if(path.includes('/seasons/43/federations/1/'))return [federal];if(path.includes('/seasons/'))return [];if(path==='/competitions/90')return federal;if(path==='/competitions/90/matches')return [own,other];if(path==='/matches/90')return own;if(path==='/matches/91')return other;throw Error(path);}})};assert.equal((await planSync(o,'federal-test')).jobs,2);await runSyncBatch(o);assert.equal(db.prepare('SELECT count(*) AS n FROM federal_match_index').get().n,2);assert.equal(statistics(db,{season:'2025/26',userId,scope:'federal'}).matches,1);assert.equal(statistics(db,{season:'2025/26',regional:true}).matches,0);assert.equal(db.prepare('SELECT 1 FROM matches WHERE id=91').get(),undefined);assert.equal((await planSync(o,'federal-next')).jobs,0);await runSyncBatch(o);db.prepare("INSERT INTO users(id,name,email,password_hash) VALUES(2,'New referee','new@example.test','activated')").run();db.prepare("INSERT INTO memberships(user_id,season,status,paid,payment_reference,consented_at,category) VALUES(2,'2026/27','active',1,'NEW','2026-10-06','active')").run();assert.equal((await planSync(o,'federal-new-member')).jobs,1);await runSyncBatch(o);assert.equal(statistics(db,{season:'2025/26',userId:2,scope:'federal'}).matches,1);assert.ok(calls.every(p=>!p.startsWith('/venues/')));assert.equal(db.prepare('SELECT count(*) AS n FROM stats_sync_jobs').get().n,0);}finally{db.close();}});

test('large import planning stores small individual jobs instead of a single huge SQL value',async()=>{const db=cloudStore();try{pilot(db);const rows=Array.from({length:10000},(_,i)=>({...match,MatchID:10000+i})),o=owner(db,rows);assert.equal((await planSync(o,'large')).jobs,10000);assert.ok(db.prepare('SELECT length(jobs) AS n FROM regional_sync_plan').get().n<1000);assert.equal(db.prepare('SELECT count(*) AS n FROM stats_sync_jobs').get().n,10000);assert.ok(db.prepare('SELECT max(length(competition)) AS n FROM stats_sync_jobs').get().n<1000);}finally{db.close();}});
