import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cloudStore} from './cloud-fixture.mjs';
import {createApp} from '../cloudflare/api.mjs';
import {hashPassword,newToken,digest} from '../cloudflare/store.mjs';
function fixture(t){const db=cloudStore(),sent=[];t.after(()=>db.close());const {handler}=createApp({db,env:{SEASON:'2026/27',SWISH_NUMBER:'1231494988',PUBLIC_ORIGIN:'https://vdk.nu'},mailer:async m=>sent.push(m)});return {db,sent,async request(path,{method='GET',body,cookie='',origin='https://vdk.nu'}={}){let status=200,output;const headers={};await handler({url:'/api'+path,method,socket:{remoteAddress:'test'},headers:{origin,cookie,'content-type':'application/json'},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(body||{}));}},{setHeader:(k,v)=>headers[k.toLowerCase()]=v,writeHead:(s,h)=>{status=s;Object.assign(headers,h);},end:v=>output=v});return {status,data:JSON.parse(output||'null'),headers};}};}
function admin(db){const id=Number(db.prepare('INSERT INTO users(name,email,password_hash) VALUES (?,?,?)').run('Pilot Admin','admin@example.test',hashPassword('Admin-password-123')).lastInsertRowid);db.prepare("INSERT INTO roles VALUES (?,'ADMIN')").run(id);const token=newToken();db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(digest(token),id,Date.now()+600000);return 'vdk_session='+token;}

test('Cloudflare membership completes payment, activation, login, reset and logout for all member categories',async t=>{const {db,sent,request}=fixture(t);const adminCookie=admin(db);for(const category of ['active','support','club']){const email=category+'@example.test';const application=await request('/applications',{method:'POST',body:{name:'Pilot '+category,email,category,season:'2026/27',consent:true,organization:'Pilot Club'}});assert.equal(application.status,201);const row=db.prepare('SELECT * FROM memberships WHERE payment_reference=?').get(application.data.paymentReference);assert.equal((await request(`/admin/applications/${row.id}/approve`,{method:'POST',cookie:adminCookie})).status,409);assert.equal((await request(`/admin/applications/${row.id}/payment`,{method:'POST',cookie:adminCookie})).status,200);assert.equal((await request(`/admin/applications/${row.id}/approve`,{method:'POST',cookie:adminCookie})).status,200);const token=sent.at(-1).html.match(/token=([A-Za-z0-9_-]+)/)[1];assert.ok(sent.at(-1).html.includes('https://vdk.nu/'));assert.equal((await request('/auth/activate',{method:'POST',body:{token,password:'Pilot-password-123'}})).status,200);assert.equal((await request('/auth/activate',{method:'POST',body:{token,password:'Pilot-password-123'}})).status,400);const login=await request('/auth/login',{method:'POST',body:{email,password:'Pilot-password-123'}});assert.equal(login.status,200);const cookie=login.headers['set-cookie'].split(';')[0];assert.match(login.headers['set-cookie'],/HttpOnly.*SameSite=Lax.*Secure/);assert.equal((await request('/me',{cookie})).status,200);assert.equal((await request('/regional-statistics',{cookie})).status,200);assert.equal((await request('/admin/members',{cookie})).status,403);assert.equal((await request('/auth/request-reset',{method:'POST',body:{email}})).status,200);const reset=sent.at(-1).html.match(/token=([A-Za-z0-9_-]+)/)[1];assert.equal((await request('/auth/reset',{method:'POST',body:{token:reset,password:'New-password-123'}})).status,200);assert.equal((await request('/me',{cookie})).status,401);assert.equal((await request('/auth/login',{method:'POST',body:{email,password:'Pilot-password-123'}})).status,401);const next=await request('/auth/login',{method:'POST',body:{email,password:'New-password-123'}});assert.equal(next.status,200);const nextCookie=next.headers['set-cookie'].split(';')[0];assert.equal((await request('/auth/logout',{method:'POST',cookie:nextCookie})).status,200);assert.equal((await request('/me',{cookie:nextCookie})).status,401);}});

test('Cloudflare enforces origins and keeps admin access independent of fictional payments',async t=>{const {db,request}=fixture(t);const cookie=admin(db);assert.equal((await request('/me',{cookie})).status,200);assert.equal((await request('/auth/login',{method:'POST',origin:'https://unrelated.example',body:{email:'admin@example.test',password:'Admin-password-123'}})).status,403);assert.equal(db.prepare('SELECT count(*) AS n FROM memberships').get().n,0);assert.equal((await request('/regional-statistics')).status,401);assert.equal((await request('/auth/login',{method:'POST',body:{email:'admin@example.test',password:'Admin-password-123'}})).status,200);});
