import {test} from 'node:test';
import assert from 'node:assert/strict';
import {cloudStore} from './cloud-fixture.mjs';
import {createApp} from '../cloudflare/api.mjs';
import {hashPassword,newToken,digest} from '../cloudflare/store.mjs';
function fixture(t){const db=cloudStore(),sent=[];t.after(()=>db.close());const {handler}=createApp({db,env:{SEASON:'2026/27',SWISH_NUMBER:'1231494988',PUBLIC_ORIGIN:'https://vdk.nu'},mailer:async m=>sent.push(m)});return {db,sent,async request(path,{method='GET',body,cookie='',origin='https://vdk.nu'}={}){let status=200,output;const headers={};await handler({url:'/api'+path,method,socket:{remoteAddress:'test'},headers:{origin,cookie,'content-type':'application/json'},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify(body||{}));}},{setHeader:(k,v)=>headers[k.toLowerCase()]=v,writeHead:(s,h)=>{status=s;Object.assign(headers,h);},end:v=>output=v});return {status,data:JSON.parse(output||'null'),headers};}};}
function admin(db){const id=Number(db.prepare('INSERT INTO users(name,email,password_hash) VALUES (?,?,?)').run('Pilot Admin','admin@example.test',hashPassword('Admin-password-123')).lastInsertRowid);db.prepare("INSERT INTO roles VALUES (?,'ADMIN')").run(id);const token=newToken();db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(digest(token),id,Date.now()+600000);return 'vdk_session='+token;}

test('Cloudflare membership completes payment, activation, login, reset and logout for all member categories',async t=>{const {db,sent,request}=fixture(t);const adminCookie=admin(db);for(const category of ['active','support','club']){const email=category+'@example.test';const application=await request('/applications',{method:'POST',body:{name:'Pilot '+category,email,category,season:'2026/27',consent:true,organization:'Pilot Club'}});assert.equal(application.status,201);const row=db.prepare('SELECT * FROM memberships WHERE payment_reference=?').get(application.data.paymentReference);assert.equal((await request(`/admin/applications/${row.id}/approve`,{method:'POST',cookie:adminCookie})).status,409);assert.equal((await request(`/admin/applications/${row.id}/payment`,{method:'POST',cookie:adminCookie})).status,200);assert.equal((await request(`/admin/applications/${row.id}/approve`,{method:'POST',cookie:adminCookie})).status,200);const token=sent.at(-1).html.match(/token=([A-Za-z0-9_-]+)/)[1];assert.ok(sent.at(-1).html.includes('https://vdk.nu/'));assert.equal((await request('/auth/activate',{method:'POST',body:{token,password:'Pilot-password-123'}})).status,200);assert.equal((await request('/auth/activate',{method:'POST',body:{token,password:'Pilot-password-123'}})).status,400);const login=await request('/auth/login',{method:'POST',body:{email,password:'Pilot-password-123'}});assert.equal(login.status,200);const cookie=login.headers['set-cookie'].at(0).split(';')[0];assert.match(login.headers['set-cookie'].at(0),/HttpOnly; Path=\/; SameSite=Lax.*Secure/);assert.equal((await request('/me',{cookie})).status,200);assert.equal((await request('/regional-statistics',{cookie})).status,category==='support'?403:200);assert.equal((await request('/admin/members',{cookie})).status,403);assert.equal((await request('/auth/request-reset',{method:'POST',body:{email}})).status,200);const reset=sent.at(-1).html.match(/token=([A-Za-z0-9_-]+)/)[1];assert.equal((await request('/auth/reset',{method:'POST',body:{token:reset,password:'New-password-123'}})).status,200);assert.equal((await request('/me',{cookie})).status,401);assert.equal((await request('/auth/login',{method:'POST',body:{email,password:'Pilot-password-123'}})).status,401);const next=await request('/auth/login',{method:'POST',body:{email,password:'New-password-123'}});assert.equal(next.status,200);const nextCookie=next.headers['set-cookie'].at(0).split(';')[0];assert.equal((await request('/auth/logout',{method:'POST',cookie:nextCookie})).status,200);assert.equal((await request('/me',{cookie:nextCookie})).status,401);}});

test('Cloudflare enforces origins and keeps admin access independent of fictional payments',async t=>{const {db,request}=fixture(t);const cookie=admin(db);assert.equal((await request('/me',{cookie})).status,200);assert.equal((await request('/auth/login',{method:'POST',origin:'https://unrelated.example',body:{email:'admin@example.test',password:'Admin-password-123'}})).status,403);assert.equal(db.prepare('SELECT count(*) AS n FROM memberships').get().n,0);assert.equal((await request('/regional-statistics')).status,401);assert.equal((await request('/auth/login',{method:'POST',body:{email:'admin@example.test',password:'Admin-password-123'}})).status,200);});

test('full rule generator restricts access to paid active, support and club members approved for current season',async t=>{const {db,request}=fixture(t);assert.equal((await request('/rules/access')).status,401);for(const [category,status,paid,expected] of [['active','pending',0,403],['active','pending',1,403],['active','approved',1,403],['active','active',0,403],['active','active',1,200],['club','active',1,200],['support','active',1,200],['business','active',1,403],['club','expired',1,403]]){const id=Number(db.prepare('INSERT INTO users(name,email) VALUES (?,?)').run('Rule test',category+status+paid+'@example.test').lastInsertRowid);db.prepare('INSERT INTO memberships(user_id,season,status,paid,payment_reference,consented_at,category,amount) VALUES (?,?,?,?,?,?,?,?)').run(id,'2026/27',status,paid,'RULE-'+id,new Date().toISOString(),category,100);const token=newToken();db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(digest(token),id,Date.now()+60000);assert.equal((await request('/rules/access',{cookie:'vdk_session='+token})).status,expected,category+status+paid);}assert.equal((await request('/rules/access',{cookie:admin(db)})).status,200);});

test('account activation and membership payment work independently in either order',async t=>{const {db,sent,request}=fixture(t);const adminCookie=admin(db);
  const application=await request('/applications',{method:'POST',body:{name:'Pending Account',email:'pending-account@example.test',season:'2026/27',category:'active',consent:true}});
  assert.equal(application.status,201);assert.equal(sent.length,1);
  const row=db.prepare('SELECT * FROM memberships WHERE payment_reference=?').get(application.data.paymentReference);
  const activationToken=sent[0].html.match(/token=([A-Za-z0-9_-]+)/)[1];
  assert.equal((await request('/auth/activate',{method:'POST',body:{token:activationToken,password:'Pending-password-123'}})).status,200);
  const login=await request('/auth/login',{method:'POST',body:{email:'pending-account@example.test',password:'Pending-password-123'}});
  assert.equal(login.status,200);const cookie=login.headers['set-cookie'].at(0).split(';')[0];
  assert.equal((await request('/me',{cookie})).status,200);
  assert.equal((await request('/membership',{cookie})).status,200);
  assert.equal((await request('/dashboard',{cookie})).data.access,false);
  assert.equal((await request(`/admin/applications/${row.id}/payment`,{method:'POST',cookie:adminCookie})).status,200);
  assert.equal((await request(`/admin/applications/${row.id}/approve`,{method:'POST',cookie:adminCookie})).status,200);
  assert.equal((await request('/dashboard',{cookie})).status,200);

  const second=await request('/applications',{method:'POST',body:{name:'Paid First',email:'paid-first@example.test',season:'2026/27',category:'active',consent:true}});
  const secondRow=db.prepare('SELECT * FROM memberships WHERE payment_reference=?').get(second.data.paymentReference);
  assert.equal((await request(`/admin/applications/${secondRow.id}/payment`,{method:'POST',cookie:adminCookie})).status,200);
  assert.equal((await request(`/admin/applications/${secondRow.id}/approve`,{method:'POST',cookie:adminCookie})).status,200);
  const secondToken=sent.at(-1).html.match(/token=([A-Za-z0-9_-]+)/)[1];
  assert.equal((await request('/auth/activate',{method:'POST',body:{token:secondToken,password:'Paid-first-password-123'}})).status,200);
  const secondLogin=await request('/auth/login',{method:'POST',body:{email:'paid-first@example.test',password:'Paid-first-password-123'}});
  assert.equal(secondLogin.status,200);assert.equal((await request('/dashboard',{cookie:secondLogin.headers['set-cookie'].at(0).split(';')[0]})).status,200);
});
