import {test} from 'node:test';
import assert from 'node:assert/strict';
import {openStore,createAdmin,importMatch,statistics,newToken,digest,hashPassword} from '../server/store.mjs';
import {createApp} from '../server/index.mjs';

const season='2026/27';
test('membership categories set server-controlled fees and preserve the organization',async t=>{const {db,request}=await fixture(t);for(const [category,amount,expected]of [['active',1,100],['support',5000,100],['club',100,1500],['business',1750,1750]]){const result=await request('/applications',{method:'POST',body:{name:'Kontaktperson',email:category+'@example.test',season,consent:true,category,amount,organization:'Testorganisation'}});assert.equal(result.status,201);assert.equal(result.data.fee,expected);const saved=db.prepare('SELECT category,amount,organization FROM memberships WHERE payment_reference=?').get(result.data.paymentReference);assert.equal(saved.category,category);assert.equal(saved.amount,expected);assert.equal(saved.organization,['club','business'].includes(category)?'Testorganisation':'');}assert.equal((await request('/applications',{method:'POST',body:{name:'Företag',email:'low@example.test',season,consent:true,category:'business',amount:999,organization:'Företag'}})).status,400);assert.equal((await request('/applications',{method:'POST',body:{name:'Förening',email:'missing@example.test',season,consent:true,category:'club'}})).status,400);assert.equal((await request('/applications',{method:'POST',body:{name:'Okänd',email:'unknown@example.test',season,consent:true,category:'other'}})).status,400);});
function member(db,name='Domare',mail='domare@example.test'){const id=Number(db.prepare('INSERT INTO users(name,email,password_hash) VALUES (?,?,?)').run(name,mail,hashPassword('Test-password-123')).lastInsertRowid);db.prepare("INSERT INTO roles VALUES (?,'MEMBER')").run(id);db.prepare("INSERT INTO memberships(user_id,season,status,paid,payment_reference,consented_at) VALUES (?,?,'active',1,?,?)").run(id,season,'REF-'+id,new Date().toISOString());return id;}
function session(db,id){const token=newToken();db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(digest(token),id,Date.now()+60000);return 'vdk_session='+token;}
const record=(ids,level='senior')=>({externalMatchId:'official-match-1',season,startsAt:'2026-10-10T14:00:00Z',home:'Hemmalag',away:'Bortalag',level,sourceUrl:'https://stats.innebandy.se/match/1',members:ids.map((userId,i)=>({userId,colleague:i?'Domare A':'Domare B'})),penalties:[{externalEventId:'1',category:'Slag',seconds:100},{externalEventId:'2',category:'Hårt spel',seconds:200}]});
async function fixture(t){const db=openStore();const sent=[];const {server}=createApp({db,season,origin:'http://localhost',swishNumber:'1230000000',mailer:async message=>{sent.push(message);}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;t.after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();});const request=async(path,{method='GET',body,cookie,origin='http://localhost'}={})=>{const r=await fetch(base+'/api'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),Origin:origin,...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),headers:r.headers};};return {db,request,sent,base};}

test('VDK totals count a shared match and its events once; repeated imports remain idempotent',()=>{const db=openStore();try{const a=member(db,'A','a@example.test'),b=member(db,'B','b@example.test');importMatch(db,record([a,b]));importMatch(db,record([a,b]));assert.equal(statistics(db,{season}).matches,1);assert.equal(statistics(db,{season}).penalties,2);assert.equal(statistics(db,{season,userId:a}).penalties,2);assert.equal(statistics(db,{season,userId:b}).penalties,2);assert.equal(statistics(db,{season,userId:a,colleague:'Domare B'}).matches,1);assert.equal(statistics(db,{season,userId:a,colleague:'Okänd'}).matches,0);}finally{db.close();}});
test('unaffiliated referees cannot be imported and failed imports are rolled back',()=>{const db=openStore();try{const id=Number(db.prepare('INSERT INTO users(name,email) VALUES (?,?)').run('Utanför VDK','outside@example.test').lastInsertRowid);assert.throws(()=>importMatch(db,record([id])),/VDK-medlemmar/);assert.equal(db.prepare('SELECT count(*) n FROM matches').get().n,0);}finally{db.close();}});
test('members cannot view admin data; unpublished coaching remains private',async t=>{const {db,request}=await fixture(t);const a=member(db),b=member(db,'B','b@example.test');const matchId=importMatch(db,record([a,b]));db.prepare('INSERT INTO coachings(match_id,coach_id,member_id,video_url,rights_note) VALUES (?,?,?,?,?)').run(matchId,b,a,'https://example.test/video','Tillstånd bekräftat');const cookie=session(db,a);assert.equal((await request('/admin/members',{cookie})).status,403);assert.equal((await request('/coach/work',{cookie})).status,403);assert.equal((await request('/coachings',{cookie})).data.coachings.length,0);assert.equal((await request('/me')).status,401);});
test('payment approval, activation and login follow the membership flow and activation is single-use',async t=>{const {db,request,sent}=await fixture(t);const adminId=createAdmin(db,{name:'Admin',email:'admin@example.test',password:'Admin-password-123',season});const admin=session(db,adminId);const app=await request('/applications',{method:'POST',body:{name:'Ny medlem',email:'new@example.test',season,consent:true}});assert.equal(app.status,201);const id=db.prepare("SELECT id FROM memberships WHERE payment_reference=?").get(app.data.paymentReference).id;assert.equal((await request(`/admin/applications/${id}/approve`,{method:'POST',body:{},cookie:admin})).status,409);assert.equal((await request(`/admin/applications/${id}/payment`,{method:'POST',body:{},cookie:admin})).status,200);assert.equal((await request(`/admin/applications/${id}/approve`,{method:'POST',body:{},cookie:admin})).status,200);const token=sent[0].html.match(/token=([A-Za-z0-9_-]+)/)[1];const body={token,password:'Member-password-123'};assert.equal((await request('/auth/activate',{method:'POST',body})).status,200);assert.equal((await request('/auth/activate',{method:'POST',body})).status,400);const logged=await request('/auth/login',{method:'POST',body:{email:'new@example.test',password:'Member-password-123'}});assert.equal(logged.status,200);assert.match(logged.headers.get('set-cookie'),/HttpOnly/);assert.match(logged.headers.get('set-cookie'),/SameSite=Lax/);assert.equal((await request('/me',{cookie:logged.headers.get('set-cookie').split(';')[0]})).data.user.name,'Ny medlem');});
test('cross-origin mutations are rejected and private files never served',async t=>{const {request,base}=await fixture(t);assert.equal((await request('/applications',{method:'POST',origin:'https://evil.example',body:{}})).status,403);for(const path of ['/server/store.mjs','/.env','/data/vdk.sqlite','/package.json','/assets/../server/index.mjs','/assets/..%2fserver%2fstore.mjs','/assets/..%5cserver%5cstore.mjs']){assert.equal((await fetch(base+path)).status,404);}});
test('video coaching only accepts senior matches, a participating member and a documented permission',async t=>{const {db,request}=await fixture(t);const adminId=createAdmin(db,{name:'Admin',email:'admin@example.test',password:'Admin-password-123',season});const a=member(db),b=member(db,'Coach','coach@example.test'),other=member(db,'Annan','other@example.test');db.prepare("INSERT INTO roles VALUES (?,'VIDEO_COACH')").run(b);const youth=importMatch(db,record([a],'youth'));const cookie=session(db,adminId);const body={matchId:youth,memberId:a,coachId:b,videoUrl:'https://example.test/video',rightsNote:'Föreningens tillstånd',rightsConfirmed:true};assert.equal((await request('/admin/coachings',{method:'POST',cookie,body})).status,400);importMatch(db,record([a]));assert.equal((await request('/admin/coachings',{method:'POST',cookie,body:{...body,memberId:other}})).status,400);assert.equal((await request('/admin/coachings',{method:'POST',cookie,body:{...body,rightsConfirmed:false}})).status,400);assert.equal((await request('/admin/coachings',{method:'POST',cookie,body})).status,201);});
test('only the assigned coach can publish; publishing notifies only the concerned member',async t=>{const {db,request}=await fixture(t);const a=member(db),coach=member(db,'Coach','coach@example.test'),other=member(db,'Other','other@example.test');for(const id of [coach,other])db.prepare("INSERT INTO roles VALUES (?,'VIDEO_COACH')").run(id);const matchId=importMatch(db,record([a]));const id=Number(db.prepare('INSERT INTO coachings(match_id,coach_id,member_id,video_url,rights_note) VALUES (?,?,?,?,?)').run(matchId,coach,a,'https://example.test/video','Skriftligt tillstånd').lastInsertRowid);const cookie=session(db,coach);assert.equal((await request(`/coach/work/${id}/publish`,{method:'POST',cookie,body:{}})).status,400);assert.equal((await request(`/coach/work/${id}/clips`,{method:'POST',cookie:session(db,other),body:{}})).status,404);assert.equal((await request(`/coach/work/${id}/clips`,{method:'POST',cookie,body:{startSeconds:50,endSeconds:60,category:'Slag',comment:'Diskutera nivån',audioUrl:''}})).status,201);assert.equal((await request(`/coach/work/${id}/publish`,{method:'POST',cookie,body:{}})).status,200);assert.equal((await request('/coachings',{cookie:session(db,a)})).data.coachings.length,1);assert.equal((await request('/coachings',{cookie:session(db,other)})).data.coachings.length,0);assert.equal(db.prepare('SELECT count(*) n FROM notifications WHERE user_id=?').get(a).n,1);assert.equal((await request(`/coach/work/${id}/publish`,{method:'POST',cookie,body:{}})).status,409);});
test('password reset invalidates existing sessions and tokens',async t=>{const {db,request,sent}=await fixture(t);const id=member(db);const cookie=session(db,id);await request('/auth/request-reset',{method:'POST',body:{email:'domare@example.test'}});const token=sent[0].html.match(/token=([A-Za-z0-9_-]+)/)[1];assert.equal((await request('/auth/reset',{method:'POST',body:{token,password:'New-password-123'}})).status,200);assert.equal((await request('/me',{cookie})).status,401);assert.equal((await request('/auth/reset',{method:'POST',body:{token,password:'New-password-123'}})).status,400);});
test('season expiry closes member access even for an existing session',async t=>{const {db,request}=await fixture(t);const id=member(db),cookie=session(db,id);db.prepare("UPDATE memberships SET status='expired' WHERE user_id=?").run(id);assert.equal((await request('/me',{cookie})).status,403);});
test('public rule generator and its dependencies load without exposing server files',async t=>{const {base}=await fixture(t);const response=await fetch(base+'/innebandyregler/');assert.equal(response.status,200);const html=await response.text();assert.ok(html.includes('VDK Regelgenerator 2026'));assert.ok(!html.includes('privacy-controls.js'));const dependencies=[...html.matchAll(/(?:src|href)="([^"#]+\.(?:js|css|svg)(?:\?[^" ]*)?)"/g)].map(x=>x[1]);assert.ok(dependencies.length>10);for(const path of dependencies){const r=await fetch(base+'/innebandyregler/'+path);assert.equal(r.status,200,path);}assert.equal((await fetch(base+'/innebandyregler/..%2fserver%2fstore.mjs')).status,404);assert.equal((await fetch(base+'/innebandyregler/..%5cserver%5cstore.mjs')).status,404);});
