import {test} from 'node:test';
import assert from 'node:assert/strict';
import {openStore,statistics} from '../server/store.mjs';
import {syncStats} from '../server/stats-sync.mjs';
import {isLeague,memberRecord,penaltySeconds} from '../server/stats-source.mjs';
import {scheduledWindow} from '../server/stats-scheduler.mjs';

const league={CompetitionID:1,CompetitionTypeID:1,Name:'Herrar Division 3'};
const match={SeasonID:43,CompetitionID:1,MatchID:1,MatchDateTime:'2025-10-01T18:00:00',HomeTeam:'Arvika IBF U',HomeTeamID:10,AwayTeam:'Gäster',AwayTeamID:20,HomeMatchTeamID:100,AwayMatchTeamID:200,Referee1ID:8888,Referee1:'Sören Johansson',Referee2ID:99,Referee2:'Kollega',HasFinalResult:true,Events:[{MatchEventID:1,MatchEventTypeID:2,PenaltyCode:'404',PenaltyName:'Hårt spel, 2+2 min',MatchTeamID:100,Period:2,Minute:1,Second:2},{MatchEventID:2,MatchEventTypeID:2,PenaltyCode:'201',PenaltyName:'Slag, 2 min',MatchTeamID:200}]};
function roster(db){for(let n=0;n<100;n++){const name=n===0?'Sören Johansson':n===1?'Kollega':'Domare '+n;const id=Number(db.prepare('INSERT INTO users(name,email) VALUES (?,?)').run(name,n+'@example.test').lastInsertRowid);db.prepare("INSERT INTO stats_profiles(user_id,name,enabled,authorization) VALUES (?,?,1,'test-pilot')").run(id,name);}return db.prepare("SELECT id FROM users WHERE name='Sören Johansson'").get().id;}
function source(data=match){const calls=[];return {calls,async get(path){calls.push(path);if(path==='/seasons/')return [{SeasonID:43,Name:'2025/26'}];if(path.includes('/federations/'))return [league,{CompetitionID:2,Name:'Träningsmatcher'}];if(path==='/competitions/1')return league;if(path==='/competitions/2')return {CompetitionID:2,CompetitionTypeID:1,Name:'Träningsmatcher'};if(path.endsWith('/matches'))return [{MatchID:1,MatchDateTime:data.MatchDateTime}];if(path==='/matches/1')return data;throw Error(path);}};}

test('100-member scan fetches a shared match once, discovers IDs by name and excludes training',async()=>{const db=openStore();try{const id=roster(db),s=source();const report=await syncStats(db,{source:s,seasonIds:[43],federationIds:[11],full:true});assert.equal(report.status,'complete');assert.equal(report.imported,1);assert.equal(s.calls.filter(x=>x==='/matches/1').length,1);assert.equal(db.prepare('SELECT referee_id FROM stats_profiles WHERE user_id=?').get(id).referee_id,8888);assert.equal(db.prepare('SELECT count(*) n FROM match_members').get().n,2);const overall=statistics(db,{userId:id,season:'all'});assert.equal(overall.penalties,2);assert.equal(overall.matches,1);const against=statistics(db,{userId:id,season:'all',team:'10',against:true});assert.equal(against.penalties,1);assert.equal(against.categories[0].seconds,240);assert.equal(against.matchList[0].penalty_count,1);assert.equal(against.colleagueSummary[0].penalties,1);await syncStats(db,{source:s,seasonIds:[43],federationIds:[11],full:true});assert.equal(statistics(db,{userId:id,season:'all'}).penalties,2);}finally{db.close();}});
test('missing events preserve verified data and report pending underlay',async()=>{const db=openStore();try{const id=roster(db);await syncStats(db,{source:source(),seasonIds:[43],federationIds:[11],full:true});const report=await syncStats(db,{source:source({...match,Events:null}),seasonIds:[43],federationIds:[11],full:true});assert.equal(report.unreported,1);assert.equal(statistics(db,{userId:id,season:'all'}).penalties,2);}finally{db.close();}});
test('a failed fetch does not erase imported events; overlap is blocked',async()=>{const db=openStore();try{const id=roster(db);await syncStats(db,{source:source(),seasonIds:[43],federationIds:[11],full:true});const s=source();const read=s.get;s.get=async p=>{if(p==='/matches/1')throw Error('Source unavailable');return read(p)};assert.equal((await syncStats(db,{source:s,seasonIds:[43],federationIds:[11],full:true})).status,'partial');assert.equal(statistics(db,{userId:id,season:'all'}).penalties,2);db.prepare('INSERT INTO sync_lock VALUES (1,?)').run(Date.now());await assert.rejects(syncStats(db,{source:s}),/pågår redan/);}finally{db.close();}});
test('Monday 03 schedule uses Swedish summer and winter time',()=>{assert.equal(scheduledWindow(new Date('2026-10-05T01:00:00Z')),'2026-10-05');assert.equal(scheduledWindow(new Date('2026-11-02T02:00:00Z')),'2026-11-02');assert.equal(scheduledWindow(new Date('2026-10-04T01:00:00Z')),null);assert.equal(scheduledWindow(new Date('2026-10-05T02:00:00Z')),null);});
test('incremental runs reuse old index and later cancellation excludes the match',async()=>{const db=openStore();try{const id=roster(db);await syncStats(db,{source:source(),seasonIds:[43],federationIds:[11],full:true});const s=source();await syncStats(db,{source:s,seasonIds:[43],federationIds:[11]});assert.equal(s.calls.filter(x=>x==='/matches/1').length,0);const cancelled=source();const read=cancelled.get;cancelled.get=async p=>p==='/competitions/1/matches'?[{MatchID:1,MatchDateTime:match.MatchDateTime,Cancelled:true}]:read(p);await syncStats(db,{source:cancelled,seasonIds:[43],federationIds:[11]});assert.equal(statistics(db,{season:'all',userId:id}).matches,0);assert.equal(db.prepare('SELECT count(*) n FROM penalties').get().n,2);}finally{db.close();}});
test('series filter combines with team and colleague instead of counting other divisions',async()=>{const db=openStore();try{const id=roster(db);await syncStats(db,{source:source(),seasonIds:[43],federationIds:[11],full:true});assert.equal(statistics(db,{season:'all',userId:id,team:'10',competition:'Herrar Division 3',colleague:'Kollega',against:true}).penalties,1);assert.equal(statistics(db,{season:'all',userId:id,team:'10',competition:'Herrar Division 2',against:true}).penalties,0);}finally{db.close();}});
test('league eligibility and compound penalties retain meaning',()=>{assert.ok(isLeague(league));assert.equal(isLeague({...league,Name:'Träningsmatcher'}),false);assert.equal(isLeague({...league,CompetitionTypeID:2}),false);assert.equal(penaltySeconds('Hårt spel, 2+2 min'),240);assert.equal(penaltySeconds('2 min + 10 min personligt straff'),720);assert.equal(memberRecord(match,league,'2025/26',[{userId:1,refereeId:8888}]).penalties[0].code,'404');});
