import {initializeMatchComments} from '../cloudflare/match-comments.mjs';
import {messageDirectory} from '../cloudflare/messages.mjs';
export function initializeMemberTools(db){initializeMatchComments(db);db.exec(`CREATE TABLE IF NOT EXISTS match_referees(match_id INTEGER NOT NULL REFERENCES matches(id),referee_id INTEGER NOT NULL,name TEXT NOT NULL,normalized_name TEXT NOT NULL,PRIMARY KEY(match_id,referee_id));CREATE INDEX IF NOT EXISTS referee_matches ON match_referees(referee_id,match_id);CREATE TABLE IF NOT EXISTS member_profiles(user_id INTEGER PRIMARY KEY REFERENCES users(id),contact_email TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',city TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',departure TEXT NOT NULL DEFAULT '',bio TEXT NOT NULL DEFAULT '',share_profile INTEGER NOT NULL DEFAULT 0,share_photo INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL);`);}
const blank={contact_email:'',phone:'',city:'',address:'',departure:'',bio:'',share_profile:0,share_photo:0};
const profile=(db,id)=>({...blank,...db.prepare('SELECT * FROM member_profiles WHERE user_id=?').get(id)});
const fold=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('sv-SE');
const sqlFold=e=>`lower(replace(replace(replace(replace(replace(replace(${e},'Å','a'),'Ä','a'),'Ö','o'),'å','a'),'ä','a'),'ö','o'))`;
export function searchMatches(db,params,currentSeason='2026/27'){
 const q=(params.get('q')||'').trim(),season=params.get('season')||'2026/27',offset=Math.max(0,Math.min(100000,Math.trunc(Number(params.get('offset')))||0)),limit=30;
 const terms=fold(q).split(/\s+/).filter(Boolean).slice(0,8),where=['m.excluded=0','m.regional_eligible=1'],args=[];
 if(season!=='all'){where.push('m.season=?');args.push(season);}
 for(const term of terms){const variants=term==='h18'?['hj18','herrjunior18']:term==='d18'?['dj18','damjunior18']:/^h[2-5]$/.test(term)?[term,'herrar division '+term.slice(1)]:/^d[1-3]$/.test(term)?[term,'damer division '+term.slice(1)]:[term];const expression=sqlFold("m.home||' '||m.away||' '||m.competition_name||' '||COALESCE((SELECT group_concat(r.name,' ') FROM match_referees r WHERE r.match_id=m.id),'')");where.push('('+variants.map(()=>`${expression} LIKE ? ESCAPE '\\'`).join(' OR ')+(variants.length>1?' OR '+variants.map(()=>`replace(${expression},' ','') LIKE ? ESCAPE '\\'`).join(' OR '):'')+')');const values=variants.map(v=>'%'+v.replace(/[\\%_]/g,x=>'\\'+x)+'%');args.push(...values,...(variants.length>1?values:[]));}
 const from=' FROM matches m WHERE '+where.join(' AND '),total=db.prepare('SELECT count(*) AS n'+from).get(...args).n;
 const matches=db.prepare('SELECT m.*,(SELECT count(*) FROM match_comments c WHERE c.match_id=m.id) AS comment_count'+from+' ORDER BY m.starts_at DESC,m.id DESC LIMIT ? OFFSET ?').all(...args,limit,offset);
 const members=messageDirectory(db,0,currentSeason,true),byName=new Map(members.map(m=>[fold(m.name),m.id]));
 for(const m of matches)m.referees=db.prepare('SELECT referee_id,name FROM match_referees WHERE match_id=? ORDER BY referee_id').all(m.id).map(r=>({...r,userId:byName.get(fold(r.name))||null}));
 return {matches,total,offset,hasMore:offset+matches.length<total,seasons:db.prepare('SELECT DISTINCT season FROM matches WHERE excluded=0 ORDER BY season DESC').all().map(r=>r.season)};
}
export function memberToolsAction({db,path,method,body,req,auth,requireMembership,season,fail,res,json:sendJson,url}){
 const json=(...args)=>{sendJson(...args);return true;};
 if(path==='/api/profile'&&['GET','POST'].includes(method)){const u=auth(req);if(method==='GET')return json(200,{profile:{name:u.name,...profile(db,u.id)}});
 const clean={};for(const [key,max]of Object.entries({contact_email:254,phone:40,city:100,address:200,departure:200,bio:1000})){const value=body[key]??'';if(typeof value!=='string'||value.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))fail(400,'Kontrollera profiluppgifterna.');clean[key]=value.trim();}if(clean.contact_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean.contact_email))fail(400,'Ange en giltig e-postadress eller lämna fältet tomt.');for(const key of ['share_profile','share_photo'])if(typeof body[key]!=='boolean')fail(400,'Välj vilka uppgifter som ska delas.');
 db.prepare(`INSERT INTO member_profiles(user_id,contact_email,phone,city,address,departure,bio,share_profile,share_photo,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET contact_email=excluded.contact_email,phone=excluded.phone,city=excluded.city,address=excluded.address,departure=excluded.departure,bio=excluded.bio,share_profile=excluded.share_profile,share_photo=excluded.share_photo,updated_at=excluded.updated_at`).run(u.id,...Object.values(clean),body.share_profile?1:0,body.share_photo?1:0,new Date().toISOString());return json(200,{ok:true});}
 if(path==='/api/members'&&method==='GET'){const u=requireMembership(req);return json(200,{members:messageDirectory(db,u.id,season,true).map(m=>{const p=profile(db,m.id);return {...m,city:p.share_profile?p.city:'',departure:p.share_profile?p.departure:'',hasPhoto:!!p.share_photo&&!!db.prepare('SELECT 1 FROM profile_photos WHERE user_id=?').get(m.id)};})});}
 const target=path.match(/^\/api\/members\/(\d+)\/(profile|photo)$/);if(target&&method==='GET'){const u=requireMembership(req),id=Number(target[1]);if(!messageDirectory(db,u.id,season,true).some(m=>m.id===id))fail(404,'Medlemmen hittades inte.');const p=profile(db,id),name=db.prepare('SELECT name FROM users WHERE id=?').get(id).name;
 if(target[2]==='photo'){if(!p.share_photo)fail(404,'Ingen delad profilbild.');const image=db.prepare('SELECT mime,data FROM profile_photos WHERE user_id=?').get(id);if(!image)fail(404,'Ingen delad profilbild.');res.writeHead(200,{'Content-Type':image.mime,'Cache-Control':'private, no-store','Content-Security-Policy':"default-src 'none'"});res.end(Buffer.from(image.data));return true;}
 return json(200,{profile:{name,...(p.share_profile?Object.fromEntries(Object.keys(blank).filter(k=>!k.startsWith('share_')).map(k=>[k,p[k]])):{}),hasPhoto:!!p.share_photo&&!!db.prepare('SELECT 1 FROM profile_photos WHERE user_id=?').get(id),userId:id}});}
 if(path==='/api/match-search'&&method==='GET'){const u=requireMembership(req);if(db.prepare('SELECT category FROM memberships WHERE user_id=? AND season=?').get(u.id,season)?.category==='support'&&!u.roles.includes('ADMIN'))fail(403,'Matchsökning ingår inte i stödmedlemskapet.');const q=url.searchParams.get('q')||'';if(q.length<2||q.length>150)fail(400,'Skriv minst två och högst 150 tecken.');const year=url.searchParams.get('season')||season;if(!/^(?:all|20\d\d\/\d\d)$/.test(year))fail(400,'Välj en giltig säsong.');return json(200,searchMatches(db,url.searchParams,season));}
 return false;
}
