import {coachingAction} from './coaching.mjs';
import {dashboard} from './dashboard.mjs';
import {commentedMatches} from './match-comments.mjs';
import {messageDirectory,unreadMessages,messageThreads,conversation} from './messages.mjs';
import {availabilityResults} from './availability.mjs';
import {canGrantAdmin,reactivateMembership,grantAdmin} from '../server/admin-actions.mjs';
import {digest,hashPassword,verifyPassword,newToken,transaction,getRoles,publicUser,hasMembership,audit,statistics,importMatch} from './store.mjs';
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new HttpError(status,message);};
function text(v,min,max){if(typeof v!=='string'||v.trim().length<min||v.length>max)fail(400,'Kontrollera att alla fält är korrekt ifyllda.');return v.trim();}
function email(v){v=text(v,3,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Ange en giltig e-postadress.');return v;}
function password(v){if(typeof v!=='string'||v.length<12||v.length>256)fail(400,'Lösenordet måste ha 12–256 tecken.');return v;}
function httpsUrl(v,optional=false){if(optional&&!v)return '';try{const u=new URL(v);if(u.protocol!=='https:'||u.username||u.password)throw Error();return u.href;}catch{fail(400,'Ange en giltig https-länk.');}}
async function readBody(req,limit=32768){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>limit)fail(413,'För mycket data.');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{fail(400,'Ogiltigt formulär.');}}
const defaultMailer=async({to,subject,html},env)=>{if(!env.RESEND_API_KEY||!env.EMAIL_FROM)fail(503,'E-posttjänsten är inte konfigurerad.');const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.EMAIL_FROM,to:[to],subject,html})});if(!response.ok)fail(502,'E-post kunde inte skickas. Försök igen.');};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createApp(options={}){
  const db=options.db;
  const season=options.season||options.env.SEASON||'2026/27';
  const origin=options.origin||options.env.PUBLIC_ORIGIN||'http://localhost:3000';
  const swishNumber=options.swishNumber||options.env.SWISH_NUMBER||'';
  const mailer=options.mailer||(message=>defaultMailer(message,options.env));
  const mailReady=!!options.mailer||!!(options.env.EMAIL_ENABLED==='true'&&options.env.RESEND_API_KEY&&options.env.EMAIL_FROM);
  const secure=new URL(origin).protocol==='https:';
  const allowed=new Set([origin,...(options.env.ALLOWED_ORIGINS||'').split(',').filter(Boolean)]);
  const limits=new Map();
  const ownerAdminEmail=options.env.OWNER_ADMIN_EMAIL;
  const dummyHash=hashPassword(newToken());
  function rate(req,key,max){const id=key+':'+req.socket.remoteAddress;const now=Date.now();let bucket=limits.get(id);if(!bucket||bucket.until<now){bucket={count:0,until:now+15*60*1000};limits.set(id,bucket);}if(++bucket.count>max)fail(429,'För många försök. Vänta 15 minuter innan du försöker igen.');if(limits.size>10000)for(const [k,v]of limits)if(v.until<now)limits.delete(k);}
  function auth(req,role){const match=(req.headers.cookie||'').match(/(?:^|;\s*)vdk_session=([A-Za-z0-9_-]+)/);if(!match)fail(401,'Logga in för att fortsätta.');const session=db.prepare('SELECT user_id FROM sessions WHERE token_hash=? AND expires_at>?').get(digest(match[1]),Date.now());if(!session)fail(401,'Din inloggning har gått ut. Logga in igen.');const user=publicUser(db,session.user_id,season);if(role&&!user.roles.includes(role))fail(403,'Du har inte behörighet till den här funktionen.');return user;}
  function requireMembership(req,role){const user=auth(req,role);if(!hasMembership(db,user.id,season)&&!user.roles.includes('ADMIN'))fail(403,'Ditt medlemskap är ännu inte aktivt. VDK behöver registrera och godkänna din betalning för aktuell säsong.');return user;}
  async function sendActivation(member){if(!mailReady)fail(503,'E-post måste konfigureras innan Mina sidor kan aktiveras.');db.prepare("DELETE FROM tokens WHERE user_id=? AND kind='activation'").run(member.user_id);const token=newToken();db.prepare("INSERT INTO tokens(token_hash,user_id,membership_id,kind,expires_at) VALUES (?,?,?,'activation',?)").run(digest(token),member.user_id,member.id,Date.now()+48*60*60*1000);const link=`${origin}/#/aktivera?token=${token}`;try{await mailer({to:member.email,subject:'Aktivera ditt konto på Mina sidor hos VDK',html:`<p>Välkommen till VDK.</p><p>Ett konto till Mina sidor har skapats för dig. Välj ett lösenord för att aktivera ditt konto.</p><p><a href="${escapeHtml(link)}">Välj ditt lösenord och aktivera Mina sidor</a></p><p>Länken gäller i 48 timmar.</p><p>Du kan logga in efter aktiveringen. Medlemsfunktionerna låses upp när VDK har registrerat din betalning och godkänt medlemskapet.</p>`});}catch(e){db.prepare('DELETE FROM tokens WHERE token_hash=?').run(digest(token));throw e;}}
  const handler=async(req,res)=>{
    const requestOrigin=req.headers.origin;
    res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');
    if(secure)res.setHeader('Strict-Transport-Security','max-age=31536000');
    const json=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
    try{
      const url=new URL(req.url,origin);const path=url.pathname;const method=req.method;
      if(path.startsWith('/api/')){
        if(requestOrigin){if(!allowed.has(requestOrigin))fail(403,'Webbplatsens ursprung är inte tillåtet.');res.setHeader('Access-Control-Allow-Origin',requestOrigin);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Vary','Origin');}
        if(method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type'});return res.end();}
        if(!['GET','POST'].includes(method))fail(405,'Metoden stöds inte.');
        if(method==='POST'){
          if(!requestOrigin||!allowed.has(requestOrigin))fail(403,'Begäran måste komma från VDK:s webbplats.');
          if(!(req.headers['content-type']||'').startsWith('application/json'))fail(415,'JSON krävs.');
        }
        const body=method==='POST'?await readBody(req,path==='/api/profile/photo'?2800000:32768):{};
        if(path==='/api/rules/access'&&method==='GET'){const u=auth(req);if(!u.roles.includes('ADMIN')&&!db.prepare("SELECT 1 FROM memberships WHERE user_id=? AND season=? AND category IN ('active','club') AND status='active' AND paid=1").get(u.id,season))fail(403,'Fullversionen kräver ett godkänt aktivt medlemskap eller föreningsmedlemskap.');return json(200,{ok:true});}
        if(path==='/api/availability'&&method==='GET'){requireMembership(req);return json(200,availabilityResults(db,url.searchParams));}
        if(path==='/api/health'&&method==='GET')return json(200,{ok:true});
        if(path==='/api/settings'&&method==='GET')return json(200,{season,fee:100,applicationsOpen:!!swishNumber&&mailReady});
        if(path==='/api/applications'&&method==='POST'){
          rate(req,'application',10);if(!swishNumber||!mailReady)fail(503,'Medlemsansökan har inte öppnat ännu. Kontakta VDK.');
          const name=text(body.name,2,120),mail=email(body.email);if(body.consent!==true||body.season!==season)fail(400,'Bekräfta medlemskapet för aktuell säsong.');
          const category=body.category||'active';if(!['active','support','club','business'].includes(category))fail(400,'Välj en giltig medlemskategori.');
          const organization=['club','business'].includes(category)?text(body.organization,2,160):'';
          const amount=category==='club'?1500:category==='business'?Number(body.amount):100;
          if(!Number.isSafeInteger(amount)||amount<(category==='business'?1000:100)||amount>10000000)fail(400,'Företagsstödet ska vara ett helt belopp på minst 1 000 kr.');
          const initialPassword=category!=='business'&&body.password?hashPassword(password(body.password)):null;
          const reference='VDK-'+newToken().slice(0,8).toUpperCase();
          transaction(db,()=>{const existing=db.prepare('SELECT id FROM users WHERE email=?').get(mail);const userId=existing?.id||Number(db.prepare('INSERT INTO users(name,email,password_hash) VALUES (?,?,?)').run(name,mail,initialPassword).lastInsertRowid);if(db.prepare('SELECT 1 FROM memberships WHERE user_id=? AND season=?').get(userId,season))fail(409,'Det finns redan en ansökan eller ett medlemskap för den här säsongen. Kontakta VDK.');db.prepare('INSERT INTO memberships(user_id,season,payment_reference,consented_at,category,amount,organization) VALUES (?,?,?,?,?,?,?)').run(userId,season,reference,new Date().toISOString(),category,amount,organization);});
          if(category!=='business'){const member=db.prepare('SELECT m.*,u.email FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.payment_reference=?').get(reference);await sendActivation(member);}
          return json(201,{paymentReference:reference,swishNumber,fee:amount,category,season});
        }
        if(path==='/api/auth/activate'&&method==='POST'){
          rate(req,'activate',20);const token=text(body.token,20,100),pass=password(body.password);const row=db.prepare("SELECT * FROM tokens WHERE token_hash=? AND kind='activation' AND expires_at>?").get(digest(token),Date.now());if(!row)fail(400,'Länken är ogiltig eller har gått ut. Be VDK om en ny aktiveringslänk.');
          const membership=db.prepare("SELECT * FROM memberships WHERE id=? AND status NOT IN ('rejected','expired')").get(row.membership_id);if(!membership)fail(400,'Medlemskapet kan inte aktiveras.');
          transaction(db,()=>{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(pass),row.user_id);if(membership.paid&&membership.status==='approved')db.prepare("UPDATE memberships SET status='active' WHERE id=?").run(row.membership_id);db.prepare("INSERT OR IGNORE INTO roles VALUES (?,'MEMBER')").run(row.user_id);db.prepare('DELETE FROM tokens WHERE user_id=?').run(row.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(row.user_id);});return json(200,{ok:true});
        }
        if(path==='/api/auth/login'&&method==='POST'){
          rate(req,'login',20);const mail=email(body.email);if(typeof body.password!=='string'||!body.password.length||body.password.length>256)fail(400,'Ange ditt lösenord.');const pass=body.password;const row=db.prepare('SELECT * FROM users WHERE email=?').get(mail);const valid=verifyPassword(pass,row?.password_hash||dummyHash);if(!row||!valid)fail(401,'Fel e-postadress eller lösenord.');
          db.prepare("INSERT OR IGNORE INTO match_members(match_id,user_id,colleague) SELECT r.match_id,?,COALESCE((SELECT name FROM match_referees other WHERE other.match_id=r.match_id AND other.referee_id!=r.referee_id LIMIT 1),'') FROM match_referees r WHERE r.normalized_name=?").run(row.id,row.name.normalize('NFC').trim().replace(/\s+/g,' ').toLocaleLowerCase('sv-SE'));const token=newToken();db.prepare('DELETE FROM sessions WHERE expires_at<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES (?,?,?)').run(digest(token),row.id,Date.now()+8*60*60*1000);res.setHeader('Set-Cookie',`vdk_session=${token}; HttpOnly; Path=/api; SameSite=Lax; Max-Age=28800${secure?'; Secure':''}`);return json(200,{user:publicUser(db,row.id,season)});
        }
        if(path==='/api/auth/logout'&&method==='POST'){const match=(req.headers.cookie||'').match(/(?:^|;\s*)vdk_session=([A-Za-z0-9_-]+)/);if(match)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(digest(match[1]));res.setHeader('Set-Cookie',`vdk_session=; HttpOnly; Path=/api; SameSite=Lax; Max-Age=0${secure?'; Secure':''}`);return json(200,{ok:true});}
        if(path==='/api/auth/request-reset'&&method==='POST'){
          rate(req,'reset',10);const mail=email(body.email);if(!mailReady)fail(503,'E-posttjänsten är inte ansluten ännu.');const row=db.prepare('SELECT id,password_hash FROM users WHERE email=?').get(mail);if(row?.password_hash){const token=newToken();db.prepare("INSERT INTO tokens(token_hash,user_id,kind,expires_at) VALUES (?,?,'reset',?)").run(digest(token),row.id,Date.now()+60*60*1000);try{await mailer({to:mail,subject:'Återställ ditt VDK-lösenord',html:`<p><a href="${escapeHtml(origin)}/#/nytt-losenord?token=${token}">Välj ett nytt lösenord</a></p><p>Länken gäller i en timme. Har du inte bett om den kan du bortse från meddelandet.</p>`});}catch(e){db.prepare('DELETE FROM tokens WHERE token_hash=?').run(digest(token));throw e;}}return json(200,{ok:true});
        }
        if(path==='/api/auth/reset'&&method==='POST'){rate(req,'reset-token',20);const token=text(body.token,20,100),pass=password(body.password);const row=db.prepare("SELECT * FROM tokens WHERE token_hash=? AND kind='reset' AND expires_at>?").get(digest(token),Date.now());if(!row)fail(400,'Återställningslänken är ogiltig eller har gått ut.');transaction(db,()=>{db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(hashPassword(pass),row.user_id);db.prepare('DELETE FROM tokens WHERE user_id=?').run(row.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(row.user_id);});return json(200,{ok:true});}
        if(path==='/api/profile/photo'&&method==='POST'){
          const u=auth(req);rate(req,'profile-photo',10);
          if(body.remove===true){db.prepare('DELETE FROM profile_photos WHERE user_id=?').run(u.id);return json(200,{ok:true});}
          if(!['image/png','image/jpeg'].includes(body.mime)||typeof body.data!=='string'||!body.data.length||!/^[A-Za-z0-9+/]+={0,2}$/.test(body.data))fail(400,'Välj en PNG- eller JPEG-bild.');
          const bytes=Buffer.from(body.data,'base64');if(bytes.length>2*1024*1024)fail(413,'Bilden får vara högst 2 MB.');
          const png=bytes.length>45&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))&&bytes.toString('ascii',12,16)==='IHDR'&&bytes.toString('ascii',bytes.length-8,bytes.length-4)==='IEND';
          const jpeg=bytes.length>20&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255&&bytes[bytes.length-2]===255&&bytes[bytes.length-1]===217;
          if(!(body.mime==='image/png'?png:jpeg))fail(400,'Filen är inte en giltig PNG- eller JPEG-bild.');
          db.prepare('INSERT INTO profile_photos VALUES (?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET mime=excluded.mime,data=excluded.data,updated_at=excluded.updated_at').run(u.id,body.mime,bytes,new Date().toISOString());return json(200,{ok:true});
        }
        if(path==='/api/profile/photo'&&method==='GET'){const u=auth(req);const photo=db.prepare('SELECT mime,data FROM profile_photos WHERE user_id=?').get(u.id);if(!photo)fail(404,'Ingen profilbild uppladdad.');res.writeHead(200,{'Content-Type':photo.mime,'Cache-Control':'no-store','Content-Security-Policy':"default-src 'none'"});return res.end(Buffer.from(photo.data));}
        if(path.startsWith('/api/messages')){
 const u=requireMembership(req);
 if(path==='/api/messages/unread'&&method==='GET')return json(200,{unread:unreadMessages(db,u.id)});
 if(path==='/api/messages'&&method==='GET')return json(200,{members:messageDirectory(db,u.id,season),threads:messageThreads(db,u.id),unread:unreadMessages(db,u.id),emailEnabled:db.prepare('SELECT email_enabled FROM message_preferences WHERE user_id=?').get(u.id)?.email_enabled!==0});
 if(path==='/api/messages/preferences'&&method==='POST'){if(typeof body.emailEnabled!=='boolean')fail(400,'Välj om mejlavisering ska vara på eller av.');db.prepare('INSERT OR REPLACE INTO message_preferences VALUES(?,?)').run(u.id,body.emailEnabled?1:0);if(!body.emailEnabled)db.prepare('DELETE FROM message_email_queue WHERE recipient_id=?').run(u.id);return json(200,{ok:true});}
 const thread=path.match(/^\/api\/messages\/thread\/(\d+)$/);
 if(thread&&method==='GET'){const peer=Number(thread[1]),member=db.prepare('SELECT id,name FROM users WHERE id=?').get(peer);if(peer===u.id||!member||(!messageDirectory(db,u.id,season).some(m=>m.id===peer)&&!db.prepare('SELECT 1 FROM direct_messages WHERE (sender_id=? AND recipient_id=?) OR (sender_id=? AND recipient_id=?)').get(u.id,peer,peer,u.id)))fail(404,'Konversationen finns inte.');const before=url.searchParams.get('before');if(before&&!/^\d+$/.test(before))fail(400,'Ogiltig sidgräns.');return json(200,{peer:member,...conversation(db,u.id,peer,before?Number(before):undefined)});}
 if(path==='/api/messages/read'&&method==='POST'){if(!Number.isSafeInteger(body.peerId)||!Number.isSafeInteger(body.throughId)||body.throughId<1)fail(400,'Ogiltigt meddelande.');db.prepare('UPDATE direct_messages SET read_at=? WHERE sender_id=? AND recipient_id=? AND id<=? AND read_at IS NULL').run(new Date().toISOString(),body.peerId,u.id,body.throughId);return json(200,{ok:true,unread:unreadMessages(db,u.id)});}
 if(path==='/api/messages'&&method==='POST'){rate(req,'messages-'+u.id,60);const recipient=body.recipientId;if(!Number.isSafeInteger(recipient)||!messageDirectory(db,u.id,season).some(m=>m.id===recipient))fail(400,'Välj en medlem med aktivt konto.');const content=text(body.message,1,4000);if(!content)fail(400,'Skriv ett meddelande.');const clientId=text(body.clientId,20,80),prior=db.prepare('SELECT id,recipient_id,body FROM direct_messages WHERE sender_id=? AND client_id=?').get(u.id,clientId);if(prior){if(prior.recipient_id!==recipient||prior.body!==content)fail(409,'Samma meddelandeidentitet har redan använts.');return json(200,{ok:true,id:prior.id});}
 const result=db.transaction(()=>{const row=db.prepare('INSERT INTO direct_messages(sender_id,recipient_id,body,client_id,created_at) VALUES(?,?,?,?,?)').run(u.id,recipient,content,clientId,new Date().toISOString());if(db.prepare('SELECT email_enabled FROM message_preferences WHERE user_id=?').get(recipient)?.email_enabled!==0){const sent=db.prepare('SELECT sent_at FROM message_email_sent WHERE user_id=?').get(recipient);db.prepare('INSERT OR IGNORE INTO message_email_queue(recipient_id,next_attempt,notification_key) VALUES(?,?,?)').run(recipient,Math.max(Date.now(),(sent?.sent_at||0)+15*60000),newToken());}return row;});await options.onMessagesQueued?.();return json(201,{ok:true,id:Number(result.lastInsertRowid)});
 }
 fail(404,'Funktionen finns inte.');
}
        if(path==='/api/me'&&method==='GET')return json(200,{user:auth(req)});
        if(path==='/api/membership'&&method==='GET'){const u=auth(req);return json(200,{memberships:db.prepare('SELECT season,status,paid,category,amount,organization FROM memberships WHERE user_id=? ORDER BY season DESC').all(u.id),coachApplication:db.prepare('SELECT status FROM coach_applications WHERE user_id=?').get(u.id)||null});}
        if(path==='/api/dashboard'&&method==='GET'){const u=auth(req);return json(200,dashboard(db,u,season,swishNumber));}
        if(path==='/api/coachings/viewed'&&method==='POST'){const u=requireMembership(req);const id=Number(body.id);if(!db.prepare("SELECT 1 FROM coachings c JOIN matches m ON m.id=c.match_id WHERE c.id=? AND c.member_id=? AND c.status='published' AND m.excluded=0 AND datetime(m.starts_at)<=datetime('now')").get(id,u.id))fail(404,'Coachningen finns inte.');db.prepare('INSERT INTO coaching_views VALUES(?,?,?) ON CONFLICT(user_id,coaching_id) DO UPDATE SET viewed_at=excluded.viewed_at').run(u.id,id,new Date().toISOString());return json(200,{ok:true});}
        if(path==='/api/commented-matches'&&method==='GET'){requireMembership(req);return json(200,commentedMatches(db,url.searchParams));}
 const commentsPath=path.match(/^\/api\/matches\/(\d+)\/comments(?:\/(\d+)\/delete)?$/);
 if(commentsPath){const u=requireMembership(req),matchId=Number(commentsPath[1]),m=db.prepare('SELECT * FROM matches WHERE id=? AND excluded=0').get(matchId);if(!m)fail(404,'Matchen finns inte.');const own=Date.parse(m.starts_at)<=Date.now()&&!!db.prepare('SELECT 1 FROM match_members WHERE match_id=? AND user_id=?').get(matchId,u.id);
 if(method==='GET'&&!commentsPath[2])return json(200,{match:m,canComment:own,comments:db.prepare('SELECT c.id,c.user_id,c.body,c.created_at,c.updated_at,u.name FROM match_comments c JOIN users u ON u.id=c.user_id WHERE c.match_id=? ORDER BY c.created_at,c.id').all(matchId)});
 if(method==='POST'&&commentsPath[2]){const comment=db.prepare('SELECT user_id FROM match_comments WHERE id=? AND match_id=?').get(Number(commentsPath[2]),matchId);if(!comment)fail(404,'Kommentaren finns inte.');if(comment.user_id!==u.id&&!u.roles.includes('ADMIN'))fail(403,'Du kan bara ta bort din egen kommentar.');db.prepare('DELETE FROM match_comments WHERE id=? AND match_id=?').run(Number(commentsPath[2]),matchId);return json(200,{ok:true});}
 if(method==='POST'){if(!own)fail(403,'Du kan bara kommentera matcher du själv har dömt.');rate(req,'match-comment-'+u.id,60);const content=text(body.comment,1,4000);if(!content)fail(400,'Skriv en kommentar.');const now=new Date().toISOString();db.prepare('INSERT INTO match_comments(match_id,user_id,body,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(match_id,user_id) DO UPDATE SET body=excluded.body,updated_at=excluded.updated_at').run(matchId,u.id,content,now,now);return json(200,{ok:true});}
 fail(405,'Metoden stöds inte.');
 }
        if(path==='/api/matches'&&method==='GET'){const u=requireMembership(req);return json(200,{matches:db.prepare('SELECT m.*,mm.colleague,(SELECT count(*) FROM penalties p WHERE p.match_id=m.id) AS penalty_count,(SELECT count(*) FROM match_comments c WHERE c.match_id=m.id) AS comment_count FROM matches m JOIN match_members mm ON mm.match_id=m.id WHERE mm.user_id=? AND m.excluded=0 ORDER BY m.starts_at DESC').all(u.id)});}
        if(path==='/api/regional-statistics'&&method==='GET'){requireMembership(req);const selected=url.searchParams.get('season')||'2025/26';return json(200,{...statistics(db,{season:selected,regional:true,colleague:'',team:url.searchParams.get('team')||'',against:url.searchParams.get('against')==='true',competition:url.searchParams.get('competition')||'',referee:url.searchParams.get('referee')||'',coReferee:url.searchParams.get('coReferee')||'',code:url.searchParams.get('code')||''}),seasons:db.prepare('SELECT DISTINCT season FROM matches WHERE excluded=0 ORDER BY season DESC').all().map(x=>x.season),referees:db.prepare('SELECT DISTINCT referee_id AS id,name FROM match_referees ORDER BY name').all(),penaltyTypes:db.prepare("SELECT code AS id,min(category) AS name FROM penalties WHERE code!='' GROUP BY code ORDER BY code").all(),allTeams:db.prepare("SELECT DISTINCT home_team_id AS id,home AS name FROM matches WHERE home_team_id!='' UNION SELECT DISTINCT away_team_id AS id,away AS name FROM matches WHERE away_team_id!='' ORDER BY name").all(),allCompetitions:db.prepare('SELECT DISTINCT competition_name AS name FROM matches ORDER BY name').all().map(x=>x.name),lastUpdate:db.prepare('SELECT finished_at,status FROM sync_runs WHERE finished_at IS NOT NULL ORDER BY id DESC LIMIT 1').get()||null});}
        if(path==='/api/statistics'&&method==='GET'){const u=requireMembership(req);const selected=url.searchParams.get('season')||season;return json(200,{lastUpdate:db.prepare('SELECT finished_at,status FROM sync_runs WHERE finished_at IS NOT NULL ORDER BY id DESC LIMIT 1').get()||null,...statistics(db,{season:selected,userId:u.id,colleague:url.searchParams.get('colleague')||'',team:url.searchParams.get('team')||'',against:url.searchParams.get('against')==='true',competition:url.searchParams.get('competition')||'',code:url.searchParams.get('code')||''}),penaltyTypes:db.prepare("SELECT p.code AS id,min(p.category) AS name FROM penalties p JOIN matches m ON m.id=p.match_id JOIN match_members mm ON mm.match_id=m.id WHERE mm.user_id=? AND m.excluded=0 AND p.code!='' GROUP BY p.code ORDER BY name").all(u.id),seasons:db.prepare('SELECT DISTINCT m.season FROM matches m JOIN match_members mm ON mm.match_id=m.id WHERE mm.user_id=? AND m.excluded=0 ORDER BY m.season DESC').all(u.id).map(x=>x.season),colleagues:db.prepare("SELECT DISTINCT mm.colleague FROM match_members mm JOIN matches m ON m.id=mm.match_id WHERE mm.user_id=? AND (m.season=? OR ?='all') AND mm.colleague!='' ORDER BY mm.colleague").all(u.id,selected,selected).map(x=>x.colleague)});}
        const coached=coachingAction({db,path,method,body,req,auth,requireMembership,fail,season,transaction,audit});if(coached)return json(coached.status,coached.data);
        if(path==='/api/coach-applications'&&method==='POST'){const u=requireMembership(req);const motivation=text(body.motivation,10,3000);if(getRoles(db,u.id).includes('VIDEO_COACH'))fail(409,'Du är redan videocoach.');if(db.prepare('SELECT 1 FROM coach_applications WHERE user_id=?').get(u.id))fail(409,'Du har redan skickat en ansökan.');db.prepare('INSERT INTO coach_applications(user_id,motivation) VALUES (?,?)').run(u.id,motivation);return json(201,{ok:true});}
        let match;
        if(path.startsWith('/api/admin/')){
          const admin=auth(req,'ADMIN');
          if(path==='/api/admin/members'&&method==='GET')return json(200,{canGrantAdmin:canGrantAdmin(admin,ownerAdminEmail),applications:db.prepare('SELECT m.*,u.name,u.email FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.season=? ORDER BY m.id DESC').all(season),members:db.prepare('SELECT id,name,email FROM users ORDER BY name').all().map(u=>({...u,roles:getRoles(db,u.id),canCoach:hasMembership(db,u.id,season)||getRoles(db,u.id).includes('ADMIN')}))});
          if((match=path.match(/^\/api\/admin\/applications\/(\d+)\/payment$/))&&method==='POST'){const m=db.prepare("SELECT * FROM memberships WHERE id=? AND season=? AND status='pending'").get(Number(match[1]),season);if(!m)fail(404,'Ansökan hittades inte.');db.prepare('UPDATE memberships SET paid=1,paid_at=?,paid_by=? WHERE id=?').run(new Date().toISOString(),admin.id,m.id);audit(db,admin.id,'payment_verified',m.id);return json(200,{ok:true});}
          if((match=path.match(/^\/api\/admin\/applications\/(\d+)\/approve$/))&&method==='POST'){const member=db.prepare("SELECT m.*,u.email,u.password_hash FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.id=? AND m.season=? AND m.status IN ('pending','approved')").get(Number(match[1]),season);if(!member)fail(404,'Ansökan hittades inte.');if(!member.paid)fail(409,'Verifiera betalningen före godkännande.');if(member.category==='business'){transaction(db,()=>{db.prepare("UPDATE memberships SET status='active',approved_at=? WHERE id=?").run(new Date().toISOString(),member.id);audit(db,admin.id,'business_gift_confirmed',member.id);});return json(200,{ok:true,donation:true});}transaction(db,()=>{db.prepare("UPDATE memberships SET status=?,approved_at=? WHERE id=?").run(member.password_hash?'active':'approved',new Date().toISOString(),member.id);audit(db,admin.id,'membership_approved',member.id);});if(!member.password_hash)await sendActivation(member);return json(200,{ok:true});}
          if((match=path.match(/^\/api\/admin\/applications\/(\d+)\/close$/))&&method==='POST'){const membership=db.prepare('SELECT * FROM memberships WHERE id=? AND season=?').get(Number(match[1]),season);if(!membership)fail(404,'Medlemskapet hittades inte.');if(membership.user_id===admin.id)fail(400,'Du kan inte avsluta ditt eget administratörsmedlemskap.');transaction(db,()=>{db.prepare("UPDATE memberships SET status='expired' WHERE id=?").run(membership.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(membership.user_id);db.prepare('DELETE FROM tokens WHERE membership_id=?').run(membership.id);audit(db,admin.id,'membership_closed',membership.id);});return json(200,{ok:true});}
          if(path==='/api/admin/coach-applications'&&method==='GET')return json(200,{applications:db.prepare('SELECT c.*,u.name FROM coach_applications c JOIN users u ON u.id=c.user_id ORDER BY c.id DESC').all()});
          if((match=path.match(/^\/api\/admin\/coach-applications\/(\d+)$/))&&method==='POST'){if(!['approved','rejected'].includes(body.status))fail(400,'Ogiltigt beslut.');const row=db.prepare("SELECT * FROM coach_applications WHERE id=? AND status='pending'").get(Number(match[1]));if(!row)fail(404,'Ansökan hittades inte.');if(body.status==='approved'&&!hasMembership(db,row.user_id,season))fail(409,'Coachen måste vara aktiv medlem.');transaction(db,()=>{db.prepare('UPDATE coach_applications SET status=? WHERE id=?').run(body.status,row.id);if(body.status==='approved')db.prepare("INSERT OR IGNORE INTO roles VALUES (?,'VIDEO_COACH')").run(row.user_id);audit(db,admin.id,'coach_application_'+body.status,row.id);});return json(200,{ok:true});}
          if((match=path.match(/^\/api\/admin\/applications\/(\d+)\/reactivate$/))&&method==='POST'){reactivateMembership(db,Number(match[1]),season,admin,fail,transaction,audit);return json(200,{ok:true});}
          if((match=path.match(/^\/api\/admin\/members\/(\d+)\/grant-admin$/))&&method==='POST'){grantAdmin(db,Number(match[1]),admin,ownerAdminEmail,season,fail,transaction,audit);return json(200,{ok:true});}
          if(path==='/api/admin/statistics'&&method==='GET'){const selected=url.searchParams.get('season')||season;return json(200,{statistics:{...statistics(db,{season:selected}),members:db.prepare("SELECT count(*) AS n FROM memberships WHERE season=? AND category='active' AND status='active' AND paid=1").get(selected).n}});}
          if(path==='/api/admin/import-match'&&method==='POST'){try{const id=importMatch(db,body);audit(db,admin.id,'match_imported',id);return json(201,{id});}catch(e){fail(400,e.message);}}
        }
        fail(404,'Funktionen hittades inte.');
      }
      fail(404,'Sidan hittades inte.');
    }catch(e){const status=e.status|| (e.code==='ENOENT'?404:500);if(status===500)console.error('VDK request failed:',e.message);json(status,{error:status===500?'Ett serverfel inträffade. Försök igen.':e.message});}
  };return {handler,db};
}
