import {deliverMessageEmail} from './messages.mjs';
import {startAvailability,runAvailability,dailyThree} from './availability.mjs';
import {planSync,runSyncBatch,isSwedishMondayThree} from './sync.mjs';
import {DurableObject} from 'cloudflare:workers';
import {initializeStore} from './store.mjs';
import {createApp} from './api.mjs';
export class VdkDatabase extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.env=env;const sql=ctx.storage.sql;this.db={exec:q=>sql.exec(q),transaction:fn=>ctx.storage.transactionSync(fn),prepare:q=>({all:(...p)=>[...sql.exec(q,...p)],get:(...p)=>[...sql.exec(q,...p)][0],run:(...p)=>{sql.exec(q,...p);return {lastInsertRowid:[...sql.exec('SELECT last_insert_rowid() AS id')][0].id,changes:[...sql.exec('SELECT changes() AS n')][0].n};}})};initializeStore(this.db);}
 async startSync(window){return planSync(this,window);}
 async startAvailability(day){return startAvailability(this,day);}
 async alarm(){const emailed=await deliverMessageEmail(this);if(!emailed){if(this.db.prepare('SELECT 1 FROM availability_plan').get())await runAvailability(this);else await runSyncBatch(this);}const queued=this.db.prepare('SELECT min(next_attempt) AS next FROM message_email_queue').get()?.next;if(this.db.prepare('SELECT 1 FROM availability_plan').get()||this.db.prepare('SELECT 1 FROM regional_sync_plan').get())await this.ctx.storage.setAlarm(Date.now()+1000);else if(queued!=null)await this.ctx.storage.setAlarm(Math.max(Date.now()+1000,queued));}
 async fetch(request){const u=new URL(request.url);if(u.pathname.startsWith('/internal/')){
 if(!this.env.IMPORT_SECRET||request.headers.get('Authorization')!=='Bearer '+this.env.IMPORT_SECRET)return Response.json({error:'Åtkomst nekad'},{status:403});
 if(u.pathname==='/internal/availability'&&request.method==='POST')return Response.json(await this.startAvailability());
 if(u.pathname==='/internal/availability'&&request.method==='GET'){const p=this.db.prepare('SELECT state FROM availability_plan WHERE id=1').get();const s=p?JSON.parse(p.state):null;return Response.json(s?{planning:s.cursor,totalCompetitions:s.competitions?.length,jobs:s.jobs.length,position:s.position,errors:s.errors.length}: {complete:true});}
 if(u.pathname==='/internal/sync'&&request.method==='POST')return Response.json(await this.startSync('manual-'+new Date().toISOString()));
 if(u.pathname==='/internal/status'&&request.method==='GET'){const plan=this.db.prepare('SELECT window,position,errors,started_at,jobs FROM regional_sync_plan WHERE id=1').get();let sync=null;if(plan){const jobs=JSON.parse(plan.jobs);const {jobs:raw,...progress}=plan;sync={...progress,totalJobs:Array.isArray(jobs)?(this.db.prepare('SELECT coalesce((SELECT position+1 FROM stats_sync_jobs WHERE window=? ORDER BY position DESC LIMIT 1),0) AS n').get(plan.window).n||jobs.length):(jobs.queued||jobs.jobs.length),...(!Array.isArray(jobs)?{competitionPosition:jobs.cursor,totalCompetitions:jobs.competitions.length}:{})};}return Response.json({sync,lastRun:this.db.prepare('SELECT * FROM sync_runs ORDER BY id DESC LIMIT 1').get()||null,matches:this.db.prepare('SELECT season,count(*) AS count FROM matches WHERE excluded=0 GROUP BY season').all()});}
 if(u.pathname!=='/internal/import'||request.method!=='POST')return Response.json({error:'Funktionen hittades inte'},{status:404});
 const body=await request.json();if(!Array.isArray(body.statements)||body.statements.length>300)return Response.json({error:'Ogiltig import'},{status:400});this.db.transaction(()=>{for(const s of body.statements){if(typeof s.sql!=='string'||!Array.isArray(s.params))throw Error('Ogiltig import');this.db.prepare(s.sql).run(...s.params);}});return Response.json({ok:true,count:body.statements.length});}
 const {handler}=this.app||(this.app=createApp({db:this.db,env:this.env,onMessagesQueued:()=>this.ctx.storage.setAlarm(Date.now()+1000),origin:this.env.PUBLIC_ORIGIN||u.origin}));const headers=new Headers();let status=200,body=null;const req={url:u.pathname+u.search,method:request.method,headers:Object.fromEntries(request.headers),socket:{remoteAddress:request.headers.get('CF-Connecting-IP')||'unknown'},async *[Symbol.asyncIterator](){yield Buffer.from(await request.arrayBuffer());}};const res={setHeader:(k,v)=>{headers.delete(k);for(const value of Array.isArray(v)?v:[v])headers.append(k,value);},writeHead:(s,h)=>{status=s;if(h)for(const[k,v]of Object.entries(h))headers.set(k,v);},end:b=>{body=b??null;}};await handler(req,res);return new Response(body,{status,headers});}
}
export default{async scheduled(controller,env,ctx){const day=dailyThree(controller.scheduledTime);if(day)ctx.waitUntil(env.VDK_DB.get(env.VDK_DB.idFromName('vdk-production')).startAvailability(day));const window=isSwedishMondayThree(controller.scheduledTime);if(window)ctx.waitUntil(env.VDK_DB.get(env.VDK_DB.idFromName('vdk-production')).startSync(window));},async fetch(request,env){const u=new URL(request.url);if(u.pathname==='/api/settings'&&request.method==='GET')return Response.json({season:env.SEASON||'2026/27',fee:100,applicationsOpen:!!(env.SWISH_NUMBER&&env.EMAIL_ENABLED==='true'&&env.RESEND_API_KEY&&env.EMAIL_FROM)},{headers:{'Cache-Control':'no-store'}});if(u.pathname.startsWith('/api/')||u.pathname.startsWith('/internal/')){const id=env.VDK_DB.idFromName('vdk-production');try{return await env.VDK_DB.get(id).fetch(request);}catch(error){if(/Exceeded allowed rows (read|written)/i.test(error.message||''))return Response.json({error:'Medlemstjänsten är tillfälligt pausad på grund av databasens kapacitetsgräns. Din begäran har inte kunnat genomföras. Försök igen senare.'},{status:503,headers:{'Cache-Control':'no-store'}});throw error;}}if(decodeURIComponent(u.pathname)==='/member-rules'||decodeURIComponent(u.pathname).startsWith('/member-rules/')){const check=await env.VDK_DB.get(env.VDK_DB.idFromName('vdk-production')).fetch(new Request(new URL('/api/rules/access',u),{headers:request.headers}));if(!check.ok){if(check.status===401)return Response.redirect(new URL('/#/logga-in',u),302);return new Response('Fullversionen kräver ett betalt och godkänt medlemskap. Kontakta VDK om ditt medlemskap behöver kontrolleras.',{status:check.status,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}})};if(u.pathname==='/member-rules')return Response.redirect(new URL('/member-rules/',u),302);const protectedResponse=await env.ASSETS.fetch(request);const protectedHeaders=new Headers(protectedResponse.headers);protectedHeaders.set('Cache-Control','private, no-store');protectedHeaders.set('X-Content-Type-Options','nosniff');return new Response(protectedResponse.body,{status:protectedResponse.status,headers:protectedHeaders});}const r=await env.ASSETS.fetch(request);const headers=new Headers(r.headers);headers.set('X-Content-Type-Options','nosniff');headers.set('Referrer-Policy','no-referrer');headers.set('Cache-Control','no-cache');return new Response(r.body,{status:r.status,headers});}};

