/* Dedicated advanced bank for VDK Regelgenerator 2026.
   Advanced scenarios describe observable match events; the referee must make the classification. */
(() => {
"use strict";
const Q=[
{id:8001,c:"Avvaktande utvisning",level:"advanced",q:"Röd 14 ska utvisas. Blå har fortsatt kontroll över bollen och domarna avvaktar utvisningen. En passning från Blå 8 träffar Röd 14:s klubblad och studsar direkt tillbaka till Blå 8, som fortsätter anfallet. Vad gör domarna?",a:["Fortsätter avvakta eftersom Röd varken kontrollerar eller spelar bollen på ett kontrollerat sätt","Stoppar spelet vid varje beröring av Röd","Avbryter och dömer tekning","Stryker utvisningen"],x:0,r:"Fortsätt avvakta.",e:"Avvaktande utvisning pågår tills felande lag kontrollerar eller spelar bollen på ett kontrollerat sätt. En ren studs på klubbladet behöver inte uppfylla det kriteriet.",s:"Regel 602",t:"Använd regelbokens kriterium: kontrollerar eller spelar bollen på ett kontrollerat sätt."},
{id:8002,c:"Avvaktande utvisning",level:"advanced",q:"Röd har en avvaktande utvisning. Blå kontrollerar bollen. Blå 7 slår en passning bakåt som Röd 9 tar emot, får under kontroll och börjar föra framåt. När ska spelet stoppas?",a:["När Röd 9 kontrollerar bollen","När Blå 7 slår passningen","Först när Röd 9 passar eller skjuter","Spelet ska fortsätta tills bollen lämnar planen"],x:0,r:"När Röd 9 kontrollerar bollen.",e:"Spelet ska stoppas när felande lag kontrollerar eller spelar bollen på ett kontrollerat sätt.",s:"Regel 602",t:"Kontroll är tillräckligt; ytterligare passning eller skott krävs inte."},
{id:8003,c:"Straffslag",level:"advanced",q:"Blå 11 är fri centralt med bollen under kontroll och endast målvakten framför sig. Röd 4 kommer snett bakifrån och slår undan Blå 11:s klubba så att avslutet omöjliggörs. Vilken del av situationen är avgörande för valet mellan frislag och straffslag?",a:["Om en målsituation avbryts eller förhindras att uppstå genom försvarande lags frislag- eller utvisningsbelagda förseelse","Om kontakten sker på offensiv planhalva","Om Röd 4 träffar bollen efteråt","Om Blå 11 faller till golvet"],x:0,r:"Bedöm om en målsituation avbryts eller förhindras.",e:"Straffslag ska dömas när en målsituation avbryts eller förhindras att uppstå på grund av försvarande lags frislag- eller utvisningsbelagda förseelse. Domarna avgör vad som ska anses som en målsituation.",s:"Regel 510.1",t:"Använd termen målsituation; regelboken använder inte 'klar målsituation' här."},
{id:8004,c:"Målvakt",level:"advanced",q:"Målvakten står med båda fötterna utanför målområdet och fångar bollen med händerna. Bollen befinner sig samtidigt helt innanför målområdets gräns. Vad ska domarna bedöma?",a:["Om målvakten enligt regelbokens kriterier helt har lämnat målområdet","Endast bollens position","Endast var målvaktens händer befinner sig","Att en räddning alltid innebär spela vidare"],x:0,r:"Målvaktens regeltekniska position måste bedömas.",e:"En målvakt som under spel helt lämnar målområdet ska bedömas som utespelare utan klubba. Det är därför målvaktens position, inte enbart bollens, som måste fastställas.",s:"Regel 303.2",t:"Separera bollens position från målvaktens position."},
{id:8005,c:"Målvakt",level:"advanced",q:"Blå 5 spelar avsiktligt bollen bakåt mot sin målvakt. Målvakten möter bollen helt utanför målområdet och spelar den vidare med foten utan att använda hand eller arm. Domslut?",a:["Spela vidare; målvakten bedöms där som utespelare utan klubba och fotspel är tillåtet","Frislag för otillåten passning till målvakt oavsett hur bollen spelas","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"En målvakt som helt lämnat målområdet bedöms som utespelare utan klubba. Förseelsen vid avsiktlig passning till egen målvakt avser mottagning med händer eller armar i målområdet.",s:"Regel 303.2 och 507.17",t:"Fastställ först målvaktens position och därefter hur bollen spelas."},
{id:8006,c:"Målvaktsområdet",level:"advanced",q:"Vid ett inspel står en anfallare utanför målvaktsområdet men har klubbladet inne i området. Ingen kroppsdel rör golvet i området. Bollen spelas förbi spelaren utan kontakt. Domslut enbart på grund av spelarens position?",a:["Spela vidare; endast klubban i målvaktsområdet innebär inte att utespelaren befinner sig där","Frislag till försvarande lag","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"En utespelare anses befinna sig i målvaktsområdet när någon del av kroppen rör golvet där. Endast klubban i området räcker inte.",s:"Regel 507.8",t:"Klubba och kropp behandlas olika i positionsbedömningen."},
{id:8007,c:"Målvaktsområdet",level:"advanced",q:"En försvarare försöker täcka ett inspel och sätter ned ena knät på linjen till målvaktsområdet. Bollen är spelbar framför mål. Hur ska spelarens position bedömas?",a:["Spelaren befinner sig i målvaktsområdet eftersom linjen tillhör området och en kroppsdel rör golvet där","Spelaren är utanför eftersom endast linjen berörs","Spelaren är utanför om bollen inte är i området","Positionen saknar alltid regelbetydelse för försvarare"],x:0,r:"Spelaren befinner sig i målvaktsområdet.",e:"Linjerna tillhör målvaktsområdet. När en kroppsdel rör golvet på linjen befinner sig utespelaren i området.",s:"Regel 507.8",t:"Linjen tillhör området."},
{id:8008,c:"Fördelsregel",level:"advanced",q:"Röd 8 utsätts för en frislagsbelagd förseelse i mittzonen men behåller kontroll över bollen och får omedelbart ett två-mot-ett-läge. Domarna bedömer att fortsatt spel innebär en större fördel än frislaget. Vad är korrekt?",a:["Tillämpa fördel och låt spelet fortsätta","Blås alltid direkt vid en frislagsbelagd förseelse","Låt spelet fortsätta endast om Röd gör mål","Döm tekning eftersom förseelsen redan skett"],x:0,r:"Tillämpa fördel.",e:"Vid frislagsbelagda förseelser ska fördelsregeln i största möjliga omfattning tillämpas när icke felande lag fortfarande kontrollerar bollen och fortsatt spel innebär en större fördel än frislag.",s:"Regel 506.1",t:"Jämför fortsatt spel med värdet av frislaget."},
{id:8009,c:"Fasta situationer",level:"advanced",q:"Ett inslag utförs ungefär en meter från korrekt plats. Bollen ligger still och det är inte uppenbart att utföraren försöker vinna en betydande fördel. Domarna upptäcker placeringen direkt efter tillslaget. Vad är korrekt åtgärd?",a:["Inslaget görs om från korrekt plats","Frislag till motståndarna","Mindre lagstraff på utföraren","Låt alltid spelet fortsätta"],x:0,r:"Inslaget görs om.",e:"Ett inslag eller frislag från fel ställe eller på rullande boll ska göras om. Den strängare bedömningen gäller när den fasta situationen utförs från uppenbart fel ställe för att vinna en betydande fördel.",s:"Regel 507.15",t:"Skilj omtag från uppenbart försök att vinna betydande fördel."},
{id:8010,c:"Avstånd",level:"advanced",q:"Vid frislag står en motståndare närmare än föreskrivet avstånd men försöker omedelbart inta korrekt avstånd. Utföraren slår frislaget snabbt och motståndaren ingriper inte. Vad måste domarna bedöma?",a:["Om spelaren försöker inta korrekt avstånd eller aktivt förhindrar eller försvårar frislaget","Att varje spelare inom tre meter automatiskt ska utvisas","Att frislaget alltid måste tas om","Att utförande lag förlorar frislaget när det slås snabbt"],x:0,r:"Bedöm spelarens agerande enligt avståndsregeln.",e:"Regelboken skiljer mellan en spelare som försöker inta korrekt avstånd och en spelare som aktivt bryter mot avståndsbestämmelsen. En fryst positionsbild räcker därför inte ensam.",s:"Regel 605, avstånd vid fast situation",t:"Bedöm beteendet i hela sekvensen."},
{id:8011,c:"Hög sving",level:"advanced",q:"Blå 3 gör en skottfint. Klubban förs över midjehöjd nära Röd 12, som riskerar att träffas. Ingen fysisk kontakt sker. Vad är den centrala regelbedömningen?",a:["Om en annan spelare är i närheten och riskerar att träffas av den höga svingen","Att ingen kontakt skedde och spelet därför alltid fortsätter","Om bollen var över knähöjd","Om Röd 12 faktiskt tappar balansen"],x:0,r:"Risken att en närvarande spelare träffas är central.",e:"Bestämmelsen om hög sving omfattar även skottfint. En hög sving är tillåten endast om ingen annan spelare är i närheten som riskerar att träffas.",s:"Regel 507.3",t:"Kontakt behöver inte inträffa."},
{id:8012,c:"Spel med kroppen",level:"advanced",q:"Röd 6 stoppar en boll med låret tydligt över knähöjd. Rörelsen är kontrollerad och bedöms inte som farlig. Vad döms?",a:["Spela vidare","Frislag för spel över knähöjd","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"Att stoppa bollen med låret räknas inte som spel över knähöjd så länge agerandet inte bedöms som farligt.",s:"Regel 507.4",t:"Regeltexten gör ett uttryckligt undantag för låret."},
{id:8013,c:"Trängning",level:"advanced",q:"Två spelare springer sida vid sida mot en lös boll. Blå 9 tränger undan Röd 5 på annat sätt än skuldra mot skuldra medan de är i kamp om bollen. Ingen högre påföljdsnivå är aktuell. Vad döms?",a:["Frislag","Spela vidare eftersom kontakten inte är hård","Mindre lagstraff automatiskt","Tekning"],x:0,r:"Frislag.",e:"När en spelare som har bollen under kontroll eller är i kamp om bollen på annat sätt än skuldra mot skuldra tränger undan en motståndare ska frislag dömas.",s:"Regel 507.6",t:"Kontaktens hårdhet är inte det enda kriteriet; typen av trängning är central."},
{id:8014,c:"Målvaktsutkast",level:"advanced",q:"Målvakten kastar bollen långt. Bollen träffar sargen på egen planhalva och passerar därefter mittlinjen i luften utan ytterligare beröring. Domslut?",a:["Spela vidare","Frislag för felaktigt målvaktsutkast","Tekning på mittlinjen","Inslag vid mittlinjen"],x:0,r:"Spela vidare.",e:"Förseelsen uppstår bara om hela bollen passerar mittlinjen utan att först röra golvet, sargen, en annan spelare eller en annan spelares utrustning.",s:"Regel 507.14",t:"Identifiera vad bollen berör före mittlinjen."},
{id:8015,c:"Målvaktsutkast",level:"advanced",q:"Målvakten kastar bollen så att hela bollen passerar mittlinjen utan att dessförinnan ha berört golvet, sargen, en annan spelare eller en annan spelares utrustning. En medspelare tar emot bollen på offensiv planhalva. Domslut?",a:["Frislag för felaktigt målvaktsutkast","Spela vidare eftersom en medspelare tar emot bollen","Tekning","Inslag"],x:0,r:"Frislag.",e:"Förseelsen är fullbordad när hela bollen passerar mittlinjen utan föregående tillåten beröring. En senare mottagning ändrar inte detta.",s:"Regel 507.14",t:"Bedöm händelserna i rätt tidsordning."},
{id:8016,c:"Målvakt",level:"advanced",q:"Målvakten får bollen under kontroll och lägger ned den efter två sekunder. Utan att någon annan spelare rör bollen tar målvakten upp den igen med händerna. Hur ska kontrolltiden bedömas?",a:["Målvakten bedöms ha haft bollen under kontroll hela tiden; nedläggningen startar inte automatiskt en ny tresekundersperiod","En ny tresekundersperiod börjar alltid","Målvakten får därefter hålla bollen obegränsat","Spelet stoppas för tekning när bollen läggs ned"],x:0,r:"Kontrollen fortsätter.",e:"Om målvakten lägger ner bollen och tar upp den igen bedöms målvakten ha bollen under kontroll hela tiden.",s:"Regel 507.16",t:"Följ regelbokens definition av kontroll."},
{id:8017,c:"Spel utan klubba",level:"advanced",q:"Blå 4 tappar klubban i egen zon. Innan klubban plockats upp sparkar Blå 4 en rullande boll till en fri medspelare. Vad döms?",a:["Mindre lagstraff eftersom Blå 4 deltar i spelet utan klubba","Spela vidare eftersom det är tillåtet att sparka bollen utan klubba","Frislag utan utvisning","Tekning"],x:0,r:"Mindre lagstraff.",e:"En utespelare som deltar i spelet utan klubba ska ådömas mindre lagstraff. Det avgörande är deltagandet i spelet, inte om aktionen lyckas.",s:"Regel 605, spel utan klubba",t:"Att klubban tappades oavsiktligt gör inte fortsatt deltagande med bollen tillåtet."},
{id:8018,c:"Utvisningar",level:"advanced",q:"En spelare håller fast en motståndare eller motståndarens klubba och saknar möjlighet att nå bollen, varigenom laget vinner en betydande fördel. Vilken påföljdsnivå är aktuell?",a:["Mindre lagstraff","Endast frislag","Större lagstraff automatiskt","Ingen åtgärd"],x:0,r:"Mindre lagstraff.",e:"Fasthållning ligger på mindre lagstraff när spelaren saknar möjlighet att nå bollen eller när laget vinner en betydande fördel genom förseelsen.",s:"Regel 605.2",t:"Jämför med frislagsnivån i 507.2."},
{id:8019,c:"Liggande spel",level:"advanced",q:"En spelare har båda knäna i golvet och spelar bollen med klubban. Laget vinner ingen betydande fördel. Vad döms?",a:["Frislag","Mindre lagstraff","Spela vidare","Större lagstraff"],x:0,r:"Frislag.",e:"Att kontrollera eller försöka spela bollen med båda knäna i golvet är frislagsbelagt. Om spelaren genom liggande eller sittande spel vinner en betydande fördel kan mindre lagstraff bli aktuellt.",s:"Regel 507.22 och 605.13",t:"Skilj grundförseelsen från betydande fördel."},
{id:8020,c:"Liggande spel",level:"advanced",q:"En spelare ligger eller sitter på golvet och spelar bollen så att det egna laget vinner en betydande fördel. Vilken påföljd ska dömas?",a:["Mindre lagstraff","Endast frislag","Spela vidare","Större lagstraff"],x:0,r:"Mindre lagstraff.",e:"När en spelare genom liggande eller sittande spel vinner en betydande fördel ska mindre lagstraff dömas.",s:"Regel 605.13",t:"Betydande fördel höjer här påföljden från grundnivån."},
{id:8021,c:"Fysiskt spel",level:"advanced",q:"En spelare tacklar en motståndare mot sargen. Domarna bedömer handlingen som vårdslös, men inte våldsam eller brutal. Vilken påföljdsnivå ska användas?",a:["Större lagstraff","Mindre lagstraff","Frislag endast","Matchstraff"],x:0,r:"Större lagstraff.",e:"Vårdslöst fysiskt spel ska bestraffas med större lagstraff. Våldsamt och brutalt spel ligger på andra nivåer enligt regelbokens klassificering.",s:"Regel 607, vårdslöst fysiskt spel",t:"Vårdslöst får aldrig blandas ihop med mindre lagstraff."},
{id:8022,c:"Straffslag",level:"advanced",q:"Under ett straffslag för spelaren bollen bakåt. Vad döms enligt straffslagsbestämmelserna?",a:["Straffslaget är felaktigt utfört; om det inte resulterar i mål återupptas spelet enligt reglerna för felaktigt straffslag","Spelet fortsätter eftersom bollen får föras bakåt","Nytt straffslag automatiskt","Mål godkänns alltid om bollen senare går in"],x:0,r:"Straffslaget är felaktigt utfört.",e:"Bollen ska föras framåt under straffslaget. Ett felaktigt utfört straffslag som inte resulterar i mål följs av den återstart som regelboken föreskriver.",s:"Regel 508 och 503.8",t:"Skilj själva utförandefelet från hur spelet återupptas."},
{id:8023,c:"Straffslag",level:"advanced",q:"Ett korrekt utfört straffslag träffar stolpen, därefter målvakten och går sedan in i mål utan att straffslagsskytten rör bollen igen. Vad döms?",a:["Mål","Tekning utan mål","Nytt straffslag","Frislag till försvarande lag"],x:0,r:"Mål.",e:"Sekvensen innehåller ingen otillåten andra beröring av straffslagsskytten. Om bollen på korrekt sätt passerar mållinjen ska målet godkännas.",s:"Regel 508 och 702",t:"Följ vem som faktiskt rör bollen efter stolpträffen."},
{id:8024,c:"Mål",level:"advanced",q:"Ett skott avlossas före slutsignalen men hela bollen passerar mållinjen först under eller efter signalen. Vad döms?",a:["Målet underkänns","Mål eftersom skottet avlossades före signalen","Mål om bollen redan var på väg mot mål","Domarna tillämpar fördel"],x:0,r:"Målet underkänns.",e:"Ett mål är felaktigt gjort när bollen passerar mållinjen under eller efter en signal.",s:"Regel 703.3",t:"Det är tidpunkten då bollen passerar mållinjen som är avgörande."},
{id:8025,c:"Mål",level:"advanced",q:"Målvakten kastar bollen. Den studsar i golvet på egen planhalva före mittlinjen och går därefter, utan någon frislags- eller utvisningsbelagd förseelse av anfallande lag, direkt in i motståndarnas mål. Vad döms?",a:["Mål","Frislag","Tekning","Målet underkänns eftersom bollen kastats av målvakten"],x:0,r:"Mål.",e:"Utkastet är korrekt eftersom bollen har rört golvet innan hela bollen passerar mittlinjen. Ett mål kan göras efter att bollen kastats av målvakten när övriga målkrav är uppfyllda.",s:"Regel 507.14 och 702.1",t:"Kontrollera både utkastets laglighet och målbestämmelsen."}
];
window.VDK_ADVANCED_QUESTIONS=Q;
})();