(() => {
  "use strict";
  const EXTRA_QUESTIONS = [
    {id:71,c:"Spelplan",n:false,q:"En hall har en spelplan som mäter 35 x 18 meter. Kan matchen spelas enligt regelbokens ordinarie minimimått utan dispens?",v:["En hall har en spelplan som mäter 35 x 18 meter. Kan matchen spelas enligt regelbokens ordinarie minimimått utan dispens?","Planen är 18 meter bred men bara 35 meter lång. Arrangören menar att bredden uppfyller minimikravet. Är planen ändå godkänd enligt grundregeln?","Curve ball: En rektangulär plan är 35,9 x 20 meter och allt annat är korrekt. Räcker det för regelbokens minimimått?"],a:["Nej, minsta tillåtna mått är 36 x 18 meter","Ja, eftersom bredden är 18 meter","Ja, om båda lagen accepterar","Ja, om sargen är IFF-märkt"],x:0,r:"Nej.",e:"Grundregeln anger 40 x 20 meter och minsta tillåtna mått 36 x 18 meter.",s:"Regel 101.1",t:"Båda minimimåtten måste vara uppfyllda."},
    {id:72,c:"Spelplan",n:false,q:"Hur stora ska målområdena vara?",v:["Hur stora ska målområdena vara?","Du mäter målområdet inför match. Vilka mått ska det ha inklusive linjer?","Curve ball: Ett målområde är 4 x 5 meter mätt inklusive linjer. Är storleken korrekt?"],a:["4 x 5 meter","2,5 x 1 meter","5 x 6 meter","3 x 4 meter"],x:0,r:"4 x 5 meter.",e:"Målområdena ska vara 4 x 5 meter och måtten inkluderar linjerna.",s:"Regel 102.3",t:"Blanda inte ihop målområdet med målvaktsområdet."},
    {id:73,c:"Spelplan",n:false,q:"Hur stora ska målvaktsområdena vara?",v:["Hur stora ska målvaktsområdena vara?","Inför match kontrollerar du den mindre rektangeln framför målet. Vilka mått ska den ha?","Curve ball: Någon påstår att målvaktsområdet är 4 x 5 meter. Vilket är rätt mått?"],a:["1 x 2,5 meter","4 x 5 meter","1,5 x 3 meter","2 x 3 meter"],x:0,r:"1 x 2,5 meter.",e:"Målvaktsområdet är det mindre området och ska mäta 1 x 2,5 meter inklusive linjer.",s:"Regel 102.4",t:"Linjerna ingår i måttet och tillhör området."},
    {id:74,c:"Spelplan",n:false,q:"Sargen går isär långt från bollen under pågående spel. Vad är huvudprincipen?",v:["Sargen går isär långt från bollen under pågående spel. Vad är huvudprincipen?","En sargsektion glider isär bakom spelet medan bollen kontrolleras på motsatt sida. Ska du blåsa omedelbart?","Curve ball: Sargen har gått isär, men bollen och spelarna är långt därifrån och ingen omedelbar fara finns. När ska spelet normalt stoppas?"],a:["Vänta normalt tills bollen kommer i närheten av det aktuella stället","Blås alltid omedelbart","Låt spelet fortsätta till nästa naturliga avblåsning oavsett var bollen går","Döm frislag till hemmalaget"],x:0,r:"Vänta tills spelet närmar sig.",e:"När sargen går isär ska spelet normalt inte stoppas förrän bollen kommer i närheten av platsen.",s:"Regel 201.2",t:"Skilj sarg som gått isär från en situation med omedelbar säkerhetsrisk."},
    {id:75,c:"Spelplan",n:false,q:"Vem ansvarar för att brister på spelplanen åtgärdas?",v:["Vem ansvarar för att brister på spelplanen åtgärdas?","Domarna hittar en brist före match. Vem har ansvaret att faktiskt åtgärda den?","Curve ball: Domarna inspekterar och påpekar en farlig detalj. Vems organisatoriska ansvar är det att den åtgärdas?"],a:["Arrangören","Domarna personligen","Bortalaget","Sekretariatet"],x:0,r:"Arrangören.",e:"Domarna inspekterar spelplanen, men arrangören ansvarar för att brister åtgärdas och att sargen hålls spelduglig.",s:"Regel 106.1",t:"Domarnas kontrollansvar och arrangörens åtgärdsansvar är olika saker."},
    {id:76,c:"Speltid",n:false,q:"När är en period slut om slutsignalen börjar ljuda medan bollen är på väg mot mål?",v:["När är en period slut om slutsignalen börjar ljuda medan bollen är på väg mot mål?","Ett skott lämnar klubban strax före slutsignalen men bollen passerar mållinjen efter att signalen börjat. Är perioden fortfarande igång?","Curve ball: Bollen är i luften när slutsignalen börjar. En halv sekund senare går den i mål. Vilken tidpunkt avslutar perioden?"],a:["Omedelbart när slutsignalen börjar ljuda","När bollen stannar","När domaren blåser","När sekretariatet stoppar klockan"],x:0,r:"När slutsignalen börjar ljuda.",e:"Perioden eller matchen är slut omedelbart när slutsignalen börjar ljuda.",s:"Regel 201.1",t:"Bedöm tidpunkten för målet mot när signalen börjar, inte när den slutar."},
    {id:77,c:"Speltid",n:false,q:"Vid effektiv speltid: när startas tiden igen efter en avblåsning?",v:["Vid effektiv speltid: när startas tiden igen efter en avblåsning?","Efter ett frislag har klockan stoppats. Ska den starta på domarens signal eller när bollen faktiskt spelas?","Curve ball: Domaren blåser igång ett frislag men spelaren väntar två sekunder innan bollen spelas. När ska matchklockan börja gå?"],a:["När bollen spelas","På domarens signal oavsett bollens rörelse","När spelaren ställer sig vid bollen","Tre sekunder efter signal"],x:0,r:"När bollen spelas.",e:"Effektiv speltid stoppas vid avblåsning och startas när bollen åter spelas.",s:"Regel 201.2",t:"Domarsignal och klockstart är inte alltid samma ögonblick."},
    {id:78,c:"Speltid",n:false,q:"En spelare ligger skadad men skadan verkar inte allvarlig och spelaren påverkar inte spelet. Ska domaren enligt huvudprincipen blåsa direkt?",v:["En spelare ligger skadad men skadan verkar inte allvarlig och spelaren påverkar inte spelet. Ska domaren enligt huvudprincipen blåsa direkt?","En spelare får ont och blir liggande nära sargen. Spelet fortsätter långt därifrån och inget tyder på allvarlig skada. Vad säger huvudprincipen?","Curve ball: Spelaren ligger ner efter en smäll, är kontaktbar och utanför spelet. Det finns ingen misstanke om allvarlig skada. Måste du stoppa ett lovande anfall direkt?"],a:["Nej, inte om skadan inte misstänks vara allvarlig och spelaren inte direkt påverkar spelet","Ja, varje liggande spelare kräver omedelbar avblåsning","Ja, men endast om hemmalaget har bollen","Nej, skador får aldrig stoppa spelet"],x:0,r:"Nej, inte automatiskt.",e:"Spelet ska stoppas vid misstanke om allvarlig skada eller om den skadade spelaren direkt påverkar spelet.",s:"Regel 201.2",t:"Spelarsäkerheten går först, men varje mindre skada innebär inte automatisk avblåsning."},
    {id:79,c:"Timeout",n:false,q:"Vem får begära time out för laget?",v:["Vem får begära time out för laget?","En vanlig utespelare som inte är kapten ropar direkt till domaren att laget vill ha time out. Är det en giltig begäran?","Curve ball: Lagets kapten sitter utvisad. En ledare begär time out. Får begäran göras?"],a:["Lagkaptenen eller en ledare","Vilken spelare som helst","Endast lagkaptenen","Endast huvudtränaren"],x:0,r:"Lagkapten eller ledare.",e:"Time out kan endast begäras genom lagkaptenen eller en ledare.",s:"Regel 202.1",t:"Rätten att begära time out är snävare än vem som kan ropa från bänken."},
    {id:80,c:"Timeout",n:false,q:"Hur lång är en time out?",v:["Hur lång är en time out?","Domaren ger extrasignalen som startar time out. När ska nästa extrasignal ges?","Curve ball: Ett lag vill använda 45 sekunder eftersom motståndaren accepterar. Hur lång tid medger regelboken?"],a:["30 sekunder","60 sekunder","45 sekunder","20 sekunder"],x:0,r:"30 sekunder.",e:"Time out startar på domarnas extra signal och avslutas med ny extra signal efter 30 sekunder.",s:"Regel 202.1",t:"Tiden räknas från extrasignalen, inte från den ursprungliga avblåsningen."},
    {id:81,c:"Timeout",n:false,q:"Får en utvisad spelare delta i lagets time out?",v:["Får en utvisad spelare delta i lagets time out?","Laget tar time out medan en spelare sitter på utvisningsbänken. Får spelaren gå till lagets samling?","Curve ball: En utvisad lagkapten vill delta i taktiksnacket under time out. Är det tillåtet?"],a:["Nej","Ja","Ja, om spelaren är lagkapten","Ja, om mindre än en minut återstår av utvisningen"],x:0,r:"Nej.",e:"En utvisad spelare får inte delta i time out.",s:"Regel 202.1",t:"Kaptenstatus ändrar inte detta."},
    {id:82,c:"Speltid",n:false,q:"Hur lång är förlängningen i en match som måste avgöras enligt grundregeln?",v:["Hur lång är förlängningen i en match som måste avgöras enligt grundregeln?","Matchen är oavgjord och tävlingen kräver ett avgörande. Hur länge pågår förlängningen som längst innan straffslagsavgörande?","Curve ball: Förlängningen är inte periodindelad. Vilken maximal speltid anger grundregeln innan straffar tar vid?"],a:["10 minuter eller tills mål görs","5 minuter","20 minuter","Två perioder om 5 minuter"],x:0,r:"10 minuter eller tills mål görs.",e:"Förlängningen spelas i högst tio minuter och avslutas om ett lag gör mål.",s:"Regel 203.1",t:"Förlängningen är inte periodindelad."},
    {id:83,c:"Deltagare",n:false,q:"Hur många spelare får ett lag maximalt notera i matchprotokollet?",v:["Hur många spelare får ett lag maximalt notera i matchprotokollet?","Ett lag vill skriva in 21 spelare eftersom två är reservmålvakter. Är det tillåtet?","Curve ball: Målvakter räknas också som spelare. Hur många spelare totalt får därför finnas noterade?"],a:["20","19","21","22"],x:0,r:"20 spelare.",e:"Varje lag får använda högst 20 spelare, inklusive utespelare och målvakter.",s:"Regel 301.1",t:"Ledare räknas separat."},
    {id:84,c:"Deltagare",n:false,q:"Vilket minsta manskap krävs för att domarna ska kunna starta matchen?",v:["Vilket minsta manskap krävs för att domarna ska kunna starta matchen?","Ett lag har fem utespelare men ingen korrekt utrustad målvakt vid matchstart. Kan matchen startas enligt grundregeln?","Curve ball: Sex spelare är på plats, men samtliga är utrustade som utespelare. Uppfyller laget startkravet?"],a:["Minst fem utespelare och en korrekt utrustad målvakt","Fyra utespelare och en målvakt","Sex valfria spelare","Fem spelare totalt"],x:0,r:"Fem utespelare och en målvakt.",e:"För att starta krävs minst fem utespelare och en korrekt utrustad målvakt.",s:"Regel 301.2",t:"Startkravet är inte samma sak som minimiantalet under pågående match."},
    {id:85,c:"Deltagare",n:false,q:"Ett lag kan under pågående match inte längre spela med minst fyra spelare. Vad händer?",v:["Ett lag kan under pågående match inte längre spela med minst fyra spelare. Vad händer?","Utvisningar och skador gör att ett lag inte kan ställa upp med fyra spelare. Ska matchen fortsätta?","Curve ball: Ett lag kan bara få ut tre spelare på planen. Motståndaren leder redan med 7–1. Vad är huvudregeln?"],a:["Matchen avbryts","Matchen fortsätter med tre spelare","Laget får fem minuters paus","Motståndaren måste ta av en spelare"],x:0,r:"Matchen avbryts.",e:"Under match måste lagen kunna spela med minst fyra spelare. Annars avbryts matchen och resultatet hanteras enligt regeln.",s:"Regel 301.2",t:"Det uppnådda resultatet kan behållas om det är fördelaktigare för icke felande lag än 5–0."},
    {id:86,c:"Deltagare",n:false,q:"När får ersättaren beträda planen vid ett normalt spelarbyte?",v:["När får ersättaren beträda planen vid ett normalt spelarbyte?","Spelare A är på väg över sargen i byteszonen men har ännu inte lämnat planen helt. Får ersättaren gå in?","Curve ball: Måste den utgående spelaren ha båda fötterna utanför planen innan ersättaren går in?"],a:["När den utgående spelaren är på väg över sargen","Först när den utgående spelaren sitter på bänken","Så fort spelarna får ögonkontakt","Endast vid avblåsning"],x:0,r:"När spelaren är på väg över sargen.",e:"Den utgående spelaren ska vara på väg över sargen innan ersättaren får beträda spelplanen.",s:"Regel 302.1",t:"Regeln kräver inte att spelaren redan sitter på bänken."},
    {id:87,c:"Deltagare",n:false,q:"En spelare lämnar planen utanför den egna byteszonen. När får spelaren ersättas?",v:["En spelare lämnar planen utanför den egna byteszonen. När får spelaren ersättas?","En spelare kliver över sargen nära hörnet i stället för i byteszonen. Laget vill direkt sätta in en ersättare. Vad gäller?","Curve ball: Spelaren lämnar planen på fel ställe på grund av att hen är trött, inte skadad. När kan ersättaren gå in?"],a:["Först när spelet är avblåst","Omedelbart","Efter tre sekunder","När domaren ger fördel"],x:0,r:"Vid nästa avblåsning.",e:"En spelare som lämnar planen på annat ställe än den egna byteszonen får inte ersättas förrän spelet är avblåst.",s:"Regel 302.1",t:"Skilj detta från ett korrekt byte i byteszonen."},
    {id:88,c:"Målvakt",n:false,q:"En spelare är markerad som målvakt i matchprotokollet. Får spelaren senare i samma match delta som utespelare med klubba?",v:["En spelare är markerad som målvakt i matchprotokollet. Får spelaren senare i samma match delta som utespelare med klubba?","Lagets reservmålvakt har ännu inte spelat. Tränaren vill använda hen som center med klubba i tredje perioden. Är det tillåtet?","Curve ball: En M-markerad spelare tar av målvaktsutrustningen och klär sig korrekt som utespelare. Får hen då spela med klubba i samma match?"],a:["Nej","Ja","Ja, om spelaren inte stått i mål ännu","Ja, efter godkännande av motståndarna"],x:0,r:"Nej.",e:"En spelare som markerats som målvakt får inte i samma match delta som utespelare med klubba.",s:"Regel 303.1",t:"Det är markeringen som målvakt i matchen som är avgörande."},
    {id:89,c:"Målvakt",n:false,q:"Hur lång tid får ett lag högst för att korrekt utrusta en utespelare som måste ersätta målvakten på grund av skada eller utvisning?",v:["Hur lång tid får ett lag högst för att korrekt utrusta en utespelare som måste ersätta målvakten på grund av skada eller utvisning?","Målvakten skadas och ingen reservmålvakt finns. Hur lång tid har laget för att klä en utespelare till målvakt?","Curve ball: Laget använder tiden för målvaktsbyte till uppvärmning. Vilket alternativ beskriver regeln korrekt?"],a:["Högst 3 minuter och tiden får inte användas till uppvärmning","Högst 5 minuter inklusive uppvärmning","Högst 2 minuter","Ingen tidsgräns"],x:0,r:"Högst tre minuter.",e:"Ersättaren får högst tre minuter för korrekt utrustning och ingen del av tiden får användas till uppvärmning.",s:"Regel 303.1",t:"Tiden är till för utrustningsbytet, inte för fysisk förberedelse."},
    {id:90,c:"Lagkapten",n:false,q:"När får ett lag byta lagkapten under match?",v:["När får ett lag byta lagkapten under match?","Kaptenen spelar dåligt och tränaren vill ge bindeln till en annan spelare i pausen. Är det ett giltigt skäl?","Curve ball: Kaptenen blir skadad och kan inte fortsätta. Får laget utse en ny kapten?"],a:["Vid skada, sjukdom eller matchstraff","När som helst i en paus","Efter varje period","Endast vid matchstraff"],x:0,r:"Vid skada, sjukdom eller matchstraff.",e:"Byte av lagkapten får endast ske av dessa skäl och tiden för bytet ska noteras.",s:"Regel 304.1",t:"Taktiska skäl räcker inte."},
    {id:91,c:"Lagkapten",n:false,q:"En lagkapten har ersatts som kapten på grund av skada men kan senare åter spela. Får spelaren åter bli lagkapten i samma match?",v:["En lagkapten har ersatts som kapten på grund av skada men kan senare åter spela. Får spelaren åter bli lagkapten i samma match?","Kaptenen skadas, ersätts som kapten och återkommer senare till spel. Kan bindeln lämnas tillbaka?","Curve ball: Den ursprungliga kaptenen blir spelklar igen i tredje perioden. Laget vill återställa kaptensrollen. Vad gäller?"],a:["Nej","Ja","Ja, efter domarnas godkännande","Ja, men bara i förlängning"],x:0,r:"Nej.",e:"En spelare som ersatts som lagkapten får inte åter fungera som lagkapten i samma match.",s:"Regel 304.1",t:"Spelaren kan åter spela men inte återta kaptensrollen."},
    {id:92,c:"Lagkapten",n:false,q:"Lagkaptenen sitter utvisad och domaren har inte tilltalat kaptenen. Får kaptenen på eget initiativ diskutera ett domslut med domaren?",v:["Lagkaptenen sitter utvisad och domaren har inte tilltalat kaptenen. Får kaptenen på eget initiativ diskutera ett domslut med domaren?","En utvisad kapten ropar att hen vill ha en regelförklaring. Domaren har inte vänt sig till kaptenen. Har kaptenen sin normala talerätt?","Curve ball: Kaptenen är utvisad. Laget behöver begära time out. Vilket är undantaget från begränsningen i kommunikationen?"],a:["Nej; under utvisningen saknas den normala talerätten, med undantag för begäran om time out","Ja, kaptensrätten gäller alltid","Ja, men endast i pausen","Nej, och laget får inte heller begära time out"],x:0,r:"Nej.",e:"En utvisad lagkapten har inte rätt att tala med domarna om hen inte blir tilltalad. Begäran om time out är undantaget.",s:"Regel 304.2",t:"Det här är en bra curve ball: kaptenens rättigheter begränsas under utvisningen."},
    {id:93,c:"Ledare",n:false,q:"Får en ledare beträda spelplanen under match utan domarnas tillåtelse?",v:["Får en ledare beträda spelplanen under match utan domarnas tillåtelse?","En ledare springer in för att hjälpa en spelare utan att invänta domarnas tillåtelse. Är det normalt tillåtet?","Curve ball: Vilket angivet undantag finns från huvudregeln att ledare inte får beträda planen utan domarnas tillåtelse?"],a:["Nej, med undantag för time out","Ja, om en spelare är skadad","Ja, huvudtränaren får alltid gå in","Nej, inte ens under time out"],x:0,r:"Nej, förutom vid time out.",e:"Ledare får inte beträda spelplanen utan domarnas tillåtelse, med undantag för time out.",s:"Regel 305.1",t:"Skada innebär inte automatiskt fri rätt att gå in på planen."},
    {id:94,c:"Utrustning",n:false,q:"Två lag har dräkter som domarna bedömer som förväxlingsbara. Vilket lag ska byta?",v:["Två lag har dräkter som domarna bedömer som förväxlingsbara. Vilket lag ska byta?","Hemmalaget spelar i mörkblått och bortalaget i svart. Domarna bedömer dräkterna som för lika. Vem ansvarar för färgbytet?","Curve ball: Bortalaget tycker att hemmalaget borde byta eftersom hemmalaget har reservställ. Vad säger grundregeln när dräkterna är förväxlingsbara?"],a:["Bortalaget","Hemmalaget","Laget med lägst serienummer","Domarna lottar"],x:0,r:"Bortalaget.",e:"Om dräkterna bedöms som förväxlingsbara ska bortalaget byta.",s:"Regel 401.1",t:"Det är domarnas bedömning av förväxlingsrisken som utlöser kravet."},
    {id:95,c:"Utrustning",n:false,q:"Får en utespelare bära tröjnummer 1?",v:["Får en utespelare bära tröjnummer 1?","En utespelare kommer till match med nummer 1 på tröjan. Är numret tillåtet för utespelare?","Curve ball: Nummer 1 finns inom intervallet 1–99. Betyder det att en utespelare får använda det?"],a:["Nej","Ja","Ja, om ingen målvakt har nummer 1","Ja, efter dispens från domarna"],x:0,r:"Nej.",e:"Nummer 1–99 får användas, men nummer 1 är inte tillåtet för utespelare.",s:"Regel 401.3",t:"Intervallet har ett uttryckligt undantag."},
    {id:96,c:"Utrustning",n:false,q:"En spelare tappar en sko under pågående spel. Måste spelaren omedelbart lämna planen?",v:["En spelare tappar en sko under pågående spel. Måste spelaren omedelbart lämna planen?","En utespelare tappar ena skon mitt i ett anfall men fortsätter spela. Är fortsatt spel till nästa avblåsning tillåtet?","Curve ball: Spelaren tappar båda skorna i samma sekvens. Hur länge får hen enligt regeln fortsätta?"],a:["Nej, spelaren får spela vidare till nästa avblåsning","Ja, spelaren måste lämna omedelbart","Ja, men bara om båda skorna tappas","Spelaren får fortsätta resten av perioden"],x:0,r:"Spelaren får fortsätta till nästa avblåsning.",e:"En spelare som tappar en eller båda skorna under spel får spela vidare till nästa avblåsning.",s:"Regel 401.4",t:"Tillåtelsen gäller inte obegränsat – nästa avblåsning är gränsen."},
    {id:97,c:"Utrustning",n:false,q:"Får lagkaptenen använda tejp som armbindel?",v:["Får lagkaptenen använda tejp som armbindel?","Lagets ordinarie kaptensbindel saknas och spelaren lindar färgad tejp runt armen. Är det godkänt?","Curve ball: Tejpen är bred, tydlig och har bokstaven K. Kan den ersätta armbindeln?"],a:["Nej","Ja","Ja, om tejpen har avvikande färg","Ja, om båda domarna godkänner"],x:0,r:"Nej.",e:"Lagkaptenen ska bära en väl synlig armbindel på armen. Tejp är inte tillåtet som armbindel.",s:"Regel 404.1",t:"Tydlighet gör inte tejp till en godkänd armbindel."},
    {id:98,c:"Utrustning",n:false,q:"Vilken huvudbonad är uttryckligen tillåten för en utespelare enligt grundregeln?",v:["Vilken huvudbonad är uttryckligen tillåten för en utespelare enligt grundregeln?","En spelare vill bära ett pannband. Vilket utförande är tillåtet enligt regeln?","Curve ball: Ett elastiskt pannband har en knut baktill. Är det tillåtet enligt huvudregeln?"],a:["Ett elastiskt pannband utan knut","Keps med mjuk skärm","Mössa utan tofs","Valfri mjuk huvudbonad"],x:0,r:"Elastiskt pannband utan knut.",e:"Huvudbonader är förbjudna med undantag för pannband som är elastiska och saknar knut.",s:"Regel 405.1",t:"Både materialet och avsaknaden av knut är relevanta."},
    {id:99,c:"Svåra scenarion",n:false,q:"Bortalagets reservmålvakt är markerad M men har inte spelat. En utespelare skadas, och laget vill sätta in reservmålvakten som utespelare med klubba. Vad gäller?",v:["Bortalagets reservmålvakt är markerad M men har inte spelat. En utespelare skadas, och laget vill sätta in reservmålvakten som utespelare med klubba. Vad gäller?","En M-markerad reservmålvakt har suttit på bänken hela matchen. I tredje perioden vill laget använda spelaren som forward med klubba. Domslut?","Curve ball: Spelaren har aldrig varit inne på planen som målvakt och byter till korrekt utespelarklädsel. Hen står ändå markerad M i protokollet. Får hen spela med klubba?"],a:["Nej, M-markeringen hindrar spel som utespelare med klubba i samma match","Ja, eftersom spelaren ännu inte varit målvakt på planen","Ja, om tröjnumret ändras","Ja, om motståndarlagets kapten accepterar"],x:0,r:"Nej.",e:"Det avgörande är att spelaren markerats som målvakt i matchprotokollet; då får spelaren inte delta som utespelare med klubba i samma match.",s:"Regel 303.1",t:"Det här testar skillnaden mellan registrerad roll och faktisk speltid."},
    {id:100,c:"Svåra scenarion",n:false,q:"En utvisad lagkapten vill själv diskutera ett domslut och därefter begära time out. Vilken del är tillåten?",v:["En utvisad lagkapten vill själv diskutera ett domslut och därefter begära time out. Vilken del är tillåten?","Kaptenen sitter på utvisningsbänken. Hen ropar först efter en förklaring av domslutet och säger sedan att laget begär time out. Vad får kaptenen göra utan att först bli tilltalad av domaren?","Curve ball: Under utvisningen saknar kaptenen normal talerätt. Vilken specifik kommunikation med domarna är ändå tillåten?"],a:["Begära time out, men inte på eget initiativ diskutera domslutet","Diskutera domslutet, men inte begära time out","Både diskutera och begära time out","Varken diskutera eller begära time out"],x:0,r:"Time out-begäran är tillåten.",e:"En utvisad kapten får normalt inte tala med domarna om hen inte blir tilltalad, men begäran om time out är uttryckligen undantagen.",s:"Regel 304.2",t:"Två regler i samma situation – läs exakt vad frågan ber om."}
  ];
  const Q = [...(window.VDK_QUESTIONS || []), ...EXTRA_QUESTIONS];
  const STATS_KEY = "vdk-regelgenerator-stats-v1";
  const THEME_KEY = "vdk-regelgenerator-theme";
  const VARIANT_COUNT = 3;
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  let setupMode = "training", session = [], index = 0, score = 0, answers = [], currentSetup = null;

  function stats(){try{return JSON.parse(localStorage.getItem(STATS_KEY)||'{"answered":0,"correct":0,"categories":{}}')}catch{return {answered:0,correct:0,categories:{}}}}
  function saveStats(result){const st=stats();st.rules??={};result.forEach(({q,ok})=>{st.answered++;if(ok)st.correct++;st.categories[q.c]??={answered:0,correct:0};st.categories[q.c].answered++;if(ok)st.categories[q.c].correct++;const key=String(q.baseId??q.id);st.rules[key]??={answered:0,correct:0,variants:{}};st.rules[key].answered++;if(ok)st.rules[key].correct++;st.rules[key].variants[q.variant??0]??={answered:0,correct:0};st.rules[key].variants[q.variant??0].answered++;if(ok)st.rules[key].variants[q.variant??0].correct++});localStorage.setItem(STATS_KEY,JSON.stringify(st));updateDashboard()}
  function updateDashboard(){const st=stats(),pct=st.answered?Math.round(st.correct/st.answered*100):null;$("#accuracy-value").textContent=pct===null?"–":pct+"%";$("#questions-answered").textContent=`${st.answered} frågor besvarade`;$("#progress-copy").textContent=st.answered?`${st.correct} korrekta svar. Fortsätt där precisionen är lägst.`:"Gör ditt första pass för att börja följa utvecklingen.";$("#bank-count").textContent=Q.length;$("#reset-stats").disabled=!st.answered}
  function resetStats(){const st=stats();if(!st.answered)return;if(!confirm(`Nollställa all din statistik från ${st.answered} besvarade frågor? Detta går inte att ångra.`))return;localStorage.removeItem(STATS_KEY);updateDashboard();$("#progress-copy").textContent="Statistiken är nollställd. Ditt nästa pass blir en ny start."}
  function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function variantText(q,variant){if(Array.isArray(q.v)&&q.v[variant])return q.v[variant];if(variant===1)return `På planen uppstår följande situation: ${q.q} Vilket alternativ följer regelboken?`;if(variant===2)return `Curve ball – skilj avgörande fakta från sådant som kan vilseleda: ${q.q} Vad gäller?`;return q.q}
  function variantUsage(q,variant){return stats().rules?.[String(q.id)]?.variants?.[variant]?.answered||0}
  function chooseVariant(q,cycle=0){const variants=[0,1,2].map(v=>({v,used:variantUsage(q,v)}));const least=Math.min(...variants.map(v=>v.used));const available=variants.filter(v=>v.used===least).map(v=>v.v);return available[cycle%available.length]}
  function withShuffledAnswers(q,variant=0){const choices=q.a.map((text,i)=>({text,correct:i===q.x}));return {...q,baseId:q.id,variant,displayId:`${q.id}-${variant}`,q:variantText(q,variant),choices:shuffle(choices)}}
  function weakProfile(){const st=stats(),categories=Object.entries(st.categories||{}).filter(([,v])=>v.answered).sort((a,b)=>a[1].correct/a[1].answered-b[1].correct/b[1].answered),weakCategories=categories.filter(([,v])=>v.correct/v.answered<.75).map(([c])=>c),missedRules=Object.entries(st.rules||{}).filter(([,v])=>v.correct<v.answered).map(([id])=>Number(id));const accuracy=st.answered?st.correct/st.answered:0;return {st,weakCategories,missedRules,high:st.answered>=20&&(accuracy>=.88||missedRules.length<=2)}}
  function weightedWeakPool(){const profile=weakProfile(),missed=new Set(profile.missedRules),weak=new Set(profile.weakCategories),focus=shuffle(Q.filter(q=>missed.has(q.id)||weak.has(q.c))),general=shuffle(Q.filter(q=>!missed.has(q.id)&&!weak.has(q.c)));if(!focus.length)return shuffle(Q);if(profile.high){const mixed=[];while(focus.length||general.length){if(focus.length)mixed.push(focus.shift());for(let i=0;i<2&&general.length;i++)mixed.push(general.shift())}return mixed}return [...focus,...general]}
  function poolFor(mode,category){let pool=mode==="new"?Q.filter(q=>q.n):mode==="weak"?weightedWeakPool():[...Q];if(category&&category!=="all")pool=pool.filter(q=>q.c===category);return pool.length?pool:[...Q]}
  function buildSession(mode,count,category){const pool=mode==="weak"?poolFor(mode,category):shuffle(poolFor(mode,category)),out=[];for(let cycle=0;out.length<count;cycle++){const round=cycle?shuffle(pool):pool;for(const q of round){if(out.length>=count)break;out.push(withShuffledAnswers(q,chooseVariant(q,cycle)))}}return out}
  function categories(){return [...new Set(Q.map(q=>q.c))].sort((a,b)=>a.localeCompare(b,"sv"))}
  function openSetup(mode){setupMode=mode;const exam=mode==="exam",fresh=mode==="new",weak=mode==="weak",profile=weak?weakProfile():null;$("#setup-kicker").textContent=exam?"DOMARPROV":fresh?"NYA REGLER 2026":weak?"SMART REPETITION":"SNABBTRÄNING";$("#setup-title").textContent=exam?"Bygg ditt domarprov":fresh?"Träna förändringarna":weak&&profile.high?"Fånga de sista luckorna":weak?"Slipa på svagheterna":"Ställ in ditt pass";$("#setup-copy").textContent=exam?"Facit och analys visas när hela provet är klart.":weak&&profile.high?"Du ligger på en hög nivå. Därför blandar vi hela regelbanken och väger in reglerna du senast missade – utan repetitiva frågor.":weak?"Passet prioriterar dina svagaste områden men visar varje grundregel högst en gång.":"Du får facit, förklaring och regelkälla direkt efter varje svar.";const counts=exam?[25,50,100]:[10,25,50];$("#count-options").innerHTML=counts.map((n,i)=>`<label class="choice"><input type="radio" name="count" value="${n}" ${i===0?'checked':''}><span>${n} frågor</span></label>`).join("");$("#category-field").hidden=fresh||weak;$("#category-options").innerHTML=["all",...categories()].map((c,i)=>`<label class="choice"><input type="radio" name="category" value="${c}" ${i===0?'checked':''}><span>${c==="all"?"Blandade regler":c}</span></label>`).join("");$("#setup-dialog").showModal()}
  function begin(){const count=Number(document.querySelector('input[name="count"]:checked').value),category=document.querySelector('input[name="category"]:checked')?.value||"all";currentSetup={mode:setupMode,count,category};session=buildSession(setupMode,count,category);index=0;score=0;answers=[];$("#setup-dialog").close();showOnly("session");renderQuestion()}
  function showOnly(view){$("#session-view").hidden=view!=="session";$("#result-view").hidden=view!=="result";$("#library-view").hidden=view!=="library";$$('body>main,body>footer,.topbar').forEach(el=>el.hidden=view!=="home");window.scrollTo(0,0)}
  function modeName(){return {training:"SNABBTRÄNING",new:"NYA REGLER",exam:"DOMARPROV",weak:"SVAGA OMRÅDEN"}[currentSetup.mode]}
  function renderQuestion(){const q=session[index];$("#session-mode").textContent=modeName();$("#progress-label").textContent=`${index+1} / ${session.length}`;$("#progress-bar").style.width=`${index/session.length*100}%`;$("#live-score").textContent=`${score} rätt`;$("#question-category").textContent=q.c;$("#question-rule").textContent=q.s;$("#question-text").textContent=q.q;$("#question-tip").textContent=q.t;$("#feedback").hidden=true;$("#answers").innerHTML=q.choices.map((o,i)=>`<button class="answer" data-index="${i}"><i>${i+1}</i><span>${o.text}</span></button>`).join("");$$('.answer').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.index))))}
  function answer(choiceIndex){if(answers[index])return;const q=session[index],chosen=q.choices[choiceIndex],ok=chosen.correct;if(ok)score++;answers[index]={q,ok,choiceIndex};$$('.answer').forEach((b,i)=>{b.disabled=true;if(q.choices[i].correct)b.classList.add('correct');else if(i===choiceIndex)b.classList.add('wrong')});$("#live-score").textContent=`${score} rätt`;if(currentSetup.mode!=="exam")showFeedback(q,ok);else setTimeout(next,280)}
  function showFeedback(q,ok){const f=$("#feedback");f.hidden=false;f.dataset.correct=String(ok);$("#feedback-icon").textContent=ok?"✓":"×";$("#feedback-title").textContent=ok?"Korrekt bedömt":"Inte riktigt";$("#feedback-ruling").textContent=q.r;$("#feedback-explanation").textContent=q.e;$("#feedback-source").textContent=`${q.s} · Regelhandbok 2026`;$("#next-question").textContent=index===session.length-1?"Visa resultat →":"Nästa fråga →";f.scrollIntoView({behavior:"smooth",block:"nearest"})}
  function next(){if(!answers[index])return;if(index<session.length-1){index++;renderQuestion()}else finish()}
  function finish(){saveStats(answers);showOnly("result");const pct=Math.round(score/session.length*100);$("#result-percent").textContent=pct+"%";$("#result-fraction").textContent=`${score} av ${session.length} rätt`;$("#result-title").textContent=pct>=90?"Matchklar!":pct>=75?"Stabil nivå":pct>=60?"På rätt väg":"Dags för en ny period";$("#result-message").textContent=pct>=90?"Mycket stark regelträff. Fortsätt med svaga områden för att hålla nivån.":"Gå igenom områdena nedan och kör ett nytt fokuserat pass.";const grouped={};answers.forEach(a=>{grouped[a.q.c]??={n:0,c:0};grouped[a.q.c].n++;if(a.ok)grouped[a.q.c].c++});$("#result-breakdown").innerHTML=Object.entries(grouped).sort((a,b)=>a[1].c/a[1].n-b[1].c/b[1].n).map(([c,v])=>`<div class="breakdown-row"><strong>${c}</strong><span>${v.c} / ${v.n} rätt</span></div>`).join("")}
  function renderLibrary(){const term=$("#rule-search").value.trim().toLocaleLowerCase("sv"),cat=$("#rule-filter").value;const rows=Q.filter(q=>(cat==="all"||q.c===cat)&&(`${q.q} ${q.r} ${q.e} ${q.s}`.toLocaleLowerCase("sv").includes(term)));$("#library-list").innerHTML=rows.length?rows.map(q=>`<article class="rule-item"><header><span>${q.c}</span><span>${q.n?'NY 2026':'REGEL 2026'}</span></header><h3>${q.q}</h3><p><strong>${q.r}</strong> ${q.e}</p><footer>${q.s}</footer></article>`).join(""):"<p>Inga regler matchade sökningen.</p>"}
  function openLibrary(){showOnly("library");$("#rule-filter").innerHTML='<option value="all">Alla områden</option>'+categories().map(c=>`<option>${c}</option>`).join('');renderLibrary()}
  function init(){if(localStorage.getItem(THEME_KEY)==="dark")document.body.classList.add("dark");updateDashboard();$$('[data-start-mode]').forEach(b=>b.addEventListener('click',()=>openSetup(b.dataset.startMode)));$("#weak-mode").addEventListener('click',()=>openSetup('weak'));$("#reset-stats").addEventListener('click',resetStats);$("#begin-session").addEventListener('click',e=>{e.preventDefault();begin()});$("#next-question").addEventListener('click',next);$("#quit-session").addEventListener('click',()=>{if(confirm("Avsluta pågående pass?"))showOnly("home")});$("#retry-session").addEventListener('click',()=>{session=buildSession(currentSetup.mode,currentSetup.count,currentSetup.category);index=score=0;answers=[];showOnly("session");renderQuestion()});$("#back-home").addEventListener('click',()=>showOnly("home"));$("#open-library").addEventListener('click',openLibrary);$("#close-library").addEventListener('click',()=>showOnly("home"));$("#rule-search").addEventListener('input',renderLibrary);$("#rule-filter").addEventListener('change',renderLibrary);$("#theme-toggle").addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem(THEME_KEY,document.body.classList.contains('dark')?'dark':'light')});document.addEventListener('keydown',e=>{if(!$("#session-view").hidden){if(/^[1-4]$/.test(e.key)&&!answers[index])$("#answers").children[Number(e.key)-1]?.click();if(e.key==='Enter'&&answers[index]&&currentSetup.mode!=="exam")next()}})}
  init();
})();
