/* VDK Regelgenerator 2026 – development expansion.
   Freshly worded classic rule-test scenarios, kept on development level and tied to 2026 rules. */
(()=>{"use strict";
const Q=[
{id:9001,c:"Tekning",level:"development",q:"Efter en avblåsning finns ingen grund för inslag, frislag eller straffslag. Hur återupptas spelet?",a:["Tekning","Inslag","Frislag","Straffslag"],x:0,r:"Tekning.",e:"När inget lag kan tilldömas någon annan fast situation återupptas spelet med tekning.",s:"Regel 502.2",t:"Identifiera först orsaken till avblåsningen."},
{id:9002,c:"Tekning",level:"development",q:"Vid tekning på mittlinjen ska tekaren välja sida om bollen. Vem har rätt att välja?",a:["Bortalagets tekare","Hemmalagets tekare","Lagkaptenen i hemmalaget","Domaren"],x:0,r:"Bortalagets tekare väljer.",e:"Vid tekning på mittlinjen väljer bortalagets tekare sida om bollen.",s:"Regel 502.5",t:"Skilj mittlinjen från övriga tekningspunkter."},
{id:9003,c:"Tekning",level:"development",q:"En tekning går direkt in i motståndarnas mål utan att någon annan spelare rör bollen. Domslut?",a:["Mål","Tekningen görs om","Frislag","Tekning efter underkänt mål"],x:0,r:"Mål.",e:"En korrekt utförd tekning får gå direkt i mål.",s:"Regel 502.6",t:"Direkt mål är tillåtet från tekning."},
{id:9004,c:"Tekning",level:"development",q:"Bollen träffar en domare och riktningsförändringen påverkar spelet märkbart. Hur återupptas spelet efter avblåsningen?",a:["Tekning","Frislag","Inslag","Straffslag"],x:0,r:"Tekning.",e:"När en domarträff märkbart påverkar spelet räknas situationen som onaturlig och spelet återupptas med tekning.",s:"Regel 503.6",t:"En domarträff utan märkbar påverkan kräver inte samma åtgärd."},
{id:9005,c:"Inslag och frislag",level:"development",q:"Bollen träffar taket ovanför spelplanen. Varifrån ska inslaget utföras?",a:["1,5 meter från sargen på samma avstånd från mittlinjen","Från närmaste tekningspunkt","Där bollen landar","Från mittpunkten"],x:0,r:"1,5 meter från sargen.",e:"Vid takträff placeras inslaget 1,5 meter från sargen på samma avstånd från mittlinjen som träffpunkten.",s:"Regel 504.2",t:"Takträff leder till inslag."},
{id:9006,c:"Inslag och frislag",level:"development",q:"Hur långt från bollen ska motståndarna omedelbart inta vid ett inslag?",a:["Minst 3 meter, klubban inräknad","Minst 2 meter","Minst 3 meter, klubban inte inräknad","Minst 5 meter"],x:0,r:"Minst 3 meter, klubban inräknad.",e:"Motståndarna ska utan uppmaning inta minst tre meters avstånd inklusive klubban.",s:"Regel 504.3",t:"Samma grundavstånd används vid frislag."},
{id:9007,c:"Inslag och frislag",level:"development",q:"En spelare drar bollen längs golvet med klubbladet för att utföra ett inslag. Är inslaget korrekt utfört?",a:["Nej, bollen ska slås med klubban","Ja, om bollen ligger still före utförandet","Ja, men bara på egen planhalva","Ja, om motståndarna står tre meter bort"],x:0,r:"Nej.",e:"Vid inslag ska bollen slås med klubban; den får inte dras eller lyftas för att sättas i spel.",s:"Regel 504.4",t:"Fokusera på själva utförandet."},
{id:9008,c:"Inslag och frislag",level:"development",q:"Ett korrekt utfört inslag går direkt i motståndarnas mål. Vad döms?",a:["Mål","Tekning","Frislag till försvarande lag","Inslaget görs om"],x:0,r:"Mål.",e:"Ett korrekt utfört inslag får gå direkt i mål.",s:"Regel 504.6",t:"Direkt mål är tillåtet."},
{id:9009,c:"Fördelsregel",level:"development",q:"Ett lag utsätts för en frislagsbelagd förseelse men behåller kontrollen över bollen och får ett bättre anfallsläge av fortsatt spel. Vad kan domarna göra?",a:["Tillämpa fördel","Måste alltid blåsa direkt","Döma tekning","Stoppa spelet och fråga laget"],x:0,r:"Tillämpa fördel.",e:"Fördelsregeln kan användas när icke felande lag har större fördel av fortsatt spel än av frislaget.",s:"Regel 506.1",t:"Bedöm den faktiska spelmässiga fördelen."},
{id:9010,c:"Inslag och frislag",level:"development",q:"Hur nära målvaktsområdet får ett frislag som närmast placeras?",a:["3,5 meter","3 meter","1,5 meter","4 meter"],x:0,r:"3,5 meter.",e:"Frislag får inte placeras närmare målvaktsområdet än 3,5 meter.",s:"Regel 506.2",t:"Placeringen skapar utrymme för försvararnas avstånd."},
{id:9011,c:"Frislagsförseelser",level:"development",q:"En spelare för undan en motståndares klubba med handen för att komma åt bollen. Vilken grundförseelse ska bedömas?",a:["Fasthållning/otillåten påverkan på klubban","Hög klubba","Felaktigt byte","Spel med huvudet"],x:0,r:"Fasthållning/otillåten påverkan på klubban.",e:"Att med hand eller arm föra undan motståndarens klubba omfattas av fasthållningsbestämmelsen.",s:"Regel 507.2",t:"Identifiera grundförseelsen innan eventuell påföljdsnivå bedöms."},
{id:9012,c:"Frislagsförseelser",level:"development",q:"En spelare gör en skottfint med klubban över midjehöjd så nära en motståndare att denne riskerar att träffas. Domslut på grundnivå?",a:["Frislag","Spela vidare","Tekning","Straffslag automatiskt"],x:0,r:"Frislag.",e:"Bestämmelsen om hög sving omfattar även skottfint när en motståndare riskerar att träffas.",s:"Regel 507.3",t:"Kontakt behöver inte ha skett för att risken ska vara relevant."},
{id:9013,c:"Frislagsförseelser",level:"development",q:"En spelare stoppar bollen med låret över knähöjd. Agerandet är inte farligt. Domslut?",a:["Spela vidare","Frislag","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"Att stoppa bollen med låret är inte automatiskt otillåtet spel över knähöjd när agerandet inte är farligt.",s:"Regel 507.4",t:"Skilj lår från otillåtet spel med annan del av kroppen."},
{id:9014,c:"Frislagsförseelser",level:"development",q:"Två spelare kämpar om bollen. Den ena tränger undan motståndaren på annat sätt än skuldra mot skuldra. Domslut på grundnivå?",a:["Frislag","Spela vidare","Tekning","Alltid större lagstraff"],x:0,r:"Frislag.",e:"Otillåten trängning i kamp om bollen leder på grundnivå till frislag.",s:"Regel 507.6",t:"Tillåten trängning har tydliga förutsättningar."},
{id:9015,c:"Målvaktsområdet",level:"development",q:"En utespelare har endast klubbladet inne i målvaktsområdet. Ingen kroppsdel rör golvet i området. Befinner sig spelaren i målvaktsområdet?",a:["Nej","Ja","Ja, om bollen är där","Ja, men bara om spelaren anfaller"],x:0,r:"Nej.",e:"Klubban ensam innebär inte att utespelaren befinner sig i målvaktsområdet.",s:"Regel 507.8",t:"Det är kroppens kontakt med golvet som är avgörande."},
{id:9016,c:"Målvaktsområdet",level:"development",q:"En utespelares knä sätts ned på linjen till målvaktsområdet. Hur bedöms spelarens position?",a:["Spelaren befinner sig i målvaktsområdet","Spelaren är utanför området","Spelaren är utanför om bollen är utanför","Det avgörs av målvaktens position"],x:0,r:"Spelaren befinner sig i målvaktsområdet.",e:"Linjen tillhör målvaktsområdet. En kroppsdel som rör golvet på linjen innebär att spelaren befinner sig i området.",s:"Regel 507.8",t:"Linjen räknas till området."},
{id:9017,c:"Målvakt",level:"development",q:"En motståndare står kvar närmare än tre meter från målvakten och hindrar målvakten från att göra ett utkast. Domslut på grundnivå?",a:["Frislag","Tekning","Spela vidare","Straffslag automatiskt"],x:0,r:"Frislag.",e:"Passivt hindrande av målvaktens utkast inom målområdet eller närmare än tre meter leder till frislag.",s:"Regel 507.10",t:"Bedöm om spelaren faktiskt hindrar utkastet."},
{id:9018,c:"Målvakt",level:"development",q:"Målvakten kastar bollen så att hela bollen passerar mittlinjen i luften utan att först ha berört golv, sarg, spelare eller utrustning. Domslut?",a:["Frislag","Tekning","Inslag","Spela vidare"],x:0,r:"Frislag.",e:"Hela bollen får inte passera mittlinjen direkt från målvaktens kast eller spark utan föregående tillåten beröring.",s:"Regel 507.14",t:"Kontrollera vad bollen har berört före mittlinjen."},
{id:9019,c:"Målvakt",level:"development",q:"Målvakten har bollen under kontroll i fyra sekunder. Vad döms?",a:["Frislag","Mindre lagstraff","Tekning","Spela vidare"],x:0,r:"Frislag.",e:"Målvakten får kontrollera bollen i högst tre sekunder.",s:"Regel 507.16",t:"Kontrolltiden är central."},
{id:9020,c:"Målvakt",level:"development",q:"En medspelare spelar avsiktligt bollen till sin målvakt, som tar emot den med handen eller armen. Vad döms på grundnivå?",a:["Frislag","Tekning","Spela vidare","Alltid straffslag"],x:0,r:"Frislag.",e:"Målvakten får inte med hand eller arm ta emot en avsiktlig passning från en medspelare.",s:"Regel 507.17",t:"Var noga med hur målvakten tar emot bollen."},
{id:9021,c:"Målvakt",level:"development",q:"En medspelare passar avsiktligt bollen till målvakten. Målvakten möter bollen och spelar den vidare med foten. Domslut?",a:["Spela vidare","Frislag","Mindre lagstraff","Tekning"],x:0,r:"Spela vidare.",e:"Förseelsen avser mottagande med hand eller arm; att spela bollen med foten är inte samma handling.",s:"Regel 507.17",t:"Hur bollen tas emot avgör."},
{id:9022,c:"Målvakt",level:"development",q:"Målvakten lägger ned bollen efter två sekunders kontroll och tar omedelbart upp den igen utan att någon annan spelare rört bollen. Börjar en ny tresekundersperiod?",a:["Nej","Ja","Ja, om bollen ligger still","Ja, om målvakten flyttar sig"],x:0,r:"Nej.",e:"Att lägga ned och åter ta upp bollen bryter inte automatiskt målvaktens kontrolltid.",s:"Regel 507.16",t:"Följ den sammanhängande kontrollen."},
{id:9023,c:"Fasta situationer",level:"development",q:"Ett inslag utförs från fel plats men ingen betydande fördel vinns. Vad gör domarna?",a:["Låter inslaget göras om från korrekt plats","Dömer automatiskt mindre lagstraff","Dömer tekning","Godkänner alltid utförandet"],x:0,r:"Inslaget görs om.",e:"Felaktig placering utan ett uppenbart försök att vinna betydande fördel korrigeras genom att den fasta situationen görs om.",s:"Regel 507.15",t:"Skilj korrigering från ett avsiktligt betydande fördelsförsök."},
{id:9024,c:"Straffslag",level:"development",q:"En frislags- eller utvisningsbelagd förseelse hindrar en klar målsituation. Vilken fast situation ska domarna pröva?",a:["Straffslag","Tekning","Inslag","Endast frislag oavsett situation"],x:0,r:"Straffslag.",e:"När en sådan förseelse hindrar en klar målsituation ska straffslagsbestämmelserna tillämpas.",s:"Regel 508",t:"Identifiera om målsituationen var klar."},
{id:9025,c:"Straffslag",level:"development",q:"Under ett straffslag rör sig bollen bakåt. Vad gäller?",a:["Det är inte tillåtet","Det är alltid tillåtet","Det är tillåtet bara efter målvaktskontakt","Det är tillåtet om spelaren inte byter handfattning"],x:0,r:"Det är inte tillåtet.",e:"Bollen ska under straffslaget föras framåt enligt straffslagsbestämmelserna.",s:"Regel 508",t:"Följ bollens rörelse, inte bara spelarens."},
{id:9026,c:"Straffslagsavgörande",level:"development",q:"Efter de fem inledande straffslagen för vardera laget är ställningen lika. Får samma behöriga utespelare slå flera av de följande straffslagen?",a:["Ja","Nej","Endast två gånger","Endast efter att alla andra behöriga spelare slagit"],x:0,r:"Ja.",e:"Efter de fem inledande straffslagen får samma behöriga utespelare användas upprepade gånger enligt 2026 års regler.",s:"Regel 204.1",t:"Använd inte den äldre rotationsregeln."},
{id:9027,c:"Påföljdsbedömning",level:"development",q:"Domarna klassificerar en utvisningsbelagd fysisk handling som oaktsam. Vilken påföljdsnivå hör till klassificeringen?",a:["Mindre lagstraff","Större lagstraff","Lindrigt matchstraff","Grovt matchstraff"],x:0,r:"Mindre lagstraff.",e:"Oaktsamt agerande kopplas till mindre lagstraff i 2026 års påföljdssystem.",s:"Regel 6 kap. – påföljdsnivåer",t:"Använd regeltermerna exakt."},
{id:9028,c:"Påföljdsbedömning",level:"development",q:"Domarna klassificerar en utvisningsbelagd fysisk handling som vårdslös. Vilken påföljdsnivå hör till klassificeringen?",a:["Större lagstraff","Mindre lagstraff","Lindrigt matchstraff","Endast frislag"],x:0,r:"Större lagstraff.",e:"Vårdslöst agerande kopplas till större lagstraff i 2026 års påföljdssystem.",s:"Regel 6 kap. – påföljdsnivåer",t:"Vårdslös och oaktsam är inte synonymer."},
{id:9029,c:"Påföljdsbedömning",level:"development",q:"Domarna klassificerar en fysisk handling som våldsam. Vilken påföljdsnivå hör till klassificeringen?",a:["Lindrigt matchstraff","Större lagstraff","Mindre lagstraff","Endast frislag"],x:0,r:"Lindrigt matchstraff.",e:"Våldsamt agerande kopplas till lindrigt matchstraff i 2026 års påföljdssystem.",s:"Regel 6 kap. – påföljdsnivåer",t:"Klassificera handlingen före påföljden."},
{id:9030,c:"Påföljdsbedömning",level:"development",q:"Domarna klassificerar en fysisk handling som brutal. Vilken påföljdsnivå hör till klassificeringen?",a:["Grovt matchstraff","Lindrigt matchstraff","Större lagstraff","Mindre lagstraff"],x:0,r:"Grovt matchstraff.",e:"Brutalt agerande kopplas till grovt matchstraff i 2026 års påföljdssystem.",s:"Regel 6 kap. – påföljdsnivåer",t:"Den högsta klassificeringen ska inte tonas ned med vardagliga synonymer."},
{id:9031,c:"Utvisningar",level:"development",q:"Icke felande lag har kontroll över bollen när en utvisningsbelagd förseelse sker. Domarna väljer att avvakta utvisningen. När ska utvisningen normalt verkställas?",a:["När felande lag får kontroll över bollen eller vid nästa avblåsning","Vid första bollberöringen av felande lag oavsett kontroll","Först när icke felande lag skjuter","Efter exakt tio sekunder"],x:0,r:"När felande lag får kontroll eller vid nästa avblåsning.",e:"Avvaktande utvisning fortsätter medan icke felande lag har den kontroll som krävs; en ren beröring är inte automatiskt kontroll.",s:"Regel 602",t:"Skilj beröring från kontroll."},
{id:9032,c:"Utvisningar",level:"development",q:"Under en avvaktande utvisning mot Röd träffar bollen Röd 7:s klubblad och studsar direkt tillbaka till Blå, som behåller kontrollen. Ska spelet stoppas enbart på grund av beröringen?",a:["Nej","Ja","Ja, men bara på offensiv planhalva","Ja, om Röd 7 tittar på bollen"],x:0,r:"Nej.",e:"En beröring är inte automatiskt kontroll. Avvaktningen upphör när felande lag får kontroll eller vid annan avblåsning.",s:"Regel 602",t:"Detta är en grundläggande skillnad i matchbedömningen."},
{id:9033,c:"Mål",level:"development",q:"Ett skott avlossas före slutsignalen men bollen passerar mållinjen först efter att speltiden har löpt ut. Ska målet godkännas?",a:["Nej","Ja","Ja, om skottet var på mål","Ja, om målvakten inte rör bollen"],x:0,r:"Nej.",e:"Det avgörande är när bollen helt passerar mållinjen, inte när skottet avlossas.",s:"Regel 2 och målbestämmelserna",t:"Skottögonblick och målögonblick är olika saker."},
{id:9034,c:"Mål",level:"development",q:"Bollen har helt passerat mållinjen på korrekt sätt innan slutsignalen ljuder. Vad döms?",a:["Mål","Inget mål eftersom domaren inte hunnit blåsa","Tekning","Frislag"],x:0,r:"Mål.",e:"När bollen helt har passerat mållinjen på korrekt sätt innan speltiden upphör är målet gjort.",s:"Målbestämmelserna",t:"Bedöm händelsen, inte tidpunkten för domarens signal."},
{id:9035,c:"Fasta situationer",level:"development",q:"Två motståndare begår samtidigt varsin frislagsbelagd förseelse och domarna kan inte avgöra någon riktning. Hur återupptas spelet?",a:["Tekning","Frislag till laget som senast hade bollen","Två frislag","Inslag"],x:0,r:"Tekning.",e:"När samtidiga frislagsbelagda förseelser inte ger en entydig riktning återupptas spelet med tekning.",s:"Regel 503.9",t:"Samtidighet och avsaknad av riktning är avgörande."},
{id:9036,c:"Fasta situationer",level:"development",q:"Ett frislag ska utföras. Motståndarna står korrekt på minst tre meters avstånd inklusive klubborna. Måste utförande lag vänta på en särskild andra signal från domaren?",a:["Nej, inte som generell regel","Ja, alltid","Ja, på offensiv planhalva","Ja, om det är mindre än fem minuter kvar"],x:0,r:"Nej.",e:"Ett korrekt placerat och korrekt utfört frislag kräver inte generellt en särskild andra signal för att få sättas i spel.",s:"Regel 506",t:"Lägg inte till procedurkrav som inte finns i regeln."},
{id:9037,c:"Frislagsförseelser",level:"development",q:"En spelare spelar bollen med huvudet. Vilken typ av återstart ska domaren utgå från om ingen högre påföljd är aktuell?",a:["Frislag","Tekning","Inslag","Spela vidare"],x:0,r:"Frislag.",e:"Otillåtet spel med kroppen enligt frislagsbestämmelserna leder till frislag när ingen högre påföljd är aktuell.",s:"Regel 507",t:"Identifiera först grundförseelsen."},
{id:9038,c:"Frislagsförseelser",level:"development",q:"En spelare hoppar upp och stoppar bollen på ett sätt som inte är tillåtet enligt spelreglerna. Ingen kontakt med motståndare sker. Vilken återstart ska domaren först pröva?",a:["Frislag","Straffslag","Mindre lagstraff automatiskt","Tekning"],x:0,r:"Frislag.",e:"En grundläggande frislagsförseelse leder till frislag om situationen inte innehåller omständigheter som höjer påföljden eller gör straffslag aktuellt.",s:"Regel 507",t:"Börja med grundförseelsen och kontrollera därefter konsekvenserna."},
{id:9039,c:"Spelavstånd",level:"development",q:"En spelare försöker spela bollen med klubban samtidigt som han ligger med båda knäna i golvet. Ingen klar målsituation påverkas. Vilken grundförseelse ska domaren bedöma?",a:["Liggande spel","Hög klubba","Felaktigt byte","Fasthållning"],x:0,r:"Liggande spel.",e:"Spel från en otillåten liggande eller sittande position bedöms enligt bestämmelserna om liggande spel. Om en klar målsituation hindras måste även straffslagsbestämmelserna prövas.",s:"Regel 6 kap. och relevanta spelbestämmelser",t:"Håll isär grundförseelsen och konsekvensen för en målsituation."},
{id:9040,c:"Matchledning",level:"development",q:"Domaren ser en regelstridig handling men icke felande lag får omedelbart ett tydligt bättre anfallsläge genom att spelet fortsätter. Vilken princip kan användas?",a:["Fördelsregeln","Automatisk tekning","Alltid omedelbar avblåsning","Straffslagsavgörande"],x:0,r:"Fördelsregeln.",e:"När fortsatt spel ger icke felande lag en större faktisk fördel kan domaren låta spelet fortsätta enligt fördelsregeln.",s:"Regel 506.1",t:"Fördelen ska vara verklig i matchsituationen."}
];
const base=Array.isArray(window.VDK_QUESTIONS)?window.VDK_QUESTIONS:[];
const ids=new Set(Q.map(q=>q.id));
window.VDK_QUESTIONS=[...base.filter(q=>!ids.has(q.id)),...Q];
window.VDK_DEVELOPMENT_CLASSIC_QUESTIONS=Q;
})();