(() => {
"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const ADVANCED=new Set(["Matchstraff","Straffslag","Straffslagsavgörande","Ledare och personliga straff","Klubbförseelser","Målvaktsområdet","Målvakt","Utvisningar","Mål","Svåra scenarion"]);
const TIP_KEY="vdk-show-tips";
const state={active:false,level:null,pool:[],session:[],index:0,score:0,answers:[],count:10,showTips:true};
function all(){return Array.isArray(window.VDK_QUESTIONS)?window.VDK_QUESTIONS:[]}
function difficulty(q){if(q.level)return q.level;if(q.n||ADVANCED.has(q.c))return"advanced";return"development"}
function poolFor(level){return all().filter(q=>difficulty(q)===level)}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function variant(q){const texts=Array.isArray(q.v)&&q.v.length?q.v:[q.q];return texts[Math.floor(Math.random()*texts.length)]||q.q}
function prepared(q){const answers=q.a.map((text,i)=>({text,correct:i===q.x}));return {...q,q:variant(q),choices:shuffle(answers)}}
function label(l){return l==="development"?"UTVECKLING":l==="advanced"?"AVANCERAD":"☠ DEATH MODE"}
function show(view){$("#session-view").hidden=view!=="session";$("#result-view").hidden=view!=="result";$("#library-view").hidden=true;$$('body>main,body>footer,.topbar').forEach(el=>el.hidden=view!=="home");window.scrollTo(0,0)}
function savedTipPreference(level){try{const raw=localStorage.getItem(`${TIP_KEY}-${level}`);if(raw!==null)return raw==="1"}catch(e){}return level!=="death"}
function saveTipPreference(level,value){try{localStorage.setItem(`${TIP_KEY}-${level}`,value?"1":"0")}catch(e){}}
function applyTipVisibility(){const tip=$(".tip-card");if(tip)tip.hidden=!state.showTips}
function startLevel(level){
 const pool=poolFor(level); if(!pool.length){alert(`Tekniskt fel: ${label(level)} har inga laddade frågor.`);return}
 state.level=level;state.pool=pool;state.active=true;state.showTips=savedTipPreference(level);
 $("#setup-kicker").textContent=label(level);$("#setup-title").textContent=level==="death"?"Du bad om det.":`Starta ${label(level).toLowerCase()}`;
 $("#setup-copy").textContent=`${pool.length} frågor är tillgängliga på denna nivå. Endast ${label(level).toLowerCase()} används i passet.`;
 const counts=[10,25,50].filter(n=>n<=pool.length);if(!counts.length)counts.push(pool.length);
 $("#count-options").innerHTML=counts.map((n,i)=>`<label class="choice"><input type="radio" name="count" value="${n}" ${i===0?'checked':''}><span>${n} frågor</span></label>`).join("");
 let tipOption=$("#vdk-tip-option");if(!tipOption){tipOption=document.createElement("label");tipOption.id="vdk-tip-option";tipOption.className="choice";$("#category-field").before(tipOption)}
 tipOption.innerHTML=`<input type="checkbox" id="vdk-show-tips" ${state.showTips?'checked':''}><span>Visa VDK-tips under passet</span>`;
 tipOption.querySelector("input").addEventListener("change",e=>{state.showTips=e.target.checked;saveTipPreference(level,state.showTips)});
 $("#category-field").hidden=true;$("#setup-dialog").showModal();
}
function beginCustom(e){if(!state.active)return;e.preventDefault();e.stopImmediatePropagation();const checked=document.querySelector('input[name="count"]:checked');const tipCheck=$("#vdk-show-tips");if(tipCheck){state.showTips=tipCheck.checked;saveTipPreference(state.level,state.showTips)}state.count=Math.min(Number(checked?.value||10),state.pool.length);state.session=shuffle(state.pool).slice(0,state.count).map(prepared);state.index=0;state.score=0;state.answers=[];$("#setup-dialog").close();show("session");applyTipVisibility();render()}
function render(){const q=state.session[state.index];if(!q){alert("Tekniskt fel: frågan kunde inte laddas.");return home()}
 $("#session-mode").textContent=label(state.level);$("#progress-label").textContent=`${state.index+1} / ${state.session.length}`;$("#progress-bar").style.width=`${state.index/state.session.length*100}%`;$("#live-score").textContent=`${state.score} rätt`;$("#question-category").textContent=q.c;$("#question-rule").textContent=q.s;$("#question-text").textContent=q.q;$("#question-tip").textContent=q.t||"Läs hela situationen innan du väljer domslut.";applyTipVisibility();$("#feedback").hidden=true;
 $("#answers").innerHTML=q.choices.map((o,i)=>`<button class="answer" data-level-answer="${i}"><i>${i+1}</i><span>${o.text}</span></button>`).join("");$$('[data-level-answer]').forEach(b=>b.addEventListener('click',()=>answer(Number(b.dataset.levelAnswer))));
}
function answer(i){if(state.answers[state.index])return;const q=state.session[state.index],chosen=q.choices[i],ok=!!chosen?.correct;if(ok)state.score++;state.answers[state.index]={q,ok};$$('[data-level-answer]').forEach((b,k)=>{b.disabled=true;if(q.choices[k].correct)b.classList.add('correct');else if(k===i)b.classList.add('wrong')});$("#live-score").textContent=`${state.score} rätt`;const f=$("#feedback");f.hidden=false;f.dataset.correct=String(ok);$("#feedback-icon").textContent=ok?"✓":"×";$("#feedback-title").textContent=ok?"Korrekt bedömt":"Inte riktigt";$("#feedback-ruling").textContent=q.r;$("#feedback-explanation").textContent=q.e;$("#feedback-source").textContent=`${q.s} · Regelhandbok 2026`;$("#next-question").textContent=state.index===state.session.length-1?"Visa resultat →":"Nästa fråga →"}
function nextCustom(e){if(!state.active)return;e.preventDefault();e.stopImmediatePropagation();if(!state.answers[state.index])return;if(state.index<state.session.length-1){state.index++;render()}else finish()}
function finish(){show("result");const pct=Math.round(state.score/state.session.length*100);$("#result-percent").textContent=pct+"%";$("#result-fraction").textContent=`${state.score} av ${state.session.length} rätt`;$("#result-title").textContent=state.level==="death"?(pct===100?"Du överlevde Death Mode":"Death Mode vann den här gången"):pct>=90?"Mycket stark nivå":pct>=75?"Stabil nivå":"Fortsätt slipa";$("#result-message").textContent=`${label(state.level)} genomfört med ${pct}% rätt.`;const g={};state.answers.forEach(a=>{g[a.q.c]??={n:0,c:0};g[a.q.c].n++;if(a.ok)g[a.q.c].c++});$("#result-breakdown").innerHTML=Object.entries(g).map(([c,v])=>`<div class="breakdown-row"><strong>${c}</strong><span>${v.c} / ${v.n} rätt</span></div>`).join("")}
function retryCustom(e){if(!state.active)return;e.preventDefault();e.stopImmediatePropagation();state.session=shuffle(state.pool).slice(0,state.count).map(prepared);state.index=0;state.score=0;state.answers=[];show("session");applyTipVisibility();render()}
function home(e){if(e){e.preventDefault();e.stopImmediatePropagation()}state.active=false;state.level=null;state.pool=[];state.session=[];show("home")}
function addUI(){const old=document.querySelector('[data-vdk-level-tools]');if(old)old.remove();const base=document.querySelector('.mode-section');if(!base)return;const section=document.createElement('section');section.className='mode-section';section.dataset.vdkLevelTools='true';section.innerHTML=`<div class="section-heading"><div><span class="eyebrow">NIVÅ</span><h2>Träna på rätt nivå</h2></div><p>Tre separata frågepooler. Ingen nivå blandas med en annan.</p></div><div class="mode-grid"><button class="mode-card white" data-vdk-train="development"><span class="mode-icon">1</span><span class="tag">UTVECKLING</span><h3>Utvecklingsläge</h3><p>Tydligare matchsituationer och regelgrunder.</p><span class="card-link">Starta utveckling →</span></button><button class="mode-card dark" data-vdk-train="advanced"><span class="mode-icon">★</span><span class="tag">AVANCERAD</span><h3>Avancerat läge</h3><p>Mer komplexa situationer och högre krav.</p><span class="card-link">Starta avancerat →</span></button><button class="mode-card dark" data-vdk-train="death"><span class="mode-icon">☠</span><span class="tag">DU BAD OM DET</span><h3>Death Mode</h3><p>Endast de särskilda Death Mode-scenarierna.</p><span class="card-link">Jag ångrar mig inte →</span></button></div>`;base.after(section);section.querySelectorAll('[data-vdk-train]').forEach(b=>b.addEventListener('click',()=>startLevel(b.dataset.vdkTrain)));
 $("#begin-session").addEventListener('click',beginCustom,true);$("#next-question").addEventListener('click',nextCustom,true);$("#retry-session").addEventListener('click',retryCustom,true);$("#back-home").addEventListener('click',e=>{if(state.active)home(e)},true);$("#quit-session").addEventListener('click',e=>{if(state.active&&confirm('Avsluta pågående pass?'))home(e)},true);
}
window.VDK_LEVELS={poolFor,startLevel};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addUI,{once:true});else addUI();
})();